"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { EllipsisVertical, Flag, TrendingDown, TrendingUp } from "lucide-react";

const overview=[{label:"Total Revenue",value:"$200,45.87",change:"+2.5%"},{label:"Active Users",value:"9,528",change:"+9.5%"},{label:"Customer Lifetime Value",value:"$849.54",change:"-1.6%",down:true},{label:"Customer Acquisition Cost",value:"9,528",change:"+3.5%"}];
const churn=[12,18,11,20,27,15,9,13,17,12,14,16].map((v,i)=>({i,v}));
const growth=[10,13,18,22,20,24,27,26,31,35,37,40].map((v,i)=>({i,v}));
const funnel=[{m:"Jan",ad:44,web:12,trial:12,paid:20},{m:"Feb",ad:55,web:22,trial:17,paid:8},{m:"Mar",ad:40,web:35,trial:15,paid:10},{m:"Apr",ad:62,web:18,trial:14,paid:8},{m:"May",ad:48,web:24,trial:15,paid:9},{m:"Jun",ad:57,web:27,trial:13,paid:8}];
const invoices=[{id:"#DF429",date:"April 28, 2016",user:"Jenny Wilson",amount:"$473.85",status:"Complete"},{id:"#HTY274",date:"October 30, 2017",user:"Wade Warren",amount:"$293.01",status:"Complete"},{id:"#LKE600",date:"May 29, 2017",user:"Darlene Robertson",amount:"$782.01",status:"Pending"},{id:"#HRP447",date:"May 20, 2015",user:"Arlene McCoy",amount:"$202.87",status:"Cancelled"},{id:"#WRH647",date:"March 13, 2014",user:"Bessie Cooper",amount:"$490.51",status:"Complete"}];
const productSets={"Daily Sales":[155,380,190,290,178,185,152],"Online Sales":[128,310,220,260,210,235,180],"New Users":[190,275,230,340,260,205,245]};
const activities=[{name:"Francisco Grbbs",code:"PQ-4491C",time:"Just Now"},{name:"Courtney Henry",code:"HK-234G",time:"15 minutes ago"},{name:"Bessie Cooper",code:"LH-2891C",time:"5 months ago"},{name:"Theresa Web",code:"CK-125NH",time:"2 weeks ago"}];

export default function SaasPage(){const [productTab,setProductTab]=useState<keyof typeof productSets>("Daily Sales");const productData=useMemo(()=>productSets[productTab].map((value,index)=>({day:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][index],value})),[productTab]);return <div className="saas-page space-y-6">
  <article className="panel p-5"><h2 className="text-xl font-semibold">Overview</h2><div className="mt-6 grid overflow-hidden rounded-2xl border border-[var(--border)] sm:grid-cols-2 xl:grid-cols-4">{overview.map((item,index)=><div className={`p-5 ${index?"border-t border-[var(--border)] sm:border-l xl:border-t-0":""} ${index===2?"sm:border-l-0 xl:border-l":""}`} key={item.label}><p className="muted text-sm">{item.label}</p><div className="mt-2 flex items-center gap-3"><p className="text-[30px] font-bold leading-[38px] tabular-nums">{item.value}</p><Change value={item.change} down={item.down}/></div></div>)}</div></article>
  <section className="grid gap-6 xl:grid-cols-12">
    <div className="min-w-0 space-y-6 xl:col-span-7 2xl:col-span-8">
      <div className="grid gap-6 lg:grid-cols-2"><MiniChart title="Churn Rate" subtitle="Downgrade to Free plan" value="4.26%" change="0.31%" down data={churn}/><MiniChart title="User Growth" subtitle="New signups website + mobile" value="3,768" change="+3.85%" data={growth}/></div>
      <article className="panel p-6"><CardTitle title="Conversion Funnel"/><div className="mt-6 flex flex-wrap gap-5">{[{n:"Ad Impressions",c:"#3641f5"},{n:"Website Session",c:"#5b75f7"},{n:"Free Trial",c:"#91a7f8"},{n:"Paid",c:"#c7d2fe"}].map(x=><span className="muted flex items-center gap-2 text-xs" key={x.n}><i className="h-2.5 w-2.5 rounded-full" style={{background:x.c}}/>{x.n}</span>)}</div><div className="mt-5 h-[310px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel} margin={{left:-24,right:4}} barCategoryGap="35%"><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,120]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="ad" name="Ad Impressions" stackId="a" fill="#3641f5" radius={[0,0,7,7]} maxBarSize={40}/><Bar dataKey="web" name="Website Session" stackId="a" fill="#5b75f7" maxBarSize={40}/><Bar dataKey="trial" name="Free Trial" stackId="a" fill="#91a7f8" maxBarSize={40}/><Bar dataKey="paid" name="Paid" stackId="a" fill="#c7d2fe" radius={[7,7,0,0]} maxBarSize={40}/></BarChart></ResponsiveContainer></div></article>
      <article className="panel min-w-0 overflow-hidden"><div className="p-6"><h2 className="text-xl font-semibold">Recent Invoices</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Serial No:</th><th>Close Date</th><th>User</th><th>Amount</th><th>Status</th></tr></thead><tbody>{invoices.map(row=><tr key={row.id}><td className="font-semibold">{row.id}</td><td>{row.date}</td><td>{row.user}</td><td className="font-semibold tabular-nums">{row.amount}</td><td><Status value={row.status}/></td></tr>)}</tbody></table></div></article>
    </div>
    <div className="min-w-0 space-y-6 xl:col-span-5 2xl:col-span-4">
      <article className="panel p-6"><CardTitle title="Product Performance"/><div className="soft mt-5 grid grid-cols-3 rounded-lg p-1">{(Object.keys(productSets) as (keyof typeof productSets)[]).map(item=><button className={`rounded-md px-2 py-2 text-sm ${productTab===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted"}`} aria-pressed={productTab===item} onClick={()=>setProductTab(item)} key={item}>{item}</button>)}</div><div className="mt-4 grid grid-cols-2 divide-x divide-[var(--border)] rounded-xl border border-[var(--border)]"><SmallMetric label="Digital Product" value="790"/><SmallMetric label="Physical Product" value="572" down/></div><div className="mt-4 rounded-xl border border-[var(--border)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="muted text-sm font-medium">Average Daily Sales</p><p className="mt-1 text-2xl font-semibold">$2,950</p></div><Change value="0.52%" down/></div><div className="mt-4 h-[190px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={productData} margin={{top:4,left:0,right:2,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:11}} dy={7}/><YAxis width={30} domain={[0,400]} ticks={[0,100,200,300,400]} axisLine={false} tickLine={false} allowDecimals={false} tick={{fill:"var(--muted)",fontSize:11}}/><Tooltip cursor={{fill:"var(--soft)"}} contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="value" fill="#465fff" radius={[5,5,0,0]} maxBarSize={10}/></BarChart></ResponsiveContainer></div></div></article>
      <article className="panel p-6"><CardTitle title="Activities"/><div className="relative mt-6"><div className="absolute bottom-10 left-5 top-6 w-px bg-[var(--border)]" aria-hidden="true"/>{activities.map((item,index)=><div className={`relative flex ${index<activities.length-1?"mb-6":""}`} key={item.name}><span className={`z-10 grid h-10 w-10 shrink-0 place-items-center rounded-full font-semibold ring-4 ring-[var(--panel)] ${index===0?"bg-indigo-100 text-[#465fff]":index===1?"bg-amber-100 text-amber-700":index===2?"bg-rose-100 text-rose-600":"bg-emerald-100 text-emerald-700"}`}>{item.name.split(" ").map(x=>x[0]).join("")}</span><div className="ml-4 min-w-0">{index===0?<div className="mb-1 flex items-center gap-1 text-xs font-medium text-emerald-600"><Flag size={18}/>New invoice</div>:null}<div className="flex flex-wrap items-baseline gap-x-2"><p className="text-sm font-semibold">{item.name}</p><span className="muted text-sm">created invoice</span></div><p className="muted text-sm">{item.code}</p><p className="mt-1 text-xs text-gray-400">{item.time}</p></div></div>)}</div></article>
    </div>
  </section>
 </div>}

function MiniChart({title,subtitle,value,change,down=false,data}:{title:string;subtitle:string;value:string;change:string;down?:boolean;data:{i:number;v:number}[]}){return <article className="panel min-w-0 overflow-hidden p-5 sm:p-6"><CardTitle title={title}/><p className="muted mt-1 break-words text-sm">{subtitle}</p><div className="mt-5 grid min-w-0 grid-cols-1 items-end gap-3 min-[340px]:grid-cols-[minmax(0,1fr)_minmax(96px,120px)]"><div className="min-w-0"><p className="text-2xl font-semibold">{value}</p><p className={`mt-2 text-xs ${down?"text-red-500":"text-emerald-600"}`}>{change} <span className="muted">than last Week</span></p></div><div className="h-20 min-w-0 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id={`mini-${title.replaceAll(" ","")}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={down?"#ef4444":"#12b76a"} stopOpacity=".25"/><stop offset="1" stopColor={down?"#ef4444":"#12b76a"} stopOpacity="0"/></linearGradient></defs><Area type="monotone" dataKey="v" stroke={down?"#ef4444":"#12b76a"} strokeWidth={2} fill={`url(#mini-${title.replaceAll(" ","")})`} dot={false}/></AreaChart></ResponsiveContainer></div></div></article>}
function CardTitle({title}:{title:string}){return <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical size={18}/></button></div>}
function Change({value,down=false}:{value:string;down?:boolean}){return <span className={`badge ${down?"bg-red-50 text-red-500":"bg-emerald-50 text-emerald-600"}`}>{down?<TrendingDown size={12}/>:<TrendingUp size={12}/>} {value}</span>}
function SmallMetric({label,value,down=false}:{label:string;value:string;down?:boolean}){return <div className="p-4"><p className="muted text-sm">{label}</p><p className="mt-1 flex items-center gap-2 text-xl font-semibold">{down?<TrendingDown className="text-red-500" size={14}/>:<TrendingUp className="text-emerald-600" size={14}/>} {value}</p></div>}
function Status({value}:{value:string}){return <span className={`badge ${value==="Complete"?"bg-emerald-50 text-emerald-600":value==="Pending"?"bg-amber-50 text-amber-600":"bg-red-50 text-red-500"}`}>{value}</span>}
