"use client";

import {CalendarDays,Download,MoreVertical,SlidersHorizontal,TrendingUp} from "lucide-react";
import Image from "next/image";
import {useState} from "react";

const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"];
const products=[
  ["/products/denim-jacket.png","Classic Denim Jacket","3 Sizes","Jacket","500","$89.99","100","In Stock"],
  ["/products/chinos.png","Slim Fit Chinos","4 Colors","Pants","500","$49.99","80","In Stock"],
  ["/products/cotton-tshirt.png","Organic Cotton T-Shirt","5 Colors","T-Shirt","220","$25.00","30","Low Stock"],
  ["/products/ankle-boots.png","Leather Ankle Boots","6 Sizes","Footwear","875","$120.00","120","Low Stock"],
  ["/products/grey-jacket.png","Classic Grey Jacket","3 Sizes","Jacket","500","$89.99","100","In Stock"],
];
const Spark=({color}:{color:string})=><svg viewBox="0 0 100 38" className="h-12 w-24"><path d="M1 28 11 12 21 29 31 14 41 26 51 9 61 27 71 16 81 25 91 10 99 29" fill="none" stroke={color} strokeWidth="2"/><path d="M1 28 11 12 21 29 31 14 41 26 51 9 61 27 71 16 81 25 91 10 99 29V38H1Z" fill={color} opacity=".1"/></svg>;

export default function SalesPage(){
 const [period,setPeriod]=useState("Monthly"),[notice,setNotice]=useState("");
 const exportCsv=()=>{const csv=["Product,Product ID,Sales,Earnings,Stocks,Status",...products.map(row=>row.slice(1).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download="sales.csv";link.click();URL.revokeObjectURL(url)};
 return <div className="sales-page space-y-6 text-sm">
  {notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-700">{notice}</div>}
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><div><h1 className="text-[21px] font-semibold">Sales Dashboard</h1><p className="muted mt-1">Track revenue, performance, and sales growth in real-time</p></div><div className="flex flex-wrap gap-3 lg:ml-auto"><button className="btn h-11 px-4"><CalendarDays size={18}/>Aug 19 to Aug 25</button><button className="btn h-11 px-4" onClick={()=>setNotice("Sales filters opened.")}><SlidersHorizontal size={18}/>Filter</button><button className="btn btn-primary h-11 px-4" onClick={exportCsv}><Download size={18}/>Export</button></div></div><div className="mt-6 grid gap-0 overflow-hidden rounded-2xl border border-[var(--border)] sm:grid-cols-2 xl:grid-cols-4">{[["Total Revenue","$10,590","#12b76a"],["Total Sales","1,320","#7f56d9"],["Total Sales","4.38%","#06aed4"],["Refund Rate","1.2%","#f04438"]].map(([title,value,color],index)=><article key={`${title}-${index}`} className="border-[var(--border)] p-5 not-last:border-b sm:nth-[2]:border-l xl:not-last:border-b-0 xl:not-first:border-l"><div className="flex items-center justify-between"><h2 className="font-semibold">{title}</h2><span className="text-xl" style={{color}}>{index===0?"$":index===1?"▣":index===2?"⇄":"↪"}</span></div><p className="mt-2 flex items-center gap-1 text-xs text-emerald-600"><TrendingUp size={14}/>3.2% <span className="muted">vs last month</span></p><div className="mt-7 flex items-end justify-between"><b className="text-[30px] leading-none">{value}</b><Spark color={color}/></div></article>)}</div></section>

  <section className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-[18px] font-semibold">Users &amp; Revenue Statistics</h2><p className="muted mt-1">Visualize month-to-month progress and engagement.</p></div><div className="flex rounded-lg bg-[var(--soft)] p-1">{["Daily","Weekly","Monthly"].map(item=><button key={item} className={`h-10 rounded-md px-4 ${period===item?"bg-[var(--panel)] shadow-sm":"muted"}`} onClick={()=>setPeriod(item)}>{item}</button>)}</div></div><div className="mt-8 flex gap-5 text-xs"><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-[#465fff]"/>Online Sales</span><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-[#9db5ff]"/>Offline Sales</span></div><div className="relative mt-5 h-[260px] overflow-hidden"><div className="absolute inset-0 flex flex-col justify-between text-xs text-[var(--muted)]">{["20K","15K","10K","5K","0"].map(item=><div key={item} className="flex items-center gap-3"><span className="w-7">{item}</span><i className="h-px flex-1 bg-[var(--border)]"/></div>)}</div><svg viewBox="0 0 900 220" preserveAspectRatio="none" className="absolute bottom-7 left-10 right-0 h-[210px] w-[calc(100%-40px)]"><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#465fff" stopOpacity=".2"/><stop offset="1" stopColor="#465fff" stopOpacity="0"/></linearGradient></defs><path d="M0 120 C70 100,120 125,190 105 S300 115,360 88 S470 90,540 63 S650 80,720 50 S820 60,900 40 V220 H0Z" fill="url(#salesFill)"/><path d="M0 120 C70 100,120 125,190 105 S300 115,360 88 S470 90,540 63 S650 80,720 50 S820 60,900 40" fill="none" stroke="#465fff" strokeWidth="3"/><path d="M0 170 C80 150,130 175,200 150 S310 162,380 137 S490 145,560 118 S660 135,735 108 S830 120,900 98" fill="none" stroke="#9db5ff" strokeWidth="3"/></svg><div className="absolute bottom-0 left-10 right-0 flex justify-between text-xs text-[var(--muted)]">{months.map(item=><span key={item}>{item}</span>)}</div></div></section>

  <div className="grid items-stretch gap-6 xl:grid-cols-3">
   <AnalyticsCard title="User Retention" subtitle="User engagement over time">
    <MetricSummary value="24%"/>
    <RetentionGrid/>
   </AnalyticsCard>
   <AnalyticsCard title="Sales by Channel" subtitle="Channel performance overview">
    <MetricSummary value="75"/>
    <div className="mt-7 flex h-8 gap-0.5">{Array.from({length:44},(_,i)=><i key={i} className={`w-2 ${i<14?"bg-[#465fff]":i<29?"bg-cyan-400":"bg-[var(--soft)]"}`}/>)}</div>
    <div className="mt-6 rounded-xl border border-[var(--border)]"><div className="flex gap-3 border-b border-[var(--border)] px-5 py-4 text-xs 2xl:gap-5 2xl:text-sm"><span className="whitespace-nowrap"><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-[#465fff]"/>Website</span><span className="whitespace-nowrap"><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-cyan-400"/>Email</span><span className="whitespace-nowrap"><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full bg-[var(--border)]"/>Social Media</span></div><div className="px-5 pb-5"><p className="muted grid grid-cols-[1fr_50px_60px] gap-2 pt-5"><span>Channels</span><span>Metric</span><span className="text-right">Total</span></p>{[["Website","35","↑ 5.2%"],["Email","25","↓ 5.2%"],["Social Media","59","↑ 5.2%"]].map(row=><p key={row[0]} className="mt-4 grid grid-cols-[1fr_50px_60px] gap-2"><span className="whitespace-nowrap">{row[0]}</span><span>{row[1]}</span><span className={`whitespace-nowrap text-right ${row[2].startsWith("↑")?"text-emerald-600":"text-red-500"}`}>{row[2]}</span></p>)}</div></div>
   </AnalyticsCard>
   <AnalyticsCard title="Sales by Country" subtitle="Country-wise sales overview">
    <WorldSalesMap/>
    <div className="mt-5 space-y-4">{[["us","USA","$20.594","79%"],["fr","France","$20.594","77%"],["jp","Japan","$15.230","68%"],["de","Germany","$16.450","72%"]].map(row=><p key={row[1]} className="grid grid-cols-[24px_1fr_auto_42px] items-center gap-2"><Flag country={row[0]}/><span>{row[1]}</span><span>{row[2]}</span><span className="text-right">{row[3]}</span></p>)}</div>
   </AnalyticsCard>
  </div>

  <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)]"><div className="flex items-center justify-between px-6 py-5"><h2 className="text-[18px] font-semibold">Top Products</h2><div className="flex gap-3"><button className="btn h-10 px-4"><SlidersHorizontal size={17}/>Filter</button><button className="btn h-10 px-4">See All</button></div></div><div className="overflow-x-auto px-5 pb-5"><table className="w-full min-w-[800px] overflow-hidden rounded-xl border border-[var(--border)] text-left"><thead><tr className="border-y border-[var(--border)] text-xs text-[var(--muted)]">{["Product Name","Product ID","Sales","Earnings","Stocks","Status"].map(item=><th key={item} className="px-5 py-4 font-medium">{item}</th>)}</tr></thead><tbody>{products.map(row=><tr key={`${row[1]}-${row[3]}`} className="border-b border-[var(--border)]"><td className="px-5 py-3"><div className="flex items-center gap-3"><Image src={row[0]} alt="" width={48} height={48} className="h-12 w-12 rounded-lg border border-[var(--border)] object-contain p-1"/><span><b className="block">{row[1]}</b><small className="muted">{row[2]}</small></span></div></td>{row.slice(3,7).map((value,i)=><td key={i} className="muted px-5 py-3">{value}</td>)}<td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs ${row[7]==="In Stock"?"bg-emerald-50 text-emerald-600":"bg-red-50 text-red-600"}`}>{row[7]}</span></td></tr>)}</tbody></table></div></section>
 </div>
}
function MetricSummary({value}:{value:string}){return <div className="flex items-center gap-2"><b className="text-[28px] font-medium">{value}</b><span className="whitespace-nowrap text-emerald-600">↑ 3.2%</span><span className="muted whitespace-nowrap">Increased vs last week</span></div>}
function RetentionGrid(){return <><div className="mt-7 space-y-1">{Array.from({length:12},(_,row)=><div className="grid grid-cols-12 gap-1" key={row}>{Array.from({length:12-row},(_,col)=><i className="h-[18px]" key={col} style={{background:`rgba(70,95,255,${Math.max(.18,.98-col*.065-row*.018)})`}}/>)}</div>)}</div><div className="muted mt-3 grid grid-cols-12 text-center text-xs">{Array.from({length:12},(_,i)=><span key={i}>{i+1}</span>)}</div></>}
function WorldSalesMap(){return <div className="relative mt-4 h-[190px] w-full" role="img" aria-label="World map showing sales locations"><Image src="/sales/world-map.png" alt="" fill sizes="(min-width: 1280px) 30vw, 100vw" className="object-contain"/><span className="absolute left-[22%] top-[38%] h-3.5 w-3.5 rounded-full border-2 border-white bg-[#465fff] shadow-sm"/><span className="absolute left-[33%] top-[67%] h-3.5 w-3.5 rounded-full border-2 border-white bg-[#465fff] shadow-sm"/><span className="absolute left-[52%] top-[48%] h-3.5 w-3.5 rounded-full border-2 border-white bg-[#465fff] shadow-sm"/><span className="absolute left-[73%] top-[45%] h-3.5 w-3.5 rounded-full border-2 border-white bg-[#465fff] shadow-sm"/><span className="absolute left-[87%] top-[72%] h-3.5 w-3.5 rounded-full border-2 border-white bg-[#465fff] shadow-sm"/></div>}
function Flag({country}:{country:string}){const backgrounds:Record<string,string>={fr:"linear-gradient(90deg,#1554b7 0 33%,#fff 33% 66%,#ef3340 66%)",jp:"radial-gradient(circle,#e6002d 0 31%,#fff 32%)",de:"linear-gradient(#111 0 33%,#e21d2d 33% 66%,#f8ce00 66%)"};if(country==="us")return <span className="relative h-5 w-5 overflow-hidden rounded-full bg-[repeating-linear-gradient(#e5233f_0_2px,#fff_2px_4px)]"><i className="absolute left-0 top-0 h-2.5 w-2.5 bg-[#3155a4]"/></span>;return <span className="h-5 w-5 rounded-full border border-[var(--border)]" style={{background:backgrounds[country]}}/>}
function AnalyticsCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="h-full rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-6"><div className="flex justify-between"><div><h2 className="text-[18px] font-semibold">{title}</h2><p className="muted mt-1">{subtitle}</p></div><button className="muted h-8"><MoreVertical size={18}/></button></div><div className="mt-6">{children}</div></section>}
