"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { DollarSign, EllipsisVertical, Star, TrendingDown, TrendingUp, Users } from "lucide-react";

const revenue = [{m:"Jan",revenue:155,traffic:18},{m:"Feb",revenue:162,traffic:13},{m:"Mar",revenue:145,traffic:21},{m:"Apr",revenue:138,traffic:18},{m:"May",revenue:132,traffic:16},{m:"Jun",revenue:145,traffic:22},{m:"Jul",revenue:152,traffic:26},{m:"Aug",revenue:148,traffic:21},{m:"Sep",revenue:159,traffic:27},{m:"Oct",revenue:151,traffic:25},{m:"Nov",revenue:164,traffic:31},{m:"Dec",revenue:158,traffic:28}];
const campaigns=[{brand:"Slack",mark:"✣",color:"#7c3aed",title:"Grow your brand by...",status:"Success"},{brand:"Facebook",mark:"f",color:"#1877f2",title:"Make Better Ideas...",status:"Pending"},{brand:"Google Ads",mark:"A",color:"#4285f4",title:"Increase your website tra...",status:"Success"},{brand:"Instagram",mark:"◎",color:"#e1306c",title:"Grow your brand by...",status:"Failed"},{brand:"Google",mark:"G",color:"#ea4335",title:"Grow your brand by...",status:"Success"},{brand:"YouTube",mark:"▶",color:"#ff0000",title:"Grow your brand by...",status:"Success"}];
const traffic=[{label:"New Subscribers",value:"567K",change:"+3.85%",down:false,data:[17,23,20,28,19,24,18,25,20,23]},{label:"Conversion Rate",value:"276K",change:"-5.39%",down:true,data:[14,22,18,25,16,21,17,24,19,22]},{label:"Page Bounce Rate",value:"285",change:"+12.74%",down:false,data:[16,21,18,24,20,25,19,23,18,22]}];
const sources=[{name:"Google",mark:"G",color:"#4285f4",value:79},{name:"Youtube",mark:"▶",color:"#ff0000",value:55},{name:"Facebook",mark:"f",color:"#1877f2",value:48},{name:"Instagram",mark:"◎",color:"#e1306c",value:48}];

export default function MarketingPage(){
  const [period,setPeriod]=useState("Monthly");
  const factor=period==="Quarterly"?1.12:period==="Annually"?1.27:1;
  const trafficRows=useMemo(()=>traffic.map(row=>({...row,value:row.value.endsWith("K")?`${Math.round(Number.parseInt(row.value)*factor)}K`:String(Math.round(Number.parseInt(row.value)*factor))})),[factor]);
  return <div className="space-y-6">
    <section className="grid gap-5 md:grid-cols-3" aria-label="Marketing summary"><Kpi icon={<Star/>} label="Avg. Client Rating" value="7.8/10" change="+20%"/><Kpi icon={<Users/>} label="Instagram Followers" value="5,934" change="-3.59%" down/><Kpi icon={<DollarSign/>} label="Total Revenue" value="$9,758" change="+15%"/></section>
    <section className="grid gap-6 xl:grid-cols-12">
      <div className="min-w-0 space-y-6 xl:col-span-8">
      <article className="panel p-6 xl:col-span-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-xl font-semibold">Impression &amp; Data Traffic</h2><p className="muted mt-1 text-sm">Jun 1, 2024 - Dec 1, 2025</p></div><div className="flex items-start gap-3"><div className="text-right"><p className="muted text-xs">Total Revenue</p><div className="mt-1 flex items-center justify-end gap-3"><p className="text-3xl font-semibold tabular-nums">$9,758.00</p><span className="badge bg-emerald-50 text-emerald-600"><TrendingUp size={13}/>+7.96%</span></div></div><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label="Impression and Data Traffic options"><EllipsisVertical size={18}/></button></div></div><div className="mt-6 h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue} margin={{left:-25,right:6}}><defs><linearGradient id="marketing-revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#465fff" stopOpacity=".22"/><stop offset="1" stopColor="#465fff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,250]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Area type="monotone" dataKey="revenue" stroke="#465fff" strokeWidth={2.3} fill="url(#marketing-revenue)" dot={false}/><Area type="monotone" dataKey="traffic" stroke="#9cb1ff" strokeWidth={2} fill="transparent" dot={false}/></AreaChart></ResponsiveContainer></div></article>
      <article className="panel overflow-hidden xl:col-span-5"><div className="p-6"><CardTitle title="Featured Campaigns"/></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Products</th><th>Campaign</th><th>Status</th></tr></thead><tbody>{campaigns.map((item,index)=><tr key={`${item.brand}-${index}`}><td><div className="flex min-w-28 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[var(--soft)] text-xs font-bold">WG</span><span className="text-sm font-medium">Wilson Gouse</span></div></td><td><div className="flex min-w-44 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-lg font-bold text-white" style={{background:item.color}}>{item.mark}</span><div><p className="truncate text-sm font-medium">{item.title}</p><p className="muted text-xs">Ads campaign</p></div></div></td><td><Status value={item.status}/></td></tr>)}</tbody></table></div></article>
      </div>
      <div className="min-w-0 space-y-6 xl:col-span-4">
      <article className="panel p-6 xl:col-span-7"><CardTitle title="Traffic Stats"/><div className="soft mt-5 grid grid-cols-3 rounded-lg p-1">{["Monthly","Quarterly","Annually"].map(item=><button key={item} onClick={()=>setPeriod(item)} aria-pressed={period===item} className={`rounded-md px-3 py-2 text-sm ${period===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted"}`}>{item}</button>)}</div><div className="mt-3 divide-y divide-[var(--border)]">{trafficRows.map(row=><div className="grid grid-cols-[1fr_120px] items-center gap-5 py-5" key={row.label}><div><p className="muted text-sm">{row.label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{row.value}</p><p className={`mt-1 text-xs ${row.down?"text-red-500":"text-emerald-600"}`}>{row.change} <span className="muted">then last Week</span></p></div><Sparkline values={row.data}/></div>)}</div></article>
      <article className="panel p-6 xl:col-span-5"><CardTitle title="Top Traffic Source"/><div className="mt-4 divide-y divide-[var(--border)]">{sources.map(source=><div className="flex items-center gap-3 py-3" key={source.name}><TrafficSourceIcon name={source.name}/><span className="min-w-20 text-sm font-normal">{source.name}</span><div className="h-2 flex-1 rounded-full bg-[var(--soft)]"><div className="h-full rounded-full bg-[#465fff]" style={{width:`${source.value}%`}}/></div><span className="w-9 text-right text-sm font-normal tabular-nums">{source.value}%</span></div>)}</div><button className="btn mt-3 w-full justify-center">View All</button></article>
      </div>
    </section>
  </div>
}

function Kpi({icon,label,value,change,down=false}:{icon:React.ReactNode;label:string;value:string;change:string;down?:boolean}){return <article className="panel p-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[var(--soft)] [&_svg]:h-5 [&_svg]:w-5">{icon}</span><p className="muted mt-5 text-sm">{label}</p><div className="mt-2 flex items-end justify-between gap-3"><p className="text-[30px] font-semibold leading-none tabular-nums">{value}</p><div className="flex shrink-0 items-center gap-2"><span className={`badge ${down?"bg-red-50 text-red-500":"bg-emerald-50 text-emerald-600"}`}>{down?<TrendingDown size={13}/>:<TrendingUp size={13}/>} {change}</span><span className="muted whitespace-nowrap text-xs">Vs last month</span></div></div></article>}
function CardTitle({title}:{title:string}){return <div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical size={18}/></button></div>}
function TrafficSourceIcon({name}:{name:string}){if(name==="Youtube")return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[var(--border)] bg-white"><svg viewBox="0 0 28 20" className="h-5 w-7" aria-hidden="true"><rect width="28" height="20" rx="6" fill="#ff0000"/><path d="m11 6 7 4-7 4z" fill="#fff"/></svg></span>;if(name==="Facebook")return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[var(--border)] bg-white"><svg viewBox="0 0 24 24" className="h-6 w-6" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="#1877f2"/><path fill="#fff" d="M13.8 20v-7h2.4l.4-2.8h-2.8V8.4c0-.8.2-1.4 1.4-1.4h1.5V4.5c-.3 0-1.2-.1-2.2-.1-2.2 0-3.7 1.3-3.7 3.8v2.1H8.3V13h2.5v7z"/></svg></span>;if(name==="Instagram")return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[var(--border)] bg-white"><svg viewBox="0 0 24 24" className="h-6 w-6" aria-hidden="true"><defs><linearGradient id="marketing-instagram" x1="2" y1="22" x2="22" y2="2"><stop stopColor="#feda75"/><stop offset=".42" stopColor="#d62976"/><stop offset="1" stopColor="#4f5bd5"/></linearGradient></defs><rect x="2" y="2" width="20" height="20" rx="6" fill="url(#marketing-instagram)"/><circle cx="12" cy="12" r="4" fill="none" stroke="#fff" strokeWidth="2"/><circle cx="17.5" cy="6.5" r="1.2" fill="#fff"/></svg></span>;return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-[var(--border)] bg-white"><svg viewBox="0 0 24 24" className="h-6 w-6" aria-hidden="true"><path fill="#4285f4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 0 1-2 3v2.6h3.3c1.9-1.8 2.9-4.4 2.9-7.5"/><path fill="#34a853" d="M12 22c2.7 0 5-.9 6.7-2.3l-3.3-2.6c-.9.6-2.1 1-3.4 1-2.6 0-4.8-1.8-5.6-4.2H3v2.7A10 10 0 0 0 12 22"/><path fill="#fbbc05" d="M6.4 13.9a6 6 0 0 1 0-3.8V7.4H3a10 10 0 0 0 0 9.2z"/><path fill="#ea4335" d="M12 5.9c1.5 0 2.8.5 3.8 1.5l2.9-2.8A9.7 9.7 0 0 0 3 7.4l3.4 2.7C7.2 7.7 9.4 5.9 12 5.9"/></svg></span>}
function Status({value}:{value:string}){return <span className={`badge ${value==="Success"?"bg-emerald-50 text-emerald-600":value==="Pending"?"bg-amber-50 text-amber-600":"bg-red-50 text-red-500"}`}>{value}</span>}
function Sparkline({values}:{values:number[]}){const data=values.map((value,index)=>({index,value}));return <div className="h-16 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id={`spark-${values[0]}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#12b76a" stopOpacity=".25"/><stop offset="1" stopColor="#12b76a" stopOpacity="0"/></linearGradient></defs><Area type="monotone" dataKey="value" stroke="#12b76a" strokeWidth={1.5} fill={`url(#spark-${values[0]})`} dot={false}/></AreaChart></ResponsiveContainer></div>}
