"use client";
import { useState } from "react";
import Image from "next/image";
import { ArrowUpDown, ChevronRight, CircleEllipsis, Eye, Pencil, Search, SlidersHorizontal, Trash2 } from "lucide-react";

function Head({title}:{title:string}){return <header className="catalog-head"><h1>{title}</h1><div>Home <ChevronRight/> <b>{title}</b></div></header>}
const basicUsers=[
 ["Lindsey Curtis","Web Designer","Agency Website","Active","3.9K",17,[22,23,24]],
 ["Kaiya George","Project Manager","Technology","Pending","24.9K",18,[25,26]],
 ["Zain Geidt","Content Writing","Blog Writing","Active","12.7K",17,[27]],
 ["Abram Schleifer","Digital Marketer","Social Media","Cancel","2.8K",20,[28,29,30]],
 ["Carla George","Front-end Developer","Website","Active","4.5K",21,[31,32,33]]
] as const;
const orderRows=[["DE124321","John Doe","johndoe@gmail.com","Software License","$18,50.34","2024-06-15","Complete"],["DE124322","Jane Smith","janesmith@gmail.com","Cloud Hosting","$12,99.00","2024-06-18","Pending"],["DE124323","Michael Brown","michaelbrown@gmail.com","Web Domain","$9,50.00","2024-06-20","Cancel"],["DE124324","Alice Johnson","alicejohnson@gmail.com","SSL Certificate","$2,30.45","2024-06-25","Pending"],["DE124325","Robert Lee","robertlee@gmail.com","Premium Support","$15,20.00","2024-06-30","Complete"]] as const;
const transactionRows=[["Bought PYPL","Success",8],["Bought AAPL","Pending",7],["Sell KKST","Success",15],["Bought FB","Success",2],["Sell AMZN","Failed",10]] as const;
const campaignRows=[["Grow your brand by...","Success",1,1],["Make Better Ideas...","Pending",2,2],["Increase your website tra...","Success",3,3],["Grow your brand by...","Failed",4,4],["Grow your brand by...","Success",5,5],["Grow your brand by...","Success",6,6]] as const;
const productRows=[["TailGrids","UI Kits","$12,499",1],["GrayGrids","Templates","$5498",2],["Uideck","Templates","$4621",3],["FormBold","SaaS","$13843",4],["NextAdmin","Templates","$7523",5],["Form Builder","Templates","$1,377",6],["AyroUI","Templates","$599,00",7]] as const;
const asset=(path:string)=>`https://nextjs-demo.tailadmin.com${path}`;
function Status({children}:{children:string}){return <span className={`basic-status ${children.toLowerCase()}`}>{children}</span>}
export function BasicTables(){return <><Head title="Basic Tables"/><div className="basic-table-page">
 <TableCard title="Basic Table 1"><table><thead><tr><th>User</th><th>Project Name</th><th>Team</th><th>Status</th><th>Budget</th></tr></thead><tbody>{basicUsers.map(([name,role,project,status,budget,user,team])=><tr key={name}><td><div className="basic-person"><Image width={48} height={48} src={asset(`/images/user/user-${String(user).padStart(2,"0")}.jpg`)} alt={name}/><span><b>{name}</b><small>{role}</small></span></div></td><td>{project}</td><td><div className="basic-team">{team.map(member=><Image width={48} height={48} src={asset(`/images/user/user-${member}.jpg`)} alt="Team member" key={member}/>)}</div></td><td><Status>{status}</Status></td><td>{budget}</td></tr>)}</tbody></table></TableCard>
 <TableCard title="Basic Table 2"><div className="basic-table-toolbar"><h3>Recent Orders</h3><span><button><SlidersHorizontal/>Filter</button><button>See all</button></span></div><table><tbody>{orderRows.map(([id,name,email,item,total,date,status])=><tr key={id}><td>{id}</td><td><div className="basic-person"><i>{name.split(" ").map(x=>x[0]).join("")}</i><span><b>{name}</b><small>{email}</small></span></div></td><td>{item}</td><td>{total}</td><td>{date}</td><td><Status>{status}</Status></td><td><button className="icon-only" aria-label="More options"><CircleEllipsis/></button></td></tr>)}</tbody></table></TableCard>
 <TableCard title="Basic Table 3"><div className="basic-table-toolbar"><h3>Latest Transactions</h3></div><table><thead><tr><th>Name</th><th>Date</th><th>Price</th><th>Category</th><th>Status</th><th>Action</th></tr></thead><tbody>{transactionRows.map(([name,status,brand])=><tr key={name}><td><div className="basic-brand"><Image width={48} height={48} src={asset(`/images/brand/brand-${String(brand).padStart(2,"0")}.svg`)} alt="brand"/><b>{name}</b></div></td><td>Nov 23, 01:00 PM</td><td>$2,567.88</td><td>Finance</td><td><Status>{status}</Status></td><td><div className="basic-actions"><button aria-label="View more"><Eye/></button><button aria-label="Delete"><Trash2/></button></div></td></tr>)}</tbody></table></TableCard>
 <TableCard title="Basic Table 4"><div className="basic-table-toolbar"><h3>Featured Campaigns</h3></div><table><thead><tr><th>Products</th><th>Campaign</th><th>Status</th></tr></thead><tbody>{campaignRows.map(([campaign,status,user,brand],index)=><tr key={index}><td><div className="basic-person"><Image width={48} height={48} src={asset(`/images/user/user-${String(user).padStart(2,"0")}.jpg`)} alt="user"/><b>Wilson Gouse</b></div></td><td><div className="basic-brand"><Image width={48} height={48} src={asset(`/images/brand/brand-${String(brand).padStart(2,"0")}.svg`)} alt="brand"/><span><b>{campaign}</b><small>Ads campaign</small></span></div></td><td><Status>{status}</Status></td></tr>)}</tbody></table></TableCard>
 <TableCard title="Basic Table 5"><div className="basic-table-toolbar"><h3>Recent Orders</h3></div><table><thead><tr><th>Products</th><th>Category</th><th>Country</th><th>CR</th><th>Value</th></tr></thead><tbody>{productRows.map(([product,category,value,country])=><tr key={product}><td><b>{product}</b></td><td>{category}</td><td><Image width={48} height={48} className="country-flag" src={asset(`/images/country/country-${String(country).padStart(2,"0")}.svg`)} alt="country"/></td><td>Dashboard</td><td>{value}</td></tr>)}</tbody></table></TableCard>
 </div></>}
function TableCard({title,children}:{title:string;children:React.ReactNode}){return <section className="basic-table-card"><header><h2>{title}</h2></header><div className="basic-table-scroll">{children}</div></section>}

const staffRows=[
 ["Abram Schleifer","Sales Assistant","Edinburgh","57","25 Apr, 2027","$89,500",20],
 ["Charlotte Anderson","Marketing Manager","London","42","12 Mar, 2025","$105,000",21],
 ["Ethan Brown","Software Engineer","San Francisco","30","01 Jan, 2024","$120,000",22],
 ["Isabella Davis","UI/UX Designer","Austin","29","18 Jul, 2025","$92,000",27],
 ["James Wilson","Data Analyst","Chicago","28","20 Sep, 2025","$80,000",24],
 ["Liam Moore","DevOps Engineer","Boston","33","30 Oct, 2024","$115,000",28],
 ["Mia Garcia","Content Strategist","Denver","27","12 Dec, 2027","$70,000",29],
 ["Olivia Johnson","HR Specialist","Los Angeles","40","08 Nov, 2026","$75,000",25],
 ["Sophia Martinez","Product Manager","New York","35","15 Jun, 2026","$95,000",23],
 ["William Smith","Financial Analyst","Seattle","38","03 Feb, 2026","$88,000",26]
] as const;
const applicantRows=[["Lindsey Curtis","Sales Assistant","$89,500","Edinburgh","Hired"],["Kaiya George","Chief Executive Officer","$105,000","London","In Progress"],["Zain Geidt","Junior Technical Author","$120,000","San Francisco","In Progress"],["Abram Schleifer","Software Engineer","$95,000","New York","Hired"],["Carla George","Integration Specialist","$80,000","Chicago","Pending"]] as const;
export function DataTables(){return <><Head title="Data Tables"/><div className="data-table-page"><DataTableOne/><DataTableTwo/><DataTableThree/></div></>}
function DataControls({entries,setEntries,search,setSearch}:{entries:number;setEntries:(value:number)=>void;search:string;setSearch:(value:string)=>void}){return <div className="data-controls"><label>Show <select value={entries} onChange={event=>setEntries(Number(event.target.value))}><option>5</option><option>8</option><option>10</option></select> entries</label><label className="data-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search..." aria-label="Search table"/></label></div>}
function SortHead({children,onClick}:{children:string;onClick:()=>void}){return <th><button onClick={onClick}><span>{children}</span><ArrowUpDown/></button></th>}
function DataFooter({shown,total}:{shown:number;total:number}){return <div className="data-footer"><span>Showing 1 to {shown} of {total} entries</span><nav><button aria-label="Previous page"><ChevronLeftIcon/></button><button className="active">1</button><button>2</button><button>3</button><button aria-label="Next page"><ChevronRight/></button></nav></div>}
function ChevronLeftIcon(){return <ChevronRight style={{transform:"rotate(180deg)"}}/>}
function DataTableOne(){const [entries,setEntries]=useState(10);const [search,setSearch]=useState("");const [sort,setSort]=useState(0);const rows=[...staffRows].filter(row=>row.join(" ").toLowerCase().includes(search.toLowerCase())).sort((a,b)=>String(a[sort]).localeCompare(String(b[sort]))).slice(0,entries);return <TableCard title="Data Table 1"><DataControls entries={entries} setEntries={setEntries} search={search} setSearch={setSearch}/><table className="data-table"><thead><tr>{["User","Position","Office","Age","Start Date","Salary"].map((label,index)=><SortHead onClick={()=>setSort(index)} key={label}>{label}</SortHead>)}</tr></thead><tbody>{rows.map(([name,position,office,age,date,salary,user])=><tr key={name}><td><div className="basic-person"><Image width={48} height={48} src={asset(`/images/user/user-${user}.jpg`)} alt="user"/><b>{name}</b></div></td><td>{position}</td><td>{office}</td><td>{age}</td><td>{date}</td><td>{salary}</td></tr>)}</tbody></table><DataFooter shown={rows.length} total={staffRows.length}/></TableCard>}
function DataTableTwo(){const [entries,setEntries]=useState(10);const [search,setSearch]=useState("");const [sort,setSort]=useState(0);const rows=[...staffRows].filter(row=>row.join(" ").toLowerCase().includes(search.toLowerCase())).sort((a,b)=>String(a[sort]).localeCompare(String(b[sort]))).slice(0,entries);return <TableCard title="Data Table 2"><DataControls entries={entries} setEntries={setEntries} search={search} setSearch={setSearch}/><table className="data-table"><thead><tr>{["User","Position","Office","Age","Start Date","Salary"].map((label,index)=><SortHead onClick={()=>setSort(index)} key={label}>{label}</SortHead>)}<th>Action</th></tr></thead><tbody>{rows.map(([name,position,office,age,date,salary])=><tr key={name}><td><b>{name}</b></td><td>{position}</td><td>{office}</td><td>{age}</td><td>{date}</td><td>{salary}</td><td><div className="basic-actions"><button aria-label="Edit"><Pencil/></button><button aria-label="Delete"><Trash2/></button></div></td></tr>)}</tbody></table><DataFooter shown={rows.length} total={staffRows.length}/></TableCard>}
function DataTableThree(){const [entries,setEntries]=useState(5);const [search,setSearch]=useState("");const rows=applicantRows.filter(row=>row.join(" ").toLowerCase().includes(search.toLowerCase())).slice(0,entries);return <TableCard title="Data Table 3"><DataControls entries={entries} setEntries={setEntries} search={search} setSearch={setSearch}/><table className="data-table"><thead><tr>{["User","Position","Salary","Office","Status"].map(label=><SortHead onClick={()=>{}} key={label}>{label}</SortHead>)}<th>Action</th></tr></thead><tbody>{rows.map(([name,position,salary,office,status])=><tr key={name}><td><div className="basic-person"><i>{name.split(" ").map(word=>word[0]).join("")}</i><span><b>{name}</b><small>demoemail@gmail.com</small></span></div></td><td>{position}</td><td>{salary}</td><td>{office}</td><td><Status>{status}</Status></td><td><div className="basic-actions"><button aria-label="Edit"><Pencil/></button><button aria-label="Delete"><Trash2/></button></div></td></tr>)}</tbody></table><DataFooter shown={rows.length} total={applicantRows.length}/></TableCard>}
