"use client";
import { ChevronRight } from "lucide-react";
import { AreaChart, BarChart as RechartsBarChart, CartesianGrid, Cell, Legend, LineChart as RechartsLineChart, PieChart, PolarAngleAxis, PolarGrid, PolarRadiusAxis, RadarChart as RechartsRadarChart, RadialBarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { TimedArea as Area, TimedBar as Bar, TimedLine as Line, TimedPie as Pie, TimedRadar as Radar, TimedRadialBar as RadialBar } from "@/components/ui/timed-charts";

function Head({title}:{title:string}){return <header className="catalog-head"><h1>{title}</h1><div>Home <ChevronRight/> <b>{title}</b></div></header>}

export function Charts({title,type}:{title:string;type:string}){if(type==="line")return <LineCharts title={title}/>;return <ChartCollection title={title} type={type}/>}
const lineChartData=[{month:"Jan",primary:180,secondary:40,single:22},{month:"Feb",primary:190,secondary:30,single:31},{month:"Mar",primary:170,secondary:50,single:28},{month:"Apr",primary:160,secondary:40,single:35},{month:"May",primary:175,secondary:55,single:32},{month:"Jun",primary:165,secondary:40,single:41},{month:"Jul",primary:170,secondary:70,single:38},{month:"Aug",primary:205,secondary:100,single:44},{month:"Sep",primary:230,secondary:110,single:40},{month:"Oct",primary:210,secondary:120,single:46},{month:"Nov",primary:240,secondary:150,single:43},{month:"Dec",primary:235,secondary:140,single:49}];
function LineCharts({title}:{title:string}){return <><Head title={title}/><div className="space-y-6">{[1,2,3].map(number=><section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)]" key={number}><header className="border-b border-[var(--border)] px-6 py-5"><h3 className="text-base font-medium">Line Chart {number}</h3></header><div className="h-[365px] px-5 pb-5 pt-10 sm:px-8">{number<3?<ResponsiveContainer width="100%" height="100%"><AreaChart data={lineChartData} margin={{top:8,right:10,left:-8,bottom:0}}><defs><linearGradient id={`line-primary-${number}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#465fff" stopOpacity=".28"/><stop offset="1" stopColor="#465fff" stopOpacity="0"/></linearGradient><linearGradient id={`line-secondary-${number}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9cb7ef" stopOpacity=".24"/><stop offset="1" stopColor="#9cb7ef" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}} dy={10}/><YAxis domain={[0,250]} ticks={[0,50,100,150,200,250]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Area animationDuration={1800} animationEasing="ease-in-out" type={number===1?"linear":"monotone"} dataKey="primary" stroke="#465fff" strokeWidth={2} fill={`url(#line-primary-${number})`} dot={false}/><Area animationDuration={1800} animationEasing="ease-in-out" type={number===1?"linear":"monotone"} dataKey="secondary" stroke="#9cb7ef" strokeWidth={2} fill={`url(#line-secondary-${number})`} dot={false}/></AreaChart></ResponsiveContainer>:<ResponsiveContainer width="100%" height="100%"><RechartsLineChart data={lineChartData} margin={{top:8,right:10,left:-8,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}} dy={10}/><YAxis domain={[0,50]} ticks={[0,10,20,30,40,50]} tickFormatter={value=>Number(value).toFixed(2)} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Line animationDuration={1800} animationEasing="ease-in-out" type="monotone" dataKey="single" stroke="#465fff" strokeWidth={2} dot={{r:4,fill:"#465fff",stroke:"#fff",strokeWidth:2}} activeDot={{r:6}}/></RechartsLineChart></ResponsiveContainer>}</div></section>)}</div></>}
function ChartCollection({title,type}:{title:string;type:string}){
 const count=type==="bar"?6:type==="pie"?5:type==="radar"?3:4;
 const charts=Array.from({length:count},(_,index)=><ChartPanel title={type==="bar"?(index===3?"Horizontal Bar Chart":`Bar Chart ${index+1}`):type==="pie"?`Donut Pie Chart ${index+1}`:type==="radar"?`Radar Chart ${index+1}`:index===0?"Radial Chart 1":index===1?"Radar Chart 2":index===2?"Radar Chart 3":"Radar Chart"} key={index}>{type==="bar"?<ReferenceBar variant={index}/>:type==="pie"?<ReferencePie variant={index}/>:type==="radar"?<ReferenceRadar variant={index}/>:<ReferenceRadial variant={index}/>}</ChartPanel>);
 return <><Head title={title}/>{type==="bar"?<div className="grid gap-6 lg:grid-cols-2">{charts.map((chart,index)=><div className={index<2?"lg:col-span-2":""} key={index}>{chart}</div>)}</div>:<div className="grid gap-6 lg:grid-cols-2">{charts}</div>}</>
}
function ChartPanel({title,children}:{title:string;children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)]"><header className="border-b border-[var(--border)] px-6 py-5"><h3 className="text-base font-medium">{title}</h3></header>{children}</section>}
const barData=lineChartData.map((item,index)=>({...item,value:[160,380,190,290,175,185,285,100,205,385,275,100][index],direct:[40,55,48,50,38,42,52,33,45,58,54,41][index],referral:[24,28,26,30,22,25,28,19,26,31,29,23][index],organic:[15,17,16,14,18,16,17,13,16,18,17,15][index],social:[10,12,11,10,12,11,12,9,11,13,12,10][index]}));
function ReferenceBar({variant}:{variant:number}){
 const horizontal=variant===3;
 const stacked=variant===1;
 const chartData=variant===1?barData.slice(0,8):variant===4?barData.slice(0,5).map((item,index)=>({...item,direct:[78,58,68,38,64][index],referral:[88,48,63,23,0][index]})):barData;
 const series=stacked?[
  <Bar key="direct" animationDuration={1800} animationEasing="ease-in-out" name="Direct" dataKey="direct" stackId="sales" fill="#2f3bd3" radius={[0,0,8,8]} barSize={40}/>,
  <Bar key="referral" animationDuration={1800} animationEasing="ease-in-out" name="Referral" dataKey="referral" stackId="sales" fill="#465fff"/>,
  <Bar key="organic" animationDuration={1800} animationEasing="ease-in-out" name="Organic Search" dataKey="organic" stackId="sales" fill="#8098f9"/>,
  <Bar key="social" animationDuration={1800} animationEasing="ease-in-out" name="Social" dataKey="social" stackId="sales" fill="#c7d7fe" radius={[8,8,0,0]}/>
 ]:variant===2||variant===4?[
  <Bar key="direct" animationDuration={1800} animationEasing="ease-in-out" dataKey="direct" fill={variant===4?"#b7cdfc":"#465fff"} radius={[5,5,0,0]}/>,
  <Bar key="referral" animationDuration={1800} animationEasing="ease-in-out" dataKey="referral" fill={variant===4?"#465fff":"#b7cdfc"} radius={[5,5,0,0]}/>
 ]:[<Bar key="value" animationDuration={1800} animationEasing="ease-in-out" dataKey="value" fill="#465fff" radius={horizontal?[0,6,6,0]:[6,6,0,0]} barSize={horizontal?18:22}/>];
 const compact=variant>=2;
 const domain=variant===1?[0,120]:variant===4?[0,100]:[0,400];
 const ticks=variant===1?[0,20,40,60,80,100,120]:variant===4?[0,20,40,60,80,100]:[0,100,200,300,400];
 return <div className={`${compact?"h-[350px]":"h-[365px]"} flex flex-col px-5 pb-5 pt-8 sm:px-8`}>{variant===1?<div className="mb-4 flex flex-wrap items-center gap-x-6 gap-y-2 pl-3 text-sm text-[var(--muted)]">{[["Direct","#2f3bd3"],["Referral","#465fff"],["Organic Search","#8098f9"],["Social","#c7d7fe"]].map(([label,color])=><span className="inline-flex items-center gap-2" key={label}><i className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:color}}/>{label}</span>)}</div>:null}<div className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><RechartsBarChart data={chartData} layout={horizontal?"vertical":"horizontal"} margin={{top:8,right:12,left:horizontal?8:-6,bottom:0}}><CartesianGrid horizontal={!horizontal} vertical={horizontal} stroke="var(--border)"/><XAxis type={horizontal?"number":"category"} dataKey={horizontal?undefined:"month"} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis type={horizontal?"category":"number"} dataKey={horizontal?"month":undefined} domain={horizontal?undefined:domain} ticks={horizontal?undefined:ticks} tickFormatter={variant===4?value=>`${value}%`:undefined} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/>{series}</RechartsBarChart></ResponsiveContainer></div></div>
}
const pieSets=[[{name:"Desktop",value:33,color:"#3641f5"},{name:"Mobile",value:47,color:"#6683f6"},{name:"Tablet",value:20,color:"#d6e3ff"}],[{name:"Downloads",value:28,color:"#8b75e8"},{name:"Apps",value:42,color:"#ff8138"},{name:"Documents",value:14,color:"#fdb022"},{name:"Media",value:16,color:"#32d583"}],[{name:"Chrome",value:45,color:"#465fff"},{name:"Safari",value:30,color:"#12b76a"},{name:"Firefox",value:25,color:"#f79009"}],[{name:"Completed",value:62,color:"#465fff"},{name:"Pending",value:24,color:"#9cb1ff"},{name:"Failed",value:14,color:"#f97066"}],[{name:"Direct",value:38,color:"#465fff"},{name:"Social",value:27,color:"#7f56d9"},{name:"Referral",value:21,color:"#06aed4"},{name:"Other",value:14,color:"#d0d5dd"}]];
function ReferencePie({variant}:{variant:number}){const data=pieSets[variant];return <div className="relative h-[375px] px-4 pb-5 pt-7"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie animationDuration={1800} animationEasing="ease-in-out" data={data} dataKey="value" nameKey="name" cx="50%" cy="43%" innerRadius={variant===0?82:76} outerRadius={variant===0?120:108} paddingAngle={0} stroke="none">{data.map(item=><Cell fill={item.color} key={item.name}/>)}</Pie><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Legend verticalAlign="bottom" iconType="circle" iconSize={9} wrapperStyle={{bottom:28}}/></PieChart></ResponsiveContainer>{variant===1?<div className="pointer-events-none absolute inset-x-0 top-[120px] text-center"><b className="block text-base">Total 135 GB</b><small className="mt-4 block">160</small></div>:null}</div>}
const radarCountries=[{label:"Estonia",a:9,b:4},{label:"Germany",a:8,b:6},{label:"France",a:4,b:7},{label:"Spain",a:6,b:8},{label:"Italy",a:4,b:5},{label:"Canada",a:5,b:6},{label:"Japan",a:7,b:4},{label:"Brazil",a:9,b:7}];const radarMonths=["January","February","March","April","May","June","July"].map((label,index)=>({label,a:[70,62,48,38,20,32,60][index],b:[55,42,51,78,28,46,49][index]}));
function ReferenceRadar({variant}:{variant:number}){const data=variant===1?radarMonths:radarCountries;return <div className="h-[445px] px-3 pb-5 pt-8"><ResponsiveContainer width="100%" height="100%"><RechartsRadarChart data={data} outerRadius="68%"><PolarGrid stroke="var(--border)"/><PolarAngleAxis dataKey="label" tick={{fill:"var(--muted)",fontSize:12}}/><PolarRadiusAxis angle={90} domain={[0,variant===1?90:10]} tick={{fill:"var(--muted)",fontSize:10}}/><Radar animationDuration={1800} animationEasing="ease-in-out" name="Desktop" dataKey="a" stroke="#465fff" fill="#465fff" fillOpacity={.25} strokeWidth={2}/>{variant>0?<Radar animationDuration={1800} animationEasing="ease-in-out" name="Mobile" dataKey="b" stroke="#ee46bc" fill="#ee46bc" fillOpacity={.18} strokeWidth={2}/>:null}<Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/>{variant===1?<Legend iconType="circle" iconSize={9}/>:null}</RechartsRadarChart></ResponsiveContainer></div>}
function ReferenceRadial({variant}:{variant:number}){const multi=variant>0;const data=multi?[{name:"Desktop",value:78,fill:"#4650a8"},{name:"Tablet",value:66,fill:"#ffb478"},{name:"Mobile",value:52,fill:"#b7a8f5"}]:[{name:"series-1",value:62.25,fill:"#5b72f2"}];return <div className="relative h-[354px] px-4 pb-5 pt-7"><ResponsiveContainer width="100%" height="100%"><RadialBarChart data={data} innerRadius={multi?"34%":"68%"} outerRadius={multi?"95%":"94%"} startAngle={multi?180:90} endAngle={multi?0:-270} barSize={multi?22:16}><RadialBar animationDuration={1800} animationEasing="ease-in-out" dataKey="value" background={{fill:"#f2f4f7"}} cornerRadius={variant===0?0:8}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/></RadialBarChart></ResponsiveContainer>{variant===0?<div className="pointer-events-none absolute inset-0 grid place-items-center pt-10 text-center"><div><b className="block text-sm">series-1</b><strong className="mt-3 block text-xl">62.25%</strong></div></div>:null}</div>}
