"use client";
import { useState } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Bell, Check, ChevronDown, ChevronRight, CircleCheck, Code2, Image as ImageIcon, Info, Play, Plus, TriangleAlert, X } from "lucide-react";

function Head({title}:{title:string}){return <header className="catalog-head"><h1>{title}</h1><div>Home <ChevronRight/> <b>{title}</b></div></header>}
function Card({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <section className={"catalog-card "+className}><h2>{title}</h2><div>{children}</div></section>}

const sectionNames:Record<string,string[]>={alerts:["Success Alert","Warning Alert","Error Alert","Info Alert"],avatar:["Default Avatar","Avatar with online indicator","Avatar with Offline indicator","Avatar with busy indicator"],avatars:["Default Avatar","Avatar with online indicator","Avatar with Offline indicator","Avatar with busy indicator"],badge:["With Light Background","With Solid Background","Light Background with Left Icon","Solid Background with Left Icon","Light Background with Right Icon","Solid Background with Right Icon"],breadcrumb:["Default Breadcrumb","Breadcrumb With Icon","Breadcrumb With Icon","Breadcrumb With Icon"],buttons:["Primary Button","Primary Button with Left Icon","Primary Button with Right Icon","Secondary Button","Outline Button with Left Icon","Outline Button with Right Icon"],"buttons-group":["Primary Button Group","Primary Button Group with Left Icon","Primary Button Group with Right Icon","Secondary Button Group","Secondary Button Group with Left Icon","Secondary Button Group with Right Icon"],cards:["Card with Image","Horizontal Card with Image","Card with link","Card with Icon"],carousel:["Slides Only","With controls","With indicators","With controls and indicators"],dropdowns:["Default Dropdown","Dropdown With Divider","Dropdown With Icon","Dropdown With Icon and Divider"],images:["Responsive image","Image in 2 Grid","Image in 3 Grid"],links:["Colored Links","Colored CustomLinks with Underline","CustomLink Opacity","Link Opacity Hover"],list:["Unordered List","Ordered List","List With button","List With Icon","Horizontal List","List with checkbox","List with radio"],modals:["Default Modal","Vertically Centered Modal","Form In Modal","Full Screen Modal","Modal Based Alerts"],notification:["Announcement Bar","Toast Notification","Success Notification","Info Notification","Warning Notification","Error Notification"],notifications:["Announcement Bar","Toast Notification","Success Notification","Info Notification","Warning Notification","Error Notification"],pagination:["Pagination with Text","Pagination with Text and Icon","Pagination with  Icon"],popovers:["Default Popover","Popover With Button","Popover With Link"],"progress-bar":["Default Progress Bar","Progress Bar In Multiple Sizes","Progress Bar with Outside Label","Progress Bar with Inside Label"],ribbons:["Rounded Ribbon","Ribbon in Hover","Filled Ribbon","Ribbon in Hover"],spinners:["Spinner 1","Spinner 2","Spinner 3","Spinner 4"],tabs:["Default Tab","Tab With Underline","Tab with line and icon","Tab with badge","Vertical Tab"],tooltips:["Default Tooltip","White and Dark Tooltip","Tooltip Placement"],videos:["Video Ratio 16:9","Video Ratio 21:9","Video Ratio 4:3","Video Ratio 1:1"]};
export function Elements({slug,title}:{slug:string;title:string}){const [active,setActive]=useState(1),[open,setOpen]=useState(false);return <><Head title={title}/><div className={`catalog-gallery ui ui-${slug}`}>{sectionNames[slug].map((name,i)=><Card title={name} key={`${name}-${i}`}><Element slug={slug} i={i} active={active} setActive={setActive} open={open} setOpen={setOpen}/></Card>)}</div>{open&&slug==="modals"&&<div className="catalog-modal" role="dialog" aria-modal="true" aria-label="Example modal" onMouseDown={()=>setOpen(false)}><div onMouseDown={e=>e.stopPropagation()}><button onClick={()=>setOpen(false)} aria-label="Close modal"><X/></button><CircleCheck/><h2>{active===3?"Add new contact":"Confirm your action"}</h2><p>{active===3?"Complete the form to add a new contact.":"Are you sure you want to continue?"}</p><footer><button onClick={()=>setOpen(false)}>Cancel</button><button className="catalog-primary" onClick={()=>setOpen(false)}>Confirm</button></footer></div></div>}</>}
function HomeMark(){return <span className="home-mark" aria-hidden="true">⌂</span>}
function SampleCard({variant}:{variant:number}){const linked=variant===2;return <article className={`sample-card c${variant}`}><div className={`card-photo photo-${variant%3}`}><ImageIcon/></div><section><h3>{variant===1?"": "Card title"}</h3><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Animi architecto aspernatur cum et ipsum</p>{linked?<a href="#">⌁ Card link</a>:<button className="catalog-primary">Read more</button>}</section></article>}
function Element({slug,i,active,setActive,open,setOpen}:{slug:string;i:number;active:number;setActive:(n:number)=>void;open:boolean;setOpen:(x:boolean)=>void}){
 if(slug==="alerts")return <div className={`catalog-alert a${i}`}>{[<CircleCheck key="1"/>,<TriangleAlert key="2"/>,<AlertCircle key="3"/>,<Info key="4"/>][i]}<span><b>Important message</b><p>Please review the information shown here.</p></span><X/></div>;
 if(slug==="avatar"||slug==="avatars")return <div className={`avatar-row status-${i}`}>{[24,32,40,48,56,64].map(size=><i key={size} style={{width:size,height:size}}>{i>0?<b/>:null}</i>)}</div>;
 if(slug==="badge")return <div className="component-row">{["Primary","Success","Error","Warning","Info","Light","Dark"].map(x=><span className={`catalog-badge b${i} tone-${x.toLowerCase()}`} key={x}>{[2,3].includes(i)&&<Plus/>}{x}{i>3&&<Plus/>}</span>)}</div>;
 if(slug==="breadcrumb")return <div className={`breadcrumb-samples variant-${i}`}><div>{i===1?<HomeMark/>:null}<span>Home</span><ChevronRight/><b>UI Kits</b></div><div>{i===1?<HomeMark/>:null}<span>Home</span><ChevronRight/><span>UI Kits</span><ChevronRight/><b>Avatar</b></div></div>;
 if(slug==="buttons")return <div className="component-row"><button className={`catalog-primary ${i>2?"outline":""}`}>{i%3===1&&<Plus/>}Button Text{i%3===2&&<ArrowRight/>}</button><button className={`catalog-primary small ${i>2?"outline":""}`}>Button Text</button></div>;
 if(slug==="buttons-group")return <div className={`button-group group-${i}`}>{["Button Text","Button Text","Button Text"].map((x,j)=><button key={j}>{[1,4].includes(i)&&<Code2/>}{x}{[2,5].includes(i)&&<Code2/>}</button>)}</div>;
 if(slug==="cards")return i===0?<div className="cards-row">{[0,1,2].map(card=><SampleCard key={card} variant={card}/>)}</div>:<SampleCard variant={i+2}/>;
 if(slug==="carousel")return <div className={`catalog-carousel carousel-${i}`}><span>Beautiful workspace</span>{i>0&&<><button aria-label="Previous slide"><ArrowLeft/></button><button aria-label="Next slide"><ArrowRight/></button></>}{i>1?<nav aria-label="Slide selection"><i/><i className="active"/><i/></nav>:null}</div>;
 if(slug==="dropdowns")return <div className={`dropdown dropdown-${i}`}><button onClick={()=>setOpen(!open)} aria-expanded={open}>Options <ChevronDown/></button>{open&&<nav>{["Edit account","Settings","Support","Sign out"].map((x,j)=><button className={j===3&&i%2===1?"divided":""} key={x}>{i>1?<Check/>:null}{x}</button>)}</nav>}</div>;
 if(slug==="images")return <div className={`image-samples cols${i+1}`}>{Array.from({length:i+1},(_,j)=><i className={`sample-image image-${j}`} role="img" aria-label={`Workspace sample ${j+1}`} key={j}/>)}</div>;
 if(slug==="links")return <div className={`link-samples l${i}`}>{["Primary link","Secondary link","Success link","Error link","Warning link","Info link"].map(x=><a href={`#${x.toLowerCase().replaceAll(" ","-")}`} key={x}>{x}</a>)}</div>;
 if(slug==="list")return <ul className={`catalog-list l${i}`}>{["Dashboard overview","Account settings","Notifications","Billing details"].map((x,j)=><li key={x}>{i===3?<Check/>:null}{i===5?<input aria-label={x} type="checkbox" defaultChecked={!j}/>:null}{i===6?<input aria-label={x} name="catalog-radio" type="radio" defaultChecked={!j}/>:null}<span>{x}</span>{i===2?<button aria-label={`Open ${x}`}><ChevronRight/></button>:null}</li>)}</ul>;
 if(slug==="modals")return <button className="catalog-primary" onClick={()=>{setActive(i);setOpen(true)}}>Open Modal</button>;
 if(slug==="notification"||slug==="notifications")return <div className={`catalog-notification notice-${i}`}>{i===0?<Bell/>:i===1?<span className="notice-avatar">AR</span>:i===2?<CircleCheck/>:i===3?<Info/>:i===4?<TriangleAlert/>:<AlertCircle/>}<span><b>{i===0?"Announcement":i===1?"New message":i===2?"Success":i===3?"Information":i===4?"Warning":"Something went wrong"}</b><p>{i<2?"You have a new update waiting.":"Your latest action has been processed."}</p></span><button aria-label="Dismiss notification"><X/></button></div>;
 if(slug==="pagination")return <div className={`pagination pagination-${i}`}><button aria-label="Previous page"><ArrowLeft/>{i<2?<span>Previous</span>:null}</button>{[1,2,3,4,5].map(x=><button aria-label={`Page ${x}`} className={active===x?"active":""} onClick={()=>setActive(x)} key={x}>{x}</button>)}<button aria-label="Next page">{i<2?<span>Next</span>:null}<ArrowRight/></button></div>;
 if(slug==="popovers")return <div className="popover"><button className="catalog-primary" onClick={()=>setOpen(!open)}>Click me</button>{open&&<span><b>Popover title</b><p>Useful supporting information.</p></span>}</div>;
 if(slug==="progress-bar")return <div className="progresses">{[25,50,75,90].map(x=><div key={x}><span>{i>1&&`${x}%`}</span><i><b style={{width:`${x}%`}}>{i===3&&`${x}%`}</b></i></div>)}</div>;
 if(slug==="ribbons")return <div className={`ribbon r${i}`}><span>Featured</span><h3>New product</h3><p>Highlight important content with a clean ribbon label.</p></div>;
 if(slug==="spinners")return <div className={`spinner-row spinner-${i}`}>{[1,2,3,4].map(x=><i style={{animationDelay:`${x*80}ms`}} key={x}/>)}</div>;
 if(slug==="tabs")return <div className={`tab-example tab-${i}`}><div className={`tabs t${i}`}>{["Overview","Notification","Analytics","Customers"].map((x,j)=><button className={active===j?"active":""} onClick={()=>setActive(j)} key={x}>{i===2?<Info/>:null}{x}{i===3&&j===1?<b>8</b>:null}</button>)}</div><article className="tab-content"><h3>{["Overview","Notification","Analytics","Customers"][active]}</h3><p>Explore the selected dashboard information and recent activity.</p></article></div>;
 if(slug==="tooltips")return <div className={`tooltip-row tooltip-set-${i}`}>{["Top","Right","Bottom","Left"].map((position,j)=><div className={`tooltip t${j}`} key={position}><button className="catalog-primary">{position}</button><span>{i===1&&j%2?"Dark":"Helpful"} tooltip</span></div>)}</div>;
 return <div className={`video-sample v${i}`}><button aria-label="Play video"><Play/></button><span>Video preview</span></div>;
}
