"use client";
/* eslint-disable @next/next/no-img-element -- uploaded previews may be local data URLs */
import {useEffect,useRef,useState} from "react";
import {ChevronDown,Code2,Copy,Gem,Layers3,MessageSquarePlus,Mic,Paperclip,Pencil,Plus,RectangleVertical,Search,Send,Share2,Sparkles,Star,Trash2,X} from "lucide-react";

function TitleMenu({clear}:{clear:()=>void}){const[open,setOpen]=useState(false),[star,setStar]=useState(false),[title,setTitle]=useState("Generate responsive login"),[edit,setEdit]=useState(false);const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);return <div className="generator-title-menu" ref={ref}>{edit?<form onSubmit={e=>{e.preventDefault();setEdit(false)}}><input autoFocus aria-label="Conversation name" value={title} onChange={e=>setTitle(e.target.value)}/></form>:<button className="generator-title" onClick={()=>setOpen(!open)} aria-expanded={open}><span>{title}</span><ChevronDown/></button>}{open&&!edit?<div className="generator-title-dropdown" role="menu"><button onClick={()=>{setStar(!star);setOpen(false)}}><Star fill={star?"currentColor":"none"}/>{star?"Remove Starred":"Add Starred"}</button><button onClick={()=>setEdit(true)}><Pencil/>Rename</button><hr/><button onClick={()=>{clear();setOpen(false)}}><Trash2/>Delete</button></div>:null}</div>}
const history=["Write a follow-up email to a client","Generate responsive login form layout","Create a warning state modal","Suggest color palette for dark theme"];
function Aside({open,close}:{open:boolean;close:()=>void}){return <aside className={open?"open":""}><button className="history-close" onClick={close}><X/></button><button className="new-chat"><Plus/>New Chat</button><label><Search/><input placeholder="Search..."/></label><small>Today</small>{history.map(x=><span key={x}>{x}</span>)}<small>Yesterday</small>{history.map(x=><span key={"y"+x}>{x}</span>)}</aside>}

export function Generator({kind}:{kind:string}){const[text,setText]=useState(""),[answer,setAnswer]=useState(""),[historyOpen,setHistoryOpen]=useState(false),[image,setImage]=useState("https://nextjs-demo.tailadmin.com/images/ai/img-1.png");const model=kind==="image"?"Nano Banana 2.0":"Claude Sonnet 4.6";const prompt=kind==="text"?"Can you generate some random, creative, and engaging placeholder text for me?":"Minimalist building facade with vertical panels and greenery in a planter, set against a clear blue sky for a modern aesthetic.";const submit=()=>{if(text.trim()){setAnswer(text.trim());setText("")}};const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>typeof r.result==="string"&&setImage(r.result);r.readAsDataURL(f)}};return <div className={`generator-page generator-${kind}`}><main><nav><TitleMenu clear={()=>setAnswer("")}/><span/><button><Share2/>Share</button><button className="history-toggle" onClick={()=>setHistoryOpen(true)}><MessageSquarePlus/></button></nav><section className="generator-conversation"><div className="generator-thread"><article className="user-bubble"><p>{answer||prompt}</p><footer><button><Pencil/></button><button><Copy/></button></footer></article><article className="assistant-answer"><header><Sparkles/><span>{model}</span></header><p>{kind==="text"?"Lorem ipsum dolor sit amet, consectetur adipiscing elit.":"I have generated a minimalist building facade with vertical panels and greenery in a planter."}</p>{kind==="image"?<div className="generated-media generated-image"><img src={image} alt="Uploaded image preview"/></div>:null}</article></div><Composer kind={kind} text={text} setText={setText} submit={submit} upload={upload}/></section></main><Aside open={historyOpen} close={()=>setHistoryOpen(false)}/></div>}

function Composer({kind,text,setText,submit,upload}:{kind:string;text:string;setText:(x:string)=>void;submit:()=>void;upload?:(e:React.ChangeEvent<HTMLInputElement>)=>void}){return <div className="prompt"><textarea aria-label={`${kind} prompt`} value={text} onChange={e=>setText(e.target.value)} placeholder="Type your prompt here..."/><footer><span>{kind==="image"?<label className="image-upload"><input type="file" accept="image/*" onChange={upload}/><Paperclip/></label>:<button><Plus/></button>}{kind!=="text"?<><button><RectangleVertical/>3:4</button><button><Layers3/>1</button><button><Gem/>2K</button></>:null}<button>{kind==="video"?"Google Veo 3.1":kind==="image"?"Nano Banana Pro":"Claude Sonnet 4.6"}<ChevronDown/></button></span><button onClick={submit}>{kind==="image"?<Mic/>:<Send/>}</button></footer></div>}

export function AdvancedGenerator({kind}:{kind:"video"|"code"}){
  const [text,setText]=useState("");
  const [answer,setAnswer]=useState("");
  const [historyOpen,setHistoryOpen]=useState(false);
  const [videoSource,setVideoSource]=useState("");
  const isVideo=kind==="video";
  const model=isVideo?"Google Veo 3.1":"Claude Sonnet 4.6";
  useEffect(()=>()=>{if(videoSource)URL.revokeObjectURL(videoSource)},[videoSource]);
  const submit=()=>{if(text.trim()){setAnswer(text.trim());setText("")}};
  const uploadVideo=(event:React.ChangeEvent<HTMLInputElement>)=>{
    const file=event.target.files?.[0];
    if(!file)return;
    setVideoSource(current=>{if(current)URL.revokeObjectURL(current);return URL.createObjectURL(file)});
    event.target.value="";
  };
  return <div className={`generator-page generator-${kind}`}><main><nav><TitleMenu clear={()=>setAnswer("")}/><span/><button><Share2/>Share</button><button className="history-toggle" onClick={()=>setHistoryOpen(true)} aria-label="Open chat history"><MessageSquarePlus/></button></nav><section className="generator-conversation"><div className="generator-thread"><article className="user-bubble"><p>{answer||(isVideo?"Minimalist building facade with vertical panels and greenery in a planter, set against a clear blue sky for a modern aesthetic.":"Create a responsive login form with Google and GitHub authentication.")}</p></article><article className="assistant-answer"><header><Sparkles/><span>{model}</span></header>{isVideo?<><p>I have generated a minimalist building facade with vertical panels and greenery in a planter, set against a clear blue sky for a modern aesthetic.</p><div className="generated-media generated-video">{videoSource?<video src={videoSource} controls playsInline/>:<iframe src="https://www.youtube.com/embed/_iHmNaQBtKk?rel=0" title="Generated mountain landscape video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>}</div></>:<><p>Here is the code for a responsive login form with Google and GitHub authentication.</p><div className="generated-code"><header><span><Code2/>HTML</span><span><button aria-label="Copy code"><Copy/></button><button aria-label="Edit code"><Pencil/></button></span></header><pre>{`<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>Welcome Back</title>\n</head>\n<body>\n  <main class="login-container">\n    <h1>Welcome Back</h1>\n    <p>Please sign in to your account</p>\n    <form id="loginForm">\n      <input type="email" placeholder="Email" />\n      <input type="password" placeholder="Password" />\n      <button type="submit">Sign In</button>\n    </form>\n  </main>\n</body>\n</html>`}</pre></div></>}</article></div>{isVideo?<VideoComposer text={text} setText={setText} submit={submit} upload={uploadVideo}/>:<Composer kind={kind} text={text} setText={setText} submit={submit}/>}</section></main><Aside open={historyOpen} close={()=>setHistoryOpen(false)}/></div>
}

function VideoComposer({text,setText,submit,upload}:{text:string;setText:(value:string)=>void;submit:()=>void;upload:(event:React.ChangeEvent<HTMLInputElement>)=>void}){return <div className="prompt"><textarea aria-label="Video prompt" value={text} onChange={event=>setText(event.target.value)} placeholder="Type your prompt here..."/><footer><span><label className="media-upload" aria-label="Upload video"><input type="file" accept="video/*" onChange={upload}/><Paperclip/></label><button><RectangleVertical/>3:4</button><button><Layers3/>1</button><button><Gem/>2K</button><button>30s</button><button>Audio</button><button>Google Veo 3.1<ChevronDown/></button></span><button onClick={submit} aria-label="Send prompt"><Mic/></button></footer></div>}
