"use client";
import { useState } from "react";
import { Bell, ChevronDown, Menu, Search, User } from "lucide-react";

const layoutMenus={
  1:["Dashboard","Ecommerce","Analytics","Marketing","CRM","Stocks","SaaS","Logistics","Sales","AI","AI Assistant","E-commerce","Calendar","User Profile"],
  2:["General","Dashboard","Inventory Management","Product Development","Finance","Human Resources","Supply Chain","Public Profiles","Settings","Notifications","User Analytics","Projects","Design Engineering","Sales & Marketing","SaaS","Customer Support","API Reference"],
  3:["Get Started","Quick Start","Installation Guide","Tutorials","API Reference","Best Practices","FAQ","Components","Accordion","Alert","Alert Dialog","Aspect Ratio","Avatar","Badge","Breadcrumbs","Button","Button Group","Card"],
  4:["Get Started","Quick Start","Installation Guide","Tutorials","Configuration","Best Practices","FAQ","Developer Features","SDK Documentation","API Reference","Integration Guides","Tutorials","Release Notes"],
  5:["Get Started","Introduction","Quick Start","Framework guides","Usage","Javascript","Accessibility","Upgrade Guide","License","Components","Accordion","Alert","Avatar","Badge","Button","Card","Carousel","Chat Bubble","Collapse","Indicator","List Group"],
  6:["Dashboard","Calendar","Profiles","Settings","Design Engineering","Email","Inbox","Customer Support","Analytics","Integrations","Components"]
} as const;
export function Layouts({n}:{title:string;n:number}){
 const [drawer,setDrawer]=useState(false);const [expanded,setExpanded]=useState(n!==6);const menus=layoutMenus[n as keyof typeof layoutMenus];const docs=n>=3&&n<=5;
 return <div className={`reference-layout layout-${n}`}><aside className={`${drawer?"open":""} ${expanded?"expanded":"collapsed"}`}><header><span className="mini-logo"><i/><i/><i/></span>{n!==6&&<b>{docs?"TailAdmin Docs":"TailAdmin"}{docs&&<small>v2.0.8-alpha</small>}</b>}<button onClick={()=>setExpanded(v=>!v)} aria-label="Toggle layout navigation"><ChevronDown/></button></header>{docs&&n!==5?<label><Search/><input placeholder="Search the docs"/></label>:null}<nav>{menus.map((item,i)=>{const heading=(n===2&&[0,11,16].includes(i))||(n===3&&[0,7].includes(i))||(n===5&&[0,9].includes(i));const accordion=n===4&&[0,7,8,9,10,11,12].includes(i);return heading?<h3 key={`${item}-${i}`}>{item}</h3>:<button key={`${item}-${i}`} className={(n===1&&i===0)||(n===3&&i===8)||(n===4&&i===2)||(n===5&&i===3)||(n===6&&i===0)?"active":""} title={item}>{n===6?<LayoutIcon index={i}/>:null}<span>{item}</span>{accordion?<ChevronDown/>:null}</button>})}</nav></aside><div className="layout-stage"><header><button onClick={()=>setDrawer(true)} aria-label="Open layout navigation"><Menu/></button><label><Search/><input placeholder="Search or type command..."/><kbd>⌘ K</kbd></label><span/><button className="theme-dot">◔</button>{docs?<button className="get-started">Get Started</button>:<><button><Bell/></button><button className="layout-user"><User/><b>Musharof</b><ChevronDown/></button></>}</header><main><div className="reference-kpis">{[1,2,3,4].map(x=><i key={x}/>)}</div><div className="reference-grid"><article/><article/></div>{n===5?<div className="reference-kpis bottom">{[1,2,3,4].map(x=><i key={x}/>)}</div>:null}</main></div>{drawer?<button className="layout-overlay" onClick={()=>setDrawer(false)} aria-label="Close layout navigation"/>:null}</div>
}
function LayoutIcon({index}:{index:number}){return <span className="layout-symbol">{["▦","□","◉","⬡","◇","✉","▣","♧","◔","⌘","◆"][index]}</span>}
