"use client";

import { Modal } from "@/components/modal";
import { AppWindow, ArrowRight, ChevronRight, Download, Eye, FileText, Folder, MoreVertical, Music2, Play, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useRef, useState } from "react";

const media = [
  { name: "Image", used: "17% Used", files: "245 files", size: "26.40 GB", icon: Folder, color: "text-emerald-500", bg: "bg-emerald-50" },
  { name: "Videos", used: "22% Used", files: "245 files", size: "26.40 GB", icon: Play, color: "text-pink-500", bg: "bg-pink-50" },
  { name: "Audios", used: "23% Used", files: "830 files", size: "18.90 GB", icon: Music2, color: "text-sky-500", bg: "bg-sky-50" },
  { name: "Apps", used: "65% Used", files: "1200 files", size: "85.30 GB", icon: AppWindow, color: "text-orange-500", bg: "bg-orange-50" },
  { name: "Documents", used: "10% Used", files: "78 files", size: "5.40 GB", icon: FileText, color: "text-amber-500", bg: "bg-amber-50" },
  { name: "Downloads", used: "16% Used", files: "245 files", size: "26.40 GB", icon: Download, color: "text-violet-500", bg: "bg-violet-50" },
];
const folderSeed = [{ name: "Images", files: "345 Files", size: "26.40 GB" },{ name: "Documents", files: "130 Files", size: "26.40 GB" },{ name: "Apps", files: "130 Files Files", size: "26.40 GB" },{ name: "Downloads", files: "345 Files", size: "26.40 GB" }];
const fileSeed = [{ name: "Video_947954.mp4", category: "Video", size: "89 MB", date: "12 Jan, 2027" },{ name: "Travel.jpg", category: "Image", size: "5.4 MB", date: "10 Feb, 2027" },{ name: "Document.pdf", category: "Document", size: "1.2 MB", date: "8 Mar, 2027" },{ name: "Video_947954_028.mp4", category: "Video", size: "489 MB", date: "29 Apr, 2027" },{ name: "Mountain.png", category: "Image", size: "5.4 MB", date: "10 Feb, 2027" },{ name: "CV.pdf", category: "Document", size: "12 MB", date: "17 Jun, 2027" },{ name: "Video_09783_882943.mp4", category: "Video", size: "309 MB", date: "27 Jul, 2027" }];

export default function FileManagerPage() {
  const [query, setQuery] = useState(""), [files, setFiles] = useState(fileSeed), [folders] = useState(folderSeed), [upload, setUpload] = useState(false), [uploadName, setUploadName] = useState("");
  const [folderMenu, setFolderMenu] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const filteredMedia = media.filter(item => item.name.toLowerCase().includes(query.toLowerCase()));
  const filteredFiles = useMemo(() => files.filter(file => `${file.name} ${file.category}`.toLowerCase().includes(query.toLowerCase())), [files, query]);
  const addFile = () => { if (!uploadName) return; setFiles(items => [{ name: uploadName, category: uploadName.match(/\.(png|jpg|jpeg)$/i) ? "Image" : uploadName.match(/\.mp4$/i) ? "Video" : "Document", size: "1.0 MB", date: "24 Aug, 2026" }, ...items]); setUpload(false); setUploadName(""); };
  return <div className="space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">File Manager</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">File Manager</span></nav></header>
    <section className="panel overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-[var(--border)] px-6 py-[15px]"><h2 className="text-xl font-semibold">All Media</h2><div className="flex flex-1 justify-end gap-3"><label className="relative w-full max-w-[295px]"><Search className="muted absolute left-4 top-1/2 -translate-y-1/2" size={18}/><input className="control !h-11 !pl-12" placeholder="Search..." value={query} onChange={event => setQuery(event.target.value)}/></label><button className="btn btn-primary h-11 whitespace-nowrap !px-5" onClick={() => setUpload(true)}><Plus size={18}/>Upload File</button></div></header><div className="grid gap-5 p-6 sm:grid-cols-2 xl:grid-cols-3">{filteredMedia.map(item => { const Icon = item.icon; return <button className="flex min-h-[84px] items-center rounded-xl border border-[var(--border)] p-4 text-left transition hover:border-[#c7d0ff]" key={item.name}><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${item.bg} ${item.color}`}><Icon size={23}/></span><div className="ml-4"><p className="font-medium">{item.name}</p><p className="muted mt-1 text-xs">{item.used}</p></div><div className="muted ml-auto text-right text-sm"><p>{item.files}</p><p className="mt-1">{item.size}</p></div></button>; })}</div></section>
    <div className="grid items-start gap-6 xl:grid-cols-[7fr_5fr] xl:[&>section]:col-span-1">
      <section className="panel overflow-hidden xl:col-span-8"><header className="flex items-center justify-between border-b border-[var(--border)] px-6 py-5"><h2 className="text-xl font-semibold">All Folders</h2><button className="muted flex items-center gap-2 text-sm hover:text-[var(--text)]">View All <ArrowRight size={17}/></button></header><div className="grid gap-5 p-6 sm:grid-cols-2">{folders.map(folder => <article className="relative rounded-xl bg-[var(--soft)] p-5" key={folder.name}><div className="flex items-start justify-between"><Folder className="fill-amber-300 text-amber-300" size={38}/><button className="rounded-lg p-1 hover:bg-[var(--panel)]" onClick={() => setFolderMenu(folderMenu === folder.name ? null : folder.name)} aria-label={`${folder.name} folder options`}><MoreVertical className="muted" size={19}/></button></div><h3 className="mt-5 font-medium">{folder.name}</h3><div className="muted mt-2 flex justify-between text-sm"><span>{folder.files}</span><span>{folder.size}</span></div>{folderMenu === folder.name ? <div className="panel absolute right-3 top-11 z-10 w-28 p-1 shadow-lg"><button className="w-full rounded-md px-3 py-2 text-left text-sm hover:bg-[var(--soft)]">Open</button><button className="w-full rounded-md px-3 py-2 text-left text-sm hover:bg-[var(--soft)]">Rename</button></div> : null}</article>)}</div></section>
      <section className="panel p-6 xl:col-span-4"><h2 className="text-xl font-semibold">Storage Details</h2><p className="muted mt-1 text-sm">585 GB Free space left</p><div className="relative mx-auto mt-7 h-48 w-48 rounded-full" style={{ background: "conic-gradient(#8b75f7 0 50%, #35cd86 50% 69%, #ffb020 69% 81%, #eef1f6 81%)" }}><div className="absolute inset-9 grid place-items-center rounded-full bg-[var(--panel)] text-center"><div><p className="text-2xl font-semibold">160</p><p className="muted text-xs">Total 160 GB</p></div></div></div><div className="mt-7 flex items-center justify-between gap-1 text-xs font-medium">{[["Downloads","#8b75f7"],["Apps","#35cd86"],["Documents","#ffb020"],["Media","#d0d5dd"]].map(([label,color]) => <span className="flex items-center gap-1 whitespace-nowrap" key={label}><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{background:color}}/>{label}</span>)}</div></section>
    </div>
    <section className="panel overflow-hidden"><header className="flex items-center justify-between px-6 py-5"><h2 className="text-xl font-semibold">Recent Files</h2><button className="muted flex items-center gap-2 text-sm">View All <ArrowRight size={17}/></button></header><div className="table-wrap"><table className="data-table min-w-[680px]"><thead><tr><th>File Name</th><th>Category</th><th>Size</th><th>Date Modified</th><th>Action</th></tr></thead><tbody>{filteredFiles.map(file => <tr key={file.name}><td><span className="block min-w-48 font-normal">{file.name}</span></td><td>{file.category}</td><td>{file.size}</td><td>{file.date}</td><td><div className="flex items-center gap-1"><button className="muted rounded-lg p-2 hover:bg-[var(--soft)] hover:text-[var(--text)]" onClick={() => setFiles(items => items.filter(item => item.name !== file.name))} aria-label={`Delete ${file.name}`} title="Delete file"><Trash2 size={17}/></button><button className="muted rounded-lg p-2 hover:bg-[var(--soft)] hover:text-[var(--text)]" aria-label={`View ${file.name}`} title="View file"><Eye size={17}/></button></div></td></tr>)}</tbody></table></div></section>
    <Modal open={upload} title="Upload File" onClose={() => setUpload(false)}><div className="space-y-5"><button className="grid min-h-44 w-full place-items-center rounded-xl border border-dashed border-[var(--border)] bg-[var(--soft)] p-6 text-center" onClick={() => inputRef.current?.click()}><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[var(--panel)] text-[#465fff]"><Plus/></span><p className="mt-3 font-medium">Choose a file to upload</p><p className="muted mt-1 text-sm">{uploadName || "PNG, JPG, PDF or MP4"}</p></div></button><input ref={inputRef} className="sr-only" type="file" onChange={event => setUploadName(event.target.files?.[0]?.name ?? "")}/><div className="flex justify-end gap-3"><button className="btn" onClick={() => setUpload(false)}>Cancel</button><button className="btn btn-primary" disabled={!uploadName} onClick={addFile}>Upload File</button></div></div></Modal>
  </div>;
}
