"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { EllipsisVertical, SlidersHorizontal } from "lucide-react";

const visitors = [168,385,201,298,187,195,291,110,215,390,280,112,123,212,270,190,310,115,90,380,112,223,292,170,290,110,115,290,380,312].map((value,index)=>({day:index+1,visitors:value}));
const channels = [{name:"Google",mark:"G",color:"#4285f4",value:"4.7K"},{name:"Facebook",mark:"f",color:"#1877f2",value:"3.4K"},{name:"Threads",mark:"@",color:"#111827",value:"2.9K"},{name:"Google",mark:"G",color:"#ea4335",value:"1.5K"}];
const pages = [{name:"tailadmin.com",value:"4.7K"},{name:"preview.tailadmin.com",value:"3.4K"},{name:"docs.tailadmin.com",value:"2.9K"},{name:"tailadmin.com/components",value:"1.5K"}];
const acquisition = [
  {month:"Jan",direct:44,referral:24,organic:12,social:8},
  {month:"Feb",direct:55,referral:23,organic:13,social:9},
  {month:"Mar",direct:40,referral:35,organic:15,social:10},
  {month:"Apr",direct:62,referral:22,organic:11,social:7},
  {month:"May",direct:48,referral:28,organic:12,social:8},
  {month:"Jun",direct:70,referral:18,organic:9,social:5},
  {month:"Jul",direct:53,referral:31,organic:12,social:7},
  {month:"Aug",direct:65,referral:23,organic:10,social:6},
];
const acquisitionLegend = [{key:"direct",label:"Direct",color:"#3641f5"},{key:"referral",label:"Referral",color:"#5b75f7"},{key:"organic",label:"Organic Search",color:"#91a7f8"},{key:"social",label:"Social",color:"#c7d2fe"}] as const;
const devices = [{name:"Desktop",value:35,color:"#3641f5"},{name:"Mobile",value:45,color:"#6f8af8"},{name:"Tablet",value:20,color:"#d7e2ff"}];
const orders = [{name:"TailGrids",category:"UI Kits",country:"USA",cr:"Dashboard",value:"$12,499"},{name:"GrayGrids",category:"Templates",country:"France",cr:"Dashboard",value:"$5498"},{name:"Uideck",category:"Templates",country:"Singapore",cr:"Dashboard",value:"$4621"},{name:"FormBold",category:"SaaS",country:"United Kingdom",cr:"Dashboard",value:"$13843"},{name:"NextAdmin",category:"Templates",country:"Yemen",cr:"Dashboard",value:"$7523"},{name:"Form Builder",category:"Templates",country:"Finland",cr:"Dashboard",value:"$1,377"},{name:"AyroUI",category:"Templates",country:"Belgium",cr:"Dashboard",value:"$599,00"}];
const activeUsers=[22,29,34,42,57,52,46,37,32,24,31,38,47,52,68,73,61,45].map((value,index)=>({index,value}));

export default function AnalyticsPage(){
  const [period,setPeriod]=useState("Monthly");
  const [filterOpen,setFilterOpen]=useState(false);
  const [country,setCountry]=useState("All");
  const factor=period==="Quarterly"?1.16:period==="Annually"?1.34:1;
  const chart=useMemo(()=>visitors.map(item=>({...item,visitors:Math.round(item.visitors*factor)})),[factor]);
  const visibleOrders=country==="All"?orders:orders.filter(item=>item.country===country);
  return <div className="space-y-6">
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4" aria-label="Analytics summary">
      <Metric label="Unique Visitors" value="24.7K" change="+20%"/>
      <Metric label="Total Pageviews" value="55.9K" change="+4%"/>
      <Metric label="Bounce Rate" value="54%" change="-1.59%" down/>
      <Metric label="Visit Duration" value="2m 56s" change="+7%"/>
    </section>

    <article className="analytics-chart-card panel px-6 pt-6">
      <div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-lg font-semibold leading-7">Analytics</h2><p className="muted mt-1 text-sm">Visitor analytics of last 30 days</p></div><div className="soft flex rounded-lg p-1">{["Monthly","Quarterly","Annually"].map(item=><button key={item} onClick={()=>setPeriod(item)} aria-pressed={period===item} className={`rounded-md px-4 py-2 text-sm transition ${period===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted hover:text-[var(--text)]"}`}>{item}</button>)}</div></div>
      <div className="analytics-chart-wrap h-[365px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:15,left:-12,right:0,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="day" interval={0} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,400]} ticks={[0,100,200,300,400]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip cursor={{fill:"var(--soft)"}} contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="visitors" fill="#465fff" radius={[5,5,0,0]} maxBarSize={9} animationDuration={1200} animationEasing="ease-in-out"/></BarChart></ResponsiveContainer></div>
    </article>

    <section className="grid items-start gap-6 lg:grid-cols-3"><RankCard title="Top Channels" label="Visitors" rows={channels}/><RankCard title="Top Pages" label="Pageview" rows={pages}/>
      <article className="analytics-active-users panel min-w-0 p-6"><CardTitle title="Active Users"/><div className="active-users-total mt-8 flex min-w-0 items-center gap-3"><span className="active-users-live-dot h-2.5 w-2.5 shrink-0 rounded-full bg-red-500" aria-hidden="true"/><p className="text-4xl font-semibold leading-none tabular-nums">364</p><span className="muted min-w-0 text-sm">Live visitors</span></div><div className="active-users-chart mt-8 h-[194px] min-w-0 overflow-hidden rounded-2xl bg-[var(--soft)]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activeUsers} margin={{top:30,right:0,bottom:25,left:0}}><defs><linearGradient id="active-users-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#465fff" stopOpacity={.28}/><stop offset="100%" stopColor="#465fff" stopOpacity={0}/></linearGradient></defs><Tooltip cursor={false} labelFormatter={()=>""} formatter={(value)=>[value,"Visitors"]} contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:8,boxShadow:"0 4px 12px rgb(16 24 40 / 10%)",fontSize:12}} itemStyle={{color:"var(--text)"}}/><Area type="monotone" dataKey="value" stroke="#465fff" strokeWidth={2.5} fill="url(#active-users-fill)" dot={false} activeDot={{r:4,fill:"#465fff",stroke:"#fff",strokeWidth:2}} animationDuration={1200} animationEasing="ease-in-out"/></AreaChart></ResponsiveContainer></div><div className="active-users-summary mt-7 grid grid-cols-3 divide-x divide-[var(--border)] text-center"><Mini value="224" label="Avg, Daily"/><Mini value="1.4K" label="Avg, Weekly"/><Mini value="22.1K" label="Avg, Monthly"/></div></article>
    </section>

    <section className="grid gap-6 xl:grid-cols-12">
      <article className="panel p-6 xl:col-span-7"><CardTitle title="Acquisition Channels"/><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2">{acquisitionLegend.map(item=><span className="muted flex items-center gap-2 text-xs" key={item.key}><i className="h-2.5 w-2.5 rounded-full" style={{background:item.color}}/>{item.label}</span>)}</div><div className="mt-4 h-[285px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={acquisition} margin={{left:-24,right:5,top:8,bottom:5}} barCategoryGap="36%"><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,120]} ticks={[0,20,40,60,80,100,120]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip cursor={{fill:"transparent"}} contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="direct" name="Direct" stackId="channel" fill="#3641f5" radius={[0,0,7,7]} maxBarSize={30}/><Bar dataKey="referral" name="Referral" stackId="channel" fill="#5b75f7" maxBarSize={30}/><Bar dataKey="organic" name="Organic Search" stackId="channel" fill="#91a7f8" maxBarSize={30}/><Bar dataKey="social" name="Social" stackId="channel" fill="#c7d2fe" radius={[7,7,0,0]} maxBarSize={30}/></BarChart></ResponsiveContainer></div></article>
      <article className="panel p-6 xl:col-span-5"><CardTitle title="Sessions By Device"/><div className="mt-5 h-[285px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={devices} dataKey="value" innerRadius={70} outerRadius={108} startAngle={90} endAngle={-270} paddingAngle={0} stroke="none">{devices.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/></PieChart></ResponsiveContainer></div><div className="mt-1 flex flex-wrap justify-center gap-x-6 gap-y-2">{devices.map(item=><span className="muted flex items-center gap-2 text-xs" key={item.name}><i className="h-2.5 w-2.5 rounded-full" style={{background:item.color}}/>{item.name}</span>)}</div></article>
    </section>

    <section className="grid items-start gap-6 xl:grid-cols-[minmax(340px,.8fr)_minmax(0,1.6fr)]">
      <article className="analytics-demographic panel p-6"><CardTitle title="Customers Demographic" subtitle="Number of customer based on country"/><WorldMap/><div className="mt-6 space-y-5"><Country name="USA" customers="2,379 Customers" percent={79}/><Country name="France" customers="589 Customers" percent={23}/></div></article>
      <article className="analytics-recent-orders panel overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 px-6 py-4"><h2 className="text-[18px] font-semibold">Recent Orders</h2><div className="flex gap-3"><div className="relative"><button className="btn !px-4 !py-3 !font-normal" onClick={()=>setFilterOpen(v=>!v)} aria-expanded={filterOpen}><SlidersHorizontal size={18}/>Filter</button>{filterOpen?<div className="panel absolute right-0 z-20 mt-2 w-44 p-2 shadow-xl">{["All",...Array.from(new Set(orders.map(item=>item.country)))].map(item=><button key={item} className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-[var(--soft)]" onClick={()=>{setCountry(item);setFilterOpen(false)}}>{item}</button>)}</div>:null}</div><button className="btn !px-4 !py-3 !font-normal">See all</button></div></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Products</th><th>Category</th><th>Country</th><th>CR</th><th>Value</th></tr></thead><tbody>{visibleOrders.map(item=><tr key={item.name}><td className="font-normal">{item.name}</td><td className="font-normal">{item.category}</td><td className="font-normal"><span className="flex items-center gap-2"><Flag country={item.country}/><span>{item.country}</span></span></td><td className="font-normal">{item.cr}</td><td className="font-normal text-emerald-600 tabular-nums">{item.value}</td></tr>)}</tbody></table></div></article>
    </section>
  </div>
}

function Metric({label,value,change,down=false}:{label:string;value:string;change:string;down?:boolean}){return <article className="analytics-metric panel"><p className="metric-label muted">{label}</p><div className="metric-row"><p className="metric-value tabular-nums">{value}</p><div className="metric-comparison"><span className={`metric-change ${down?"down":"up"}`}>{change}</span><p className="muted">Vs last month</p></div></div></article>}
function CardTitle({title,subtitle}:{title:string;subtitle?:string}){return <div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{title}</h2>{subtitle?<p className="muted mt-1 text-sm">{subtitle}</p>:null}</div><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical size={18}/></button></div>}
function RankCard({title,label,rows}:{title:string;label:string;rows:{name:string;value:string}[]}){return <article className="analytics-rank-card panel flex flex-col overflow-hidden p-6"><CardTitle title={title}/><div className="mx-2 mt-5 grid grid-cols-[1fr_auto] border-b border-[var(--border)] pb-3 text-xs text-[var(--muted)]"><span>Source</span><span>{label}</span></div><div className="mx-2 divide-y divide-[var(--border)]">{rows.map((row,index)=><div className="flex items-center gap-3 py-3" key={`${row.name}-${index}`}><span className="min-w-0 flex-1 truncate text-sm font-normal">{row.name}</span><span className="text-sm font-normal tabular-nums">{row.value}</span></div>)}</div><button className="btn mt-3 w-full !py-3 text-sm !font-medium">Channels Report <span className="text-xl leading-none">→</span></button></article>}
function Mini({value,label}:{value:string;label:string}){return <div><b className="text-lg tabular-nums">{value}</b><p className="muted mt-1 text-xs">{label}</p></div>}
function WorldMap(){const [zoom,setZoom]=useState(1);return <div className="analytics-vector-map mt-6" role="group" aria-label="Interactive customer locations map"><div className="analytics-vector-map-canvas" style={{transform:`scale(${zoom})`}}><MapMarker name="United States" x="18%" y="43%"/><MapMarker name="France" x="44%" y="35%"/><MapMarker name="India" x="67%" y="50%"/><MapMarker name="Australia" x="79%" y="70%"/></div><nav aria-label="Map zoom controls"><button type="button" onClick={()=>setZoom(value=>Math.min(1.3,Number((value+.1).toFixed(1))))} aria-label="Zoom in">+</button><button type="button" onClick={()=>setZoom(value=>Math.max(.8,Number((value-.1).toFixed(1))))} aria-label="Zoom out">−</button></nav></div>}
function MapMarker({name,x,y}:{name:string;x:string;y:string}){return <button type="button" className="analytics-map-marker" style={{left:x,top:y}} aria-label={name}><span>{name}</span></button>}
function Country({name,customers,percent}:{name:string;customers:string;percent:number}){return <div className="flex items-center gap-3"><DemographicFlag country={name}/><div><p className="text-sm font-semibold leading-5">{name}</p><p className="muted text-xs leading-[18px]">{customers}</p></div><p className="ml-auto text-sm font-medium tabular-nums">{percent}%</p></div>}
function DemographicFlag({country}:{country:string}){if(country==="USA")return <svg viewBox="0 0 32 32" className="h-8 w-8 shrink-0 rounded-full" role="img" aria-label="USA flag"><defs><clipPath id="analytics-us-flag"><circle cx="16" cy="16" r="16"/></clipPath></defs><g clipPath="url(#analytics-us-flag)"><path fill="#fff" d="M0 0h32v32H0z"/>{[2,6,10,14,18,22,26,30].map(y=><path key={y} fill="#e11d48" d={`M0 ${y}h32v2H0z`}/>) }<path fill="#1d4ed8" d="M0 0h15v15H0z"/><g fill="#fff">{[3,7,11].flatMap(y=>[3,7,11].map(x=><circle key={`${x}-${y}`} cx={x} cy={y} r=".8"/>))}</g></g></svg>;return <svg viewBox="0 0 32 32" className="h-8 w-8 shrink-0 rounded-full" role="img" aria-label="France flag"><defs><clipPath id="analytics-fr-flag"><circle cx="16" cy="16" r="16"/></clipPath></defs><g clipPath="url(#analytics-fr-flag)"><path fill="#1d4ed8" d="M0 0h11v32H0z"/><path fill="#fff" d="M11 0h10v32H11z"/><path fill="#ef4444" d="M21 0h11v32H21z"/></g></svg>}
function Flag({country}:{country:string}){const clipId=`order-flag-${country.toLowerCase().replaceAll(" ","-")}`;return <svg viewBox="0 0 24 24" className="h-5 w-5 shrink-0 rounded-full border border-[var(--border)]" role="img" aria-label={`${country} flag`}><defs><clipPath id={clipId}><circle cx="12" cy="12" r="12"/></clipPath></defs><g clipPath={`url(#${clipId})`}>{country==="USA"?<><rect width="24" height="24" fill="#fff"/>{[0,4,8,12,16,20].map(y=><rect key={y} y={y} width="24" height="2" fill="#e11d48"/>)}<rect width="11" height="10" fill="#1d4ed8"/><circle cx="3" cy="3" r=".8" fill="#fff"/><circle cx="7" cy="3" r=".8" fill="#fff"/><circle cx="3" cy="7" r=".8" fill="#fff"/><circle cx="7" cy="7" r=".8" fill="#fff"/></>:country==="France"?<><rect width="8" height="24" fill="#1d4ed8"/><rect x="8" width="8" height="24" fill="#fff"/><rect x="16" width="8" height="24" fill="#ef4444"/></>:country==="Singapore"?<><rect width="24" height="12" fill="#ef3340"/><rect y="12" width="24" height="12" fill="#fff"/><circle cx="7" cy="6" r="4" fill="#fff"/><circle cx="8.5" cy="6" r="3.2" fill="#ef3340"/></>:country==="United Kingdom"?<><rect width="24" height="24" fill="#1e3a8a"/><path d="M0 0l24 24M24 0L0 24" stroke="#fff" strokeWidth="6"/><path d="M0 0l24 24M24 0L0 24" stroke="#dc2626" strokeWidth="2.5"/><path d="M12 0v24M0 12h24" stroke="#fff" strokeWidth="7"/><path d="M12 0v24M0 12h24" stroke="#dc2626" strokeWidth="3.5"/></>:country==="Yemen"?<><rect width="24" height="8" fill="#dc2626"/><rect y="8" width="24" height="8" fill="#fff"/><rect y="16" width="24" height="8" fill="#111827"/></>:country==="Finland"?<><rect width="24" height="24" fill="#fff"/><rect x="7" width="4" height="24" fill="#2563b8"/><rect y="9" width="24" height="4" fill="#2563b8"/></>:<><rect width="8" height="24" fill="#111827"/><rect x="8" width="8" height="24" fill="#facc15"/><rect x="16" width="8" height="24" fill="#ef4444"/></>}</g></svg>}
