"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Check, ChevronLeft, ChevronRight, EllipsisVertical, Filter, MessageCircle, Navigation, PackageCheck, Phone, Truck, TrendingUp } from "lucide-react";

const deliveries=[{m:"Jan",shipment:48,delivery:38},{m:"Feb",shipment:55,delivery:44},{m:"Mar",shipment:51,delivery:48},{m:"Apr",shipment:64,delivery:53},{m:"May",shipment:61,delivery:58},{m:"Jun",shipment:72,delivery:64},{m:"Jul",shipment:68,delivery:62},{m:"Aug",shipment:79,delivery:70},{m:"Sep",shipment:75,delivery:68},{m:"Oct",shipment:84,delivery:76},{m:"Nov",shipment:88,delivery:80},{m:"Dec",shipment:94,delivery:86}];
const shippedTrend=[32,38,35,48,43,56,51,67,61,72,69,82].map((value,index)=>({index,value}));
const orders=[{id:"#324112",category:"Furniture",company:"HomeLine",arrival:"10 Apr 2028 2:15 pm",route:"Berlin–Milan",price:"$1,250.00",status:"Delivered"},{id:"#325678",category:"Clothing",company:"StylePro",arrival:"21 May 2028 9:00 am",route:"Paris–Rome",price:"$340.75",status:"Delivered"},{id:"#326789",category:"Books",company:"EduSource",arrival:"02 Jun 2028 11:45 am",route:"New York–Chicago",price:"$128.40",status:"In Transit"},{id:"#327003",category:"Automotive",company:"AutoParts Co.",arrival:"18 Mar 2028 4:00 pm",route:"Tokyo–Osaka",price:"$2,150.89",status:"Delivered"},{id:"#328556",category:"Electronics",company:"TechNova",arrival:"25 Jul 2028 10:30 am",route:"San Francisco–Seattle",price:"$849.99",status:"Delivered"},{id:"#329041",category:"Grocery",company:"FreshMart",arrival:"30 Jul 2028 1:20 pm",route:"Madrid–Lisbon",price:"$420.30",status:"Pending"}];

export default function LogisticsPage(){const [period,setPeriod]=useState("Monthly");const [status,setStatus]=useState("All");const [page,setPage]=useState(1);const chart=useMemo(()=>deliveries.map(x=>period==="Yearly"?{...x,shipment:Math.min(100,x.shipment+4),delivery:Math.min(100,x.delivery+5)}:x),[period]);const filtered=status==="All"?orders:orders.filter(x=>x.status.replace(" ","-")===status);const rows=filtered.slice((page-1)*5,page*5);return <div className="space-y-6">
  <section className="grid gap-5 md:grid-cols-3"><Kpi value="12,384" label="Total Orders"/><Kpi value="728" label="Orders in Transit"/><Kpi value="12,384" label="Delivered Orders"/></section>
  <section className="grid grid-cols-1 gap-6 lg:grid-cols-3">
    <div className="min-w-0 space-y-6 lg:col-span-2">
      <article className="panel p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-xl font-semibold">Delivery Statistics</h2><p className="muted mt-1 text-sm">Total number of deliveries <b className="text-[var(--text)]">70.5K</b></p></div><div className="soft flex rounded-lg p-1">{["Monthly","Yearly"].map(item=><button key={item} onClick={()=>setPeriod(item)} aria-pressed={period===item} className={`rounded-md px-4 py-2 text-sm ${period===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted"}`}>{item}</button>)}</div></div><div className="mt-5 flex gap-5 text-xs"><span className="muted flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#465fff]"/>Shipment</span><span className="muted flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#9cb1ff]"/>Delivery</span></div><div className="mt-4 h-[270px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{left:-22,right:5}} barGap={3} barCategoryGap="28%"><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,100]} ticks={[0,20,40,60,80,100]} allowDecimals={false} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip cursor={{fill:"var(--soft)"}} contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="shipment" name="Shipment" fill="#465fff" radius={[5,5,0,0]} maxBarSize={18}/><Bar dataKey="delivery" name="Delivery" fill="#9cb1ff" radius={[5,5,0,0]} maxBarSize={18}/></BarChart></ResponsiveContainer></div></article>
      <div className="grid gap-6 sm:grid-cols-2"><article className="panel overflow-hidden p-6"><p className="muted text-sm">Total revenue earned</p><p className="mt-2 text-3xl font-semibold tabular-nums">$23,445,700</p><div className="mt-6 border-t border-[var(--border)] pt-5"><div className="flex items-end justify-between gap-5"><div><p className="muted text-sm">Shipped quantities</p><p className="mt-2 text-2xl font-semibold">9,258</p></div><div className="h-16 w-32 shrink-0"><ResponsiveContainer width="100%" height="100%"><AreaChart data={shippedTrend}><defs><linearGradient id="shipped-mini" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#12b76a" stopOpacity=".3"/><stop offset="1" stopColor="#12b76a" stopOpacity="0"/></linearGradient></defs><Area type="monotone" dataKey="value" stroke="#12b76a" strokeWidth={2} fill="url(#shipped-mini)" dot={false}/></AreaChart></ResponsiveContainer></div></div></div></article><article className="panel overflow-hidden p-6"><CardTitle title="Delivery Vehicles"/><p className="muted mt-1 text-sm">Vehicles operating on the road</p><div className="mt-5 flex items-start justify-between"><div><p className="text-4xl font-semibold">29</p><p className="mt-2 text-xs text-emerald-600">+3.85% <span className="muted">than last Week</span></p><p className="mt-5 text-sm font-medium leading-5 text-[#12b76a]">On-route</p></div><VehicleIllustration/></div></article></div>
    </div>
    <article className="rounded-xl border border-[var(--border)] bg-[var(--soft)] p-2 lg:col-span-1"><div className="panel p-4"><CardTitle title="Tracking Delivery"/><p className="muted mt-1 text-sm">Last viewed delivery history</p></div><MapVisual/><div className="panel mt-2 p-5"><p className="muted text-xs">Tracking ID</p><div className="mt-1 flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">#28745-72809bjk</p><span className="badge bg-amber-50 text-amber-600"><Navigation size={13}/>In Transit</span></div><div className="relative mt-6 space-y-5 before:absolute before:bottom-5 before:left-[17px] before:top-5 before:w-px before:bg-[var(--border)]"><Track date="12 Apr 2028" title="Picked up" time="12:54" kind="pickup"/><Track date="12 Apr 2028" title="In Transit" time="12:58" kind="transit"/><Track date="13 Apr 2028" title="Delivered" time="--:--" kind="delivered" muted/></div><div className="mt-6 flex items-center gap-3 border-t border-[var(--border)] pt-4"><Image src="/logistics/courier-avatar.png" alt="Courier Devid walthen" width={58} height={58} className="h-[58px] w-[58px] shrink-0 rounded-full object-cover"/><div className="min-w-0"><p className="muted text-sm">Courier</p><p className="truncate text-base font-semibold">Devid walthen</p></div><div className="ml-auto flex gap-2"><button className="grid h-12 w-12 place-items-center rounded-full border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Message courier"><MessageCircle size={20}/></button><button className="grid h-12 w-12 place-items-center rounded-full border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Call courier"><Phone size={20}/></button></div></div></div></article>
  </section>
  <article className="panel min-w-0 overflow-hidden"><header className="flex flex-col gap-4 border-b border-[var(--border)] p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-semibold">Delivery Activities</h2><p className="muted mt-1 text-sm">Track your recent shipping activities</p></div><div className="flex flex-wrap gap-2">{["All","Delivered","In-Transit","Pending","Processing"].map(item=><button className={`rounded-lg px-3 py-2 text-sm ${status===item?"bg-[#465fff] text-white":"soft muted"}`} onClick={()=>{setStatus(item);setPage(1)}} aria-pressed={status===item} key={item}>{item}</button>)}<button className="btn !px-3"><Filter size={15}/>Filter</button></div></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Order ID</th><th>Category</th><th>Company</th><th>Arrival</th><th>Route</th><th>Price</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="font-semibold">{row.id}</td><td>{row.category}</td><td>{row.company}</td><td>{row.arrival}</td><td>{row.route}</td><td className="font-semibold">{row.price}</td><td><Status value={row.status}/></td></tr>)}</tbody></table></div><footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] p-5"><p className="muted text-sm">Showing {(page-1)*5+1} to {Math.min(page*5,filtered.length)} of {filtered.length}</p><div className="flex items-center gap-3"><button className="btn !p-2" aria-label="Previous page" disabled={page===1} onClick={()=>setPage(1)}><ChevronLeft size={16}/></button><span className="text-sm">Page {page} of {Math.max(1,Math.ceil(filtered.length/5))}</span><button className="btn !p-2" aria-label="Next page" disabled={page*5>=filtered.length} onClick={()=>setPage(2)}><ChevronRight size={16}/></button></div></footer></article>
 </div>}

function Kpi({value,label}:{value:string;label:string}){return <article className="panel p-5"><p className="text-3xl font-semibold leading-none tabular-nums">{value}</p><div className="mt-5 flex items-center justify-between gap-3"><p className="muted text-sm">{label}</p><span className="badge bg-emerald-50 text-emerald-600"><TrendingUp size={13}/>+20%</span></div></article>}
function CardTitle({title}:{title:string}){return <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical size={18}/></button></div>}
function MapVisual(){return <div className="relative mt-2 h-56 overflow-hidden rounded-xl bg-[#dfe7ee]"><iframe className="h-full w-full border-0 grayscale-[15%]" title="Google Map showing the delivery route" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Berlin%20Germany&z=11&output=embed"/><span className="pointer-events-none absolute bottom-4 left-4 flex items-center gap-2 rounded-lg bg-[var(--panel)] px-3 py-2 text-xs font-semibold shadow-lg"><Navigation size={15} className="text-[#465fff]"/>Live delivery route</span></div>}
function Track({date,title,time,kind,muted=false}:{date:string;title:string;time:string;kind:"pickup"|"transit"|"delivered";muted?:boolean}){const icon=kind==="pickup"?<PackageCheck size={16}/>:kind==="transit"?<Truck size={16}/>:<Check size={16}/>;return <div className="relative flex gap-3"><span className={`z-10 grid h-9 w-9 shrink-0 place-items-center rounded-full border-4 border-[var(--panel)] ${muted?"bg-gray-200 text-gray-500":"bg-indigo-100 text-[#465fff]"}`}>{icon}</span><div className="min-w-0 flex-1"><p className="muted text-xs">{date}</p><div className="mt-1 flex justify-between gap-3"><b className="text-sm">{title}</b><span className="muted text-sm">{time}</span></div></div></div>}
function VehicleIllustration(){return <Image src="/logistics/delivery-truck.png" alt="White delivery truck on route" width={200} height={132} className="h-[132px] w-[200px] max-w-[58%] object-contain"/>}
function Status({value}:{value:string}){return <span className={`badge ${value==="Delivered"?"bg-emerald-50 text-emerald-600":value==="In Transit"?"bg-blue-50 text-blue-600":value==="Pending"?"bg-amber-50 text-amber-600":"bg-gray-100 text-gray-600"}`}>{value}</span>}
