"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import { AreaChart, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { TimedArea as Area, TimedBar as Bar } from "@/components/ui/timed-charts";
import { Box, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, ClipboardCheck, EllipsisVertical, MessageCircleMore, PackageCheck, Phone, SlidersHorizontal as Filter, Truck } from "lucide-react";
import type { LucideIcon } from "lucide-react";

const deliveries=[{m:"Jan",shipment:48,delivery:38},{m:"Feb",shipment:55,delivery:44},{m:"Mar",shipment:51,delivery:48},{m:"Apr",shipment:64,delivery:53},{m:"May",shipment:61,delivery:58},{m:"Jun",shipment:72,delivery:64},{m:"Jul",shipment:68,delivery:62},{m:"Aug",shipment:79,delivery:70},{m:"Sep",shipment:75,delivery:68},{m:"Oct",shipment:84,delivery:76},{m:"Nov",shipment:88,delivery:80},{m:"Dec",shipment:94,delivery:86}];
const shippedTrend=[32,38,35,48,43,56,51,67,61,72,69,82].map((value,index)=>({index,value}));
const orders=[{id:"#324112",category:"Furniture",company:"HomeLine",arrival:"10 Apr 2028 2:15 pm",route:"Berlin–Milan",price:"$1,250.00",status:"Delivered"},{id:"#325678",category:"Clothing",company:"StylePro",arrival:"21 May 2028 9:00 am",route:"Paris–Rome",price:"$340.75",status:"Delivered"},{id:"#326789",category:"Books",company:"EduSource",arrival:"02 Jun 2028 11:45 am",route:"New York–Chicago",price:"$128.40",status:"In Transit"},{id:"#327003",category:"Automotive",company:"AutoParts Co.",arrival:"18 Mar 2028 4:00 pm",route:"Tokyo–Osaka",price:"$2,150.89",status:"Delivered"},{id:"#328556",category:"Electronics",company:"TechNova",arrival:"25 Jul 2028 10:30 am",route:"San Francisco–Seattle",price:"$849.99",status:"Delivered"},{id:"#329041",category:"Grocery",company:"FreshMart",arrival:"30 Jul 2028 1:20 pm",route:"Madrid–Lisbon",price:"$420.30",status:"Pending"}];

export default function LogisticsPage(){const [period,setPeriod]=useState("Monthly");const [periodOpen,setPeriodOpen]=useState(false);const [status,setStatus]=useState("All");const [page,setPage]=useState(1);const chart=useMemo(()=>deliveries.map(x=>period==="Yearly"?{...x,shipment:Math.min(100,x.shipment+4),delivery:Math.min(100,x.delivery+5)}:x),[period]);const filtered=status==="All"?orders:orders.filter(x=>x.status.replace(" ","-")===status);const rows=filtered.slice((page-1)*5,page*5);return <div className="space-y-6">
  <section className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><Kpi value="12,384" label="Total Orders" icon={Box}/><Kpi value="728" label="Orders in Transit" icon={Truck}/><Kpi value="12,384" label="Total Orders" icon={ClipboardCheck}/></section>
  <section className="grid grid-cols-1 gap-6 lg:grid-cols-3">
    <div className="min-w-0 space-y-6 lg:col-span-2">
      <article className="panel p-6"><div className="flex items-center justify-between gap-5"><div><h2 className="text-[18px] font-semibold leading-7">Delivery Statistics</h2><p className="muted text-sm">Total number of deliveries <span className="text-[var(--text)]">70.5K</span></p></div><div className="relative"><button className="flex h-11 w-28 items-center justify-between gap-3 rounded-lg border border-[var(--border)] bg-[var(--panel)] px-4 text-[14px] leading-5 shadow-sm" onClick={()=>setPeriodOpen(open=>!open)} aria-expanded={periodOpen} aria-haspopup="listbox">{period}<ChevronDown className={`muted transition-transform ${periodOpen?"rotate-180":""}`} size={17}/></button>{periodOpen?<div className="panel absolute right-0 top-[50px] z-30 w-full overflow-hidden p-1 shadow-xl" role="listbox" aria-label="Delivery statistics period">{["Monthly","Yearly"].map(item=><button className={`w-full rounded-md px-3 py-2 text-left text-[14px] leading-5 ${period===item?"bg-[var(--soft)] text-[var(--text)]":"muted hover:bg-[var(--soft)]"}`} onClick={()=>{setPeriod(item);setPeriodOpen(false)}} role="option" aria-selected={period===item} key={item}>{item}</button>)}</div>:null}</div></div><div className="mt-5 flex gap-5 text-xs"><span className="muted flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#9cb1ff]"/>Shipment</span><span className="muted flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#465fff]"/>Delivery</span></div><div className="mt-4 h-[254px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{left:-22,right:5}} barGap={3} barCategoryGap="28%"><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,100]} ticks={[0,20,40,60,80,100]} allowDecimals={false} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}} tickFormatter={value=>`${value}%`}/><Tooltip cursor={{fill:"var(--soft)"}} contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar animationDuration={1800} animationEasing="ease-in-out" dataKey="shipment" name="Shipment" fill="#9cb1ff" radius={[5,5,0,0]} maxBarSize={18}/><Bar animationDuration={1800} animationEasing="ease-in-out" dataKey="delivery" name="Delivery" fill="#465fff" radius={[5,5,0,0]} maxBarSize={18}/></BarChart></ResponsiveContainer></div></article>
      <div className="grid gap-6 sm:grid-cols-2"><article className="panel overflow-hidden p-6"><p className="muted text-sm">Total revenue earned</p><p className="mt-2 text-3xl font-medium tabular-nums">$23,445,700</p><div className="mt-6"><div className="flex items-end justify-between gap-5"><div><p className="muted text-sm">Shipped quantities</p><p className="mt-2 text-3xl font-medium leading-9">9,258</p></div><div className="h-16 w-32 shrink-0"><ResponsiveContainer width="100%" height="100%"><AreaChart data={shippedTrend}><defs><linearGradient id="shipped-mini" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#12b76a" stopOpacity=".3"/><stop offset="1" stopColor="#12b76a" stopOpacity="0"/></linearGradient></defs><Area animationDuration={1800} animationEasing="ease-in-out" type="monotone" dataKey="value" stroke="#12b76a" strokeWidth={2} fill="url(#shipped-mini)" dot={false}/></AreaChart></ResponsiveContainer></div></div></div></article><article className="panel overflow-hidden p-6"><CardTitle title="Delivery Vehicles"/><p className="muted mt-1 text-sm">Vehicles operating on the road</p><div className="mt-5 flex items-start justify-between"><div><p className="text-3xl font-medium leading-9">29</p><p className="mt-2 text-xs text-emerald-600">+3.85% <span className="muted">than last Week</span></p><p className="mt-5 text-sm font-medium leading-5 text-[#12b76a]">On-route</p></div><VehicleIllustration/></div></article></div>
    </div>
    <article className="rounded-xl border border-[var(--border)] bg-[var(--soft)] p-2 lg:col-span-1"><div className="panel p-4"><CardTitle title="Tracking Delivery"/><p className="muted mt-1 text-sm">Last viewed delivery history</p><MapVisual/></div><div className="panel mt-2 p-5"><p className="muted text-sm">Tracking ID</p><div className="mt-1 flex flex-wrap items-center justify-between gap-2"><p className="text-lg font-semibold leading-7">#28745-72809bjk</p><span className="badge bg-emerald-50 text-emerald-600">In Transit</span></div><div className="relative mt-6 space-y-5"><span className="pointer-events-none absolute left-[23px] top-6 h-[72px] border-l-2 border-dotted border-[#465fff]" aria-hidden="true"/><span className="pointer-events-none absolute bottom-6 left-[23px] top-[102px] w-px bg-[var(--border)]" aria-hidden="true"/><Track date="12 Apr 2028" title="Picked up" time="12:54" kind="pickup"/><Track date="12 Apr 2028" title="In Transit" time="12:58" kind="transit"/><Track date="13 Apr 2028" title="Delivered" time="--:--" kind="delivered" muted/></div></div><div className="panel mt-2 flex items-center gap-3 p-3"><Image src="/logistics/courier-avatar.png" alt="Courier Devid walthen" width={58} height={58} className="h-[58px] w-[58px] shrink-0 rounded-full object-cover"/><div className="min-w-0"><p className="muted text-sm">Courier</p><p className="truncate text-base font-semibold">Devid walthen</p></div><div className="ml-auto flex gap-2"><button className="grid h-12 w-12 place-items-center rounded-full border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Message courier"><MessageCircleMore size={20}/></button><button className="grid h-12 w-12 place-items-center rounded-full border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Call courier"><Phone size={20}/></button></div></div></article>
  </section>
  <article className="logistics-delivery-activities panel min-w-0 overflow-hidden"><header className="flex flex-col gap-4 border-b border-[var(--border)] px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="shrink-0"><h2 className="text-xl font-semibold">Delivery Activities</h2><p className="muted mt-1 text-sm">Track your recent shipping activities</p></div><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-center"><div className="soft flex min-w-0 overflow-x-auto rounded-lg p-1">{["All","Delivered","In-Transit","Pending","Processing"].map(item=><button className={`shrink-0 rounded-md px-4 py-2 text-sm ${status===item?"bg-[var(--panel)] text-[var(--text)] shadow-sm":"muted"}`} onClick={()=>{setStatus(item);setPage(1)}} aria-pressed={status===item} key={item}>{item}</button>)}</div><button className="btn h-[46px] shrink-0 !gap-2 !px-5 !font-normal"><Filter size={18}/>Filter</button></div></header><div className="table-wrap"><table className="data-table"><thead><tr><th><input type="checkbox" aria-label="Select all deliveries"/></th><th>Order ID</th><th><span>Category<ChevronsUpDown/></span></th><th><span>Company<ChevronsUpDown/></span></th><th><span>Arrival<ChevronsUpDown/></span></th><th>Route</th><th>Price</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={`Select delivery ${row.id}`}/></td><td>{row.id}</td><td>{row.category}</td><td>{row.company}</td><td>{row.arrival}</td><td>{row.route}</td><td>{row.price}</td><td><Status value={row.status}/></td></tr>)}</tbody></table></div><footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] px-6 py-5"><p className="muted text-sm">Showing {(page-1)*5+1} to {Math.min(page*5,filtered.length)} of {filtered.length}</p><div className="flex items-center gap-2"><button className="btn !h-11 !w-11 !p-0" aria-label="Previous page" disabled={page===1} onClick={()=>setPage(1)}><ChevronLeft size={18}/></button>{Array.from({length:Math.max(1,Math.ceil(filtered.length/5))},(_,index)=>index+1).map(item=><button className={`h-11 w-11 rounded-lg text-sm ${page===item?"bg-[#465fff] text-white":"hover:bg-[var(--soft)]"}`} onClick={()=>setPage(item)} aria-current={page===item?"page":undefined} key={item}>{item}</button>)}<button className="btn !h-11 !w-11 !p-0" aria-label="Next page" disabled={page*5>=filtered.length} onClick={()=>setPage(page+1)}><ChevronRight size={18}/></button></div></footer></article>
 </div>}

function Kpi({value,label,icon:Icon}:{value:string;label:string;icon:LucideIcon}){return <article className="panel flex min-h-[98px] items-center gap-5 p-4"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-[var(--soft)] text-[#344054]"><Icon size={25} strokeWidth={1.7}/></span><div className="min-w-0"><p className="text-2xl font-semibold leading-8 tabular-nums">{value}</p><div className="flex flex-wrap items-center gap-3"><p className="muted whitespace-nowrap text-sm">{label}</p><span className="badge bg-emerald-50 text-emerald-600">+20%</span></div></div></article>}
function CardTitle({title}:{title:string}){return <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical size={18}/></button></div>}
function MapVisual(){return <div className="mt-6 overflow-hidden rounded-xl bg-[#dfe7ee]" style={{aspectRatio:"1.82 / 1"}}><iframe className="h-full w-full border-0 grayscale-[15%]" title="Google Map showing the delivery route" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Pimjo%20Dhaka&z=14&output=embed"/></div>}
function Track({date,title,time,kind,muted=false}:{date:string;title:string;time:string;kind:"pickup"|"transit"|"delivered";muted?:boolean}){const icon=kind==="pickup"?<PackageCheck size={18}/>:kind==="transit"?<Truck size={18}/>:<Check size={18}/>;return <div className="relative flex min-h-14 gap-4"><span className={`z-10 grid h-12 w-12 shrink-0 place-items-center rounded-full ring-4 ring-[var(--panel)] ${muted?"bg-gray-200 text-gray-500":"bg-indigo-50 text-[#465fff]"}`}>{icon}</span><div className="min-w-0 flex-1"><p className="muted text-sm">{date}</p><div className="mt-1 flex justify-between gap-3"><b className="text-base font-semibold">{title}</b><span className="muted text-sm">{time}</span></div></div></div>}
function VehicleIllustration(){return <Image src="/logistics/delivery-truck.png" alt="White delivery truck on route" width={200} height={132} className="h-[132px] w-[200px] max-w-[58%] object-contain"/>}
function Status({value}:{value:string}){return <span className={`badge ${value==="Delivered"?"bg-emerald-50 text-emerald-600":value==="In Transit"?"bg-amber-50 text-amber-600":value==="Pending"?"bg-amber-50 text-amber-600":"bg-gray-100 text-gray-600"}`}>{value}</span>}
