"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { StatCard } from "@/components/ui/stat-card";
import { ArrowDown, ArrowUp, BrainCircuit, CalendarDays, Clock3, DollarSign, EllipsisVertical, FolderOpen, Search, SlidersHorizontal as Filter, Sparkles, Target, UserRoundCheck, Users, X, Zap } from "lucide-react";

const stats=[{label:"Users",value:"10,590",icon:"users",change:"+3.52%"},{label:"Projects",value:"15,682",icon:"projects",change:"+3.52%"},{label:"Revenue",value:"$90,369",icon:"revenue",change:"+14.8%"},{label:"Paid Users",value:"520",icon:"paid",change:"-9.05%",down:true}];
const monthly=[{m:"Jan",users:23000,revenue:13000},{m:"Feb",users:24500,revenue:14200},{m:"Mar",users:22600,revenue:12600},{m:"Apr",users:24800,revenue:14800},{m:"May",users:23200,revenue:13500},{m:"Jun",users:25200,revenue:15400},{m:"Jul",users:24600,revenue:14700},{m:"Aug",users:27100,revenue:17000},{m:"Sep",users:25800,revenue:16000},{m:"Oct",users:28600,revenue:18400},{m:"Nov",users:27300,revenue:17200},{m:"Dec",users:31000,revenue:19900}];
const tokens=[{name:"GPT",keys:"2 API keys configured",value:"7M",amount:7,color:"#6683f6",icon:"gpt"},{name:"Gemini",keys:"1 API key configured",value:"2.5M",amount:2.5,color:"#6ec8e8",icon:"gemini"},{name:"xAI",keys:"2 API key configured",value:"4.5M",amount:4.5,color:"#a695f7",icon:"xai"}];
const transactions=[{name:"John Doe",email:"johndeo@gmail.com",pkg:"Starter - Monthly",price:"$20.00",date:"28 Feb, 2029",status:"Active"},{name:"Kierra Gentry",email:"kierra@gmail.com",pkg:"Growth - Yearly",price:"$249.00",date:"28 Jan, 2029",status:"Active"},{name:"Emerson Workman",email:"emerson@gmail.com",pkg:"Premium - Monthly",price:"$199.00",date:"5 Jan, 2029",status:"Expired"},{name:"Chance Philips",email:"chance@gmail.com",pkg:"Growth - Yearly",price:"$249.00",date:"12 Dec, 2028",status:"Active"},{name:"Terry Geidt",email:"terry@gmail.com",pkg:"Starter - Monthly",price:"$20.00",date:"25 Nov, 2028",status:"Expired"}];

export default function AiPage(){const [period,setPeriod]=useState("Monthly");const [query,setQuery]=useState("");const [filter,setFilter]=useState("All");const factor=period==="Quarterly"?1.11:period==="Annually"?1.26:1;const chart=useMemo(()=>monthly.map(x=>({...x,users:Math.round(x.users*factor),revenue:Math.round(x.revenue*factor)})),[factor]);const rows=transactions.filter(x=>(filter==="All"||x.status===filter)&&`${x.name} ${x.email} ${x.pkg}`.toLowerCase().includes(query.toLowerCase()));return <div className="space-y-6">
  <section className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4" aria-label="AI summary">{stats.map(item=><Kpi key={item.label} item={item}/>)}</section>
  <section className="grid grid-cols-1 gap-6 xl:grid-cols-12">
    <article className="panel flex min-w-0 flex-col p-6 xl:col-span-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-xl font-semibold">Users & Revenue Statistics</h2><p className="muted mt-1 text-sm">Visualize month-to-month progress and engagement.</p></div><div className="soft flex rounded-lg p-1">{["Monthly","Quarterly","Annually"].map(item=><button className={`rounded-md px-4 py-2 text-sm ${period===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted"}`} onClick={()=>setPeriod(item)} aria-pressed={period===item} key={item}>{item}</button>)}</div></div><div className="mt-6 flex gap-5 text-xs"><Legend color="#465fff" label="Users"/><Legend color="#9cb1ff" label="Revenue"/></div><div className="mt-4 min-h-[360px] flex-1"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{left:0,right:6,bottom:0}}><defs><linearGradient id="ai-users" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#465fff" stopOpacity=".25"/><stop offset="1" stopColor="#465fff" stopOpacity="0"/></linearGradient><linearGradient id="ai-revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9cb1ff" stopOpacity=".2"/><stop offset="1" stopColor="#9cb1ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}K`} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Area animationDuration={1800} animationEasing="ease-in-out" type="linear" dataKey="users" stroke="#465fff" strokeWidth={2} fill="url(#ai-users)" dot={false}/><Area animationDuration={1800} animationEasing="ease-in-out" type="linear" dataKey="revenue" stroke="#9cb1ff" strokeWidth={2} fill="url(#ai-revenue)" dot={false}/></AreaChart></ResponsiveContainer></div></article>
    <article className="panel flex h-full min-w-0 flex-col overflow-hidden px-3 py-2 xl:col-span-4"><div className="flex items-center justify-between p-3"><h2 className="text-xl font-semibold">API Token Usages</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label="API Token Usages options"><EllipsisVertical size={18}/></button></div><div className="relative h-[230px] shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie animationDuration={1800} animationEasing="ease-in-out" data={tokens} dataKey="amount" innerRadius={72} outerRadius={102} startAngle={90} endAngle={-270} stroke="none">{tokens.map(x=><Cell fill={x.color} key={x.name}/>)}</Pie><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="text-2xl font-semibold">13.5M</p><p className="muted mt-1 text-xs">2450</p></div></div></div><div className="divide-y divide-[var(--border)] border-t border-[var(--border)]">{tokens.map(x=><div className="flex items-center gap-3 px-3 py-4" key={x.name}><TokenIcon type={x.icon} color={x.color}/><div><p className="font-semibold">{x.name}</p><p className="muted text-xs">{x.keys}</p></div><div className="ml-auto text-right"><p className="font-semibold" style={{color:x.color}}>• {x.value}</p><p className="muted text-xs">Token used</p></div></div>)}</div><button className="mt-auto w-full border-t border-[var(--border)] p-4 text-sm font-semibold hover:bg-[var(--soft)]">View All Usage Details</button></article>
  </section>
  <section className="grid gap-6 lg:grid-cols-2"><AnalyticsCard type="users"/><AnalyticsCard type="projects"/></section>
  <article className="panel min-w-0 overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 p-6"><h2 className="text-xl font-semibold">Recent Transactions</h2><div className="flex flex-wrap gap-3"><label className="relative block max-w-full"><Search className="muted absolute left-3 top-1/2 -translate-y-1/2" size={17}/><span className="sr-only">Search transactions</span><input className="field !w-60 max-w-full !pl-10" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="relative"><button className="btn !font-normal"><Filter size={16}/>Filter</button><select className="absolute inset-0 cursor-pointer opacity-0" aria-label="Filter transaction status" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Active</option><option>Expired</option></select></div></div></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Paid By</th><th>Package Name</th><th>Price</th><th>Paid Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.email}><td><div className="flex min-w-48 items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-indigo-50 font-semibold text-[#465fff]">{row.name.split(" ").map(x=>x[0]).join("")}</span><div><p className="font-semibold">{row.name}</p><p className="muted text-xs">{row.email}</p></div></div></td><td>{row.pkg}</td><td className="font-semibold">{row.price}</td><td>{row.date}</td><td><span className={`badge ${row.status==="Active"?"bg-emerald-50 text-emerald-600":"bg-red-50 text-red-500"}`}>{row.status}</span></td><td><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`Actions for ${row.name}`}><EllipsisVertical size={17}/></button></td></tr>)}</tbody></table></div><footer className="flex justify-center gap-2 border-t border-[var(--border)] p-5">{[1,2,3].map(page=><button className={`grid h-9 w-9 place-items-center rounded-lg text-sm ${page===1?"bg-[#465fff] text-white":"border border-[var(--border)]"}`} key={page}>{page}</button>)}</footer></article>
 </div>}

function Kpi({item}:{item:(typeof stats)[number]}){const icon=item.icon==="users"?<Users/>:item.icon==="projects"?<FolderOpen/>:item.icon==="revenue"?<DollarSign/>:<UserRoundCheck/>;const iconColor=item.icon==="projects"?"text-sky-500":item.icon==="revenue"?"text-emerald-500":item.down?"text-amber-500":"text-[#465fff]";return <StatCard icon={<span className={`grid h-6 w-6 place-items-center [&_svg]:h-[21px] [&_svg]:w-[21px] ${iconColor}`}>{icon}</span>} label={item.label} value={item.value} change={item.change} down={item.down} trendIcon={item.down?<ArrowDown size={14}/>:<ArrowUp size={14}/>} variant="ai"/>}
function TokenIcon({type,color}:{type:string;color:string}){const icon=type==="gpt"?<BrainCircuit/>:type==="gemini"?<Sparkles/>:<X/>;return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-[var(--border)] [&_svg]:h-5 [&_svg]:w-5" style={{color}}>{icon}</span>}
function Legend({color,label}:{color:string;label:string}){return <span className="muted flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{background:color}}/>{label}</span>}
function AnalyticsCard({type}:{type:"users"|"projects"}){const users=type==="users";const cells=users?[{label:"Free Users",value:"15,682",note:"95% of total user",icon:<Users/>,color:"text-[#465fff]"},{label:"Paid Users",value:"305",note:"5% of total user",icon:<UserRoundCheck/>,color:"text-amber-500"},{label:"This Month",value:"4,925",note:"+5,238 from last month",icon:<CalendarDays/>,color:"text-emerald-500"},{label:"This Year",value:"12,489",note:"+12,495 from last year",icon:<Target/>,color:"text-pink-500"}]:[{label:"Today",value:"120",note:"Project created",icon:<Zap/>,color:"text-violet-500"},{label:"Yesterday",value:"392",note:"Project created",icon:<Clock3/>,color:"text-sky-500"},{label:"This Month",value:"3,835",note:"+2,093 from last month",icon:<CalendarDays/>,color:"text-emerald-500"},{label:"This Year",value:"12,958",note:"+8,532 from last year",icon:<Target/>,color:"text-pink-500"}];return <article className="panel p-5"><div className="mb-4 flex items-start justify-between"><div><h2 className="text-base font-medium">{users?"User Analytics":"Projects Analytics"}</h2><p className="muted mt-1 text-sm">{users?"Platform user insights":"View detailed project insights"}</p></div><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${users?"User":"Projects"} Analytics options`}><EllipsisVertical size={18}/></button></div><div className="mb-3 flex items-center justify-between gap-4"><div className="flex items-center gap-1"><span className="muted">{users?<Users size={22}/>:<FolderOpen size={22}/>}</span><span className="muted">Total {users?"Users":"Projects"}</span></div><b className="text-[24px] font-semibold leading-8">{users?"10,590":"15,682"}</b></div><div className="grid gap-1 overflow-hidden rounded-2xl bg-[var(--soft)] p-1 sm:grid-cols-2">{cells.map((cell)=><div className="flex flex-col rounded-md bg-[var(--panel)] p-5" key={cell.label}><div className="mb-4 flex items-center justify-between gap-3"><p className="muted text-sm">{cell.label}</p><span className={`[&_svg]:h-5 [&_svg]:w-5 ${cell.color}`}>{cell.icon}</span></div><p className="text-xl font-semibold">{cell.value}</p><p className={`mt-2 text-xs ${cell.note.startsWith("+")?"text-emerald-600":"muted"}`}>{cell.note}</p></div>)}</div></article>}
