"use client";

import { CheckCircle2, ChevronLeft, ChevronRight, Hourglass, MoreHorizontal, Search, SlidersHorizontal, Ticket } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

type Status = "Solved" | "Pending";
type TicketRow = { id: string; name: string; email: string; subject: string; date: string; status: Status };
const tickets: TicketRow[] = [
  { id: "#323534", name: "Lindsey Curtis", email: "demoemail@gmail.com", subject: "Issue with Dashboard Login Access", date: "12 Feb, 2027", status: "Solved" },
  { id: "#323535", name: "Kaiya George", email: "demoemail@gmail.com", subject: "Billing Information Not Updating Properly", date: "13 Mar, 2027", status: "Pending" },
  { id: "#323536", name: "Zain Geidt", email: "demoemail@gmail.com", subject: "Bug Found in Dark Mode Layout", date: "19 Mar, 2027", status: "Pending" },
  { id: "#323537", name: "Abram Schleifer", email: "demoemail@gmail.com", subject: "Request to Add New Integration Feature", date: "25 Apr, 2027", status: "Solved" },
  { id: "#323538", name: "Mia Chen", email: "mia.chen@email.com", subject: "Unable to Reset Password", date: "28 Apr, 2027", status: "Pending" },
  { id: "#323539", name: "John Doe", email: "john.doe@email.com", subject: "Feature Request: Dark Mode", date: "30 Apr, 2027", status: "Solved" },
  { id: "#323540", name: "Jane Smith", email: "jane.smith@email.com", subject: "Error 500 on Dashboard", date: "01 May, 2027", status: "Pending" },
  { id: "#323541", name: "Carlos Ruiz", email: "carlos.ruiz@email.com", subject: "Cannot Download Invoice", date: "02 May, 2027", status: "Solved" },
  { id: "#323542", name: "Emily Clark", email: "emily.clark@email.com", subject: "UI Bug in Mobile View", date: "03 May, 2027", status: "Pending" },
  { id: "#323543", name: "Liam Wong", email: "liam.wong@email.com", subject: "Account Locked", date: "04 May, 2027", status: "Solved" },
  { id: "#323544", name: "Olivia Davis", email: "olivia@email.com", subject: "Payment method declined", date: "05 May, 2027", status: "Pending" },
  { id: "#323545", name: "Noah Wilson", email: "noah@email.com", subject: "Export report is incomplete", date: "06 May, 2027", status: "Solved" },
];

export default function SupportTicketsPage() {
  const [tab, setTab] = useState<"All" | Status>("All"), [query, setQuery] = useState(""), [filterOpen, setFilterOpen] = useState(false), [page, setPage] = useState(1), [selected, setSelected] = useState<string[]>([]), [menu, setMenu] = useState<string | null>(null);
  const filtered = useMemo(() => tickets.filter(ticket => (tab === "All" || ticket.status === tab) && `${ticket.id} ${ticket.name} ${ticket.email} ${ticket.subject}`.toLowerCase().includes(query.toLowerCase())), [query, tab]);
  const rows = filtered.slice((page - 1) * 10, page * 10);
  const selectAll = (checked: boolean) => setSelected(checked ? rows.map(row => row.id) : []);
  return <div className="support-tickets-page space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">Support List</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Support List</span></nav></header>
    <section className="grid gap-5 sm:grid-cols-3"><Metric icon={<Ticket size={24}/>} value="5,347" label="Total tickets" tone="bg-indigo-50 text-[#465fff]"/><Metric icon={<Hourglass size={24}/>} value="1,230" label="Pending tickets" tone="bg-orange-50 text-orange-500"/><Metric icon={<CheckCircle2 size={24}/>} value="4,117" label="Solved tickets" tone="bg-emerald-50 text-emerald-500"/></section>
    <section className="panel overflow-hidden"><header className="flex flex-col gap-4 border-b border-[var(--border)] px-5 py-[18px] xl:flex-row xl:items-center"><div className="min-w-[250px]"><h2 className="text-xl font-semibold">Support Tickets</h2><p className="muted mt-1 text-sm">Your most recent support tickets list</p></div><div className="soft flex rounded-lg p-1 xl:ml-auto">{(["All","Solved","Pending"] as const).map(item => <button className={`rounded-md px-4 py-2 text-sm ${tab === item ? "bg-[var(--panel)] font-medium shadow-sm" : "muted"}`} onClick={() => { setTab(item); setPage(1); }} aria-pressed={tab === item} key={item}>{item}</button>)}</div><label className="relative block w-full xl:max-w-[295px]"><Search className="muted absolute left-4 top-1/2 -translate-y-1/2" size={18}/><input className="control !pl-11" placeholder="Search..." value={query} onChange={event => { setQuery(event.target.value); setPage(1); }}/></label><div className="relative"><button className="btn h-11 !px-5" onClick={() => setFilterOpen(value => !value)} aria-expanded={filterOpen}><SlidersHorizontal size={17}/>Filter</button>{filterOpen ? <div className="panel absolute right-0 z-30 mt-2 w-36 p-2 shadow-xl">{(["All","Solved","Pending"] as const).map(item => <button className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-[var(--soft)]" onClick={() => { setTab(item); setFilterOpen(false); setPage(1); }} key={item}>{item}</button>)}</div> : null}</div></header>
      <div className="table-wrap"><table className="data-table min-w-[850px]"><thead><tr><th><input type="checkbox" className="h-4 w-4 accent-[#465fff]" aria-label="Select all tickets" checked={rows.length > 0 && rows.every(row => selected.includes(row.id))} onChange={event => selectAll(event.target.checked)}/></th><th>Ticket ID</th><th>Requested By</th><th>Subject</th><th>Create Date</th><th>Status</th><th/></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><input type="checkbox" className="h-4 w-4 accent-[#465fff]" aria-label={`Select ${row.id}`} checked={selected.includes(row.id)} onChange={event => setSelected(items => event.target.checked ? [...items,row.id] : items.filter(id => id !== row.id))}/></td><td>{row.id}</td><td><p className="font-medium">{row.name}</p><p className="muted mt-1 text-sm">{row.email}</p></td><td>{row.subject}</td><td>{row.date}</td><td><span className={`rounded-full px-2.5 py-1 text-xs ${row.status === "Solved" ? "bg-emerald-50 text-emerald-600" : "bg-amber-50 text-amber-600"}`}>{row.status}</span></td><td className="relative"><button className="rounded-lg p-2 hover:bg-[var(--soft)]" onClick={() => setMenu(menu === row.id ? null : row.id)} aria-label={`Actions for ${row.id}`}><MoreHorizontal size={18}/></button>{menu === row.id ? <div className="panel absolute right-8 top-10 z-20 w-32 p-1 shadow-xl"><Link className="block rounded-md px-3 py-2 text-sm hover:bg-[var(--soft)]" href="/support-ticket-reply">View ticket</Link><button className="w-full rounded-md px-3 py-2 text-left text-sm hover:bg-[var(--soft)]" onClick={() => setMenu(null)}>Mark {row.status === "Solved" ? "pending" : "solved"}</button></div> : null}</td></tr>)}</tbody></table></div>
      <footer className="flex flex-wrap items-center justify-between gap-4 border-t border-[var(--border)] px-5 py-4"><p className="muted text-sm">Showing {(page - 1) * 10 + 1} to {Math.min(page * 10, filtered.length)} of {filtered.length}</p><div className="flex items-center gap-2"><button className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] disabled:opacity-40" disabled={page === 1} onClick={() => setPage(page - 1)} aria-label="Previous page"><ChevronLeft size={16}/></button>{[1,2].map(value => <button className={`grid h-9 w-9 place-items-center rounded-lg text-sm ${page === value ? "bg-[#465fff] text-white" : "border border-[var(--border)]"}`} onClick={() => setPage(value)} key={value}>{value}</button>)}<button className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] disabled:opacity-40" disabled={page * 10 >= filtered.length} onClick={() => setPage(page + 1)} aria-label="Next page"><ChevronRight size={16}/></button></div></footer>
    </section>
  </div>;
}

function Metric({ icon, value, label, tone }: { icon: React.ReactNode; value: string; label: string; tone: string }) { return <article className="panel flex min-h-[90px] items-center gap-5 p-4"><span className={`grid h-14 w-14 shrink-0 place-items-center rounded-xl ${tone}`}>{icon}</span><div><p className="text-lg font-semibold">{value}</p><p className="muted mt-1 text-sm">{label}</p></div></article>; }
