"use client";

import { CreditCard, Eye, Mail, RefreshCcw, Send, ShoppingCart } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const items=[["1",'Macbook pro 13”',"1","$1200","0%","$1200"],["2","Apple Watch Ultra","1","$300","50%","$150"],["3","iPhone 15 Pro Max","2","$800","0%","$1600"],["4","iPad Pro 3rd Gen","1","$900","0%","$900"]];

export default function SingleTransactionPage(){
  const [message,setMessage]=useState("");
  return <div className="space-y-6 text-sm">
    <div className="flex items-center justify-between"><h1 className="text-[22px] font-semibold">Single Transaction</h1><div className="muted flex items-center gap-2"><Link href="/ecommerce" className="hover:text-[#465fff]">Home</Link><span>/</span><span>Single Transaction</span></div></div>
    {message&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-700" role="status">{message}</div>}
    <section className="flex flex-col gap-5 rounded-2xl border border-[var(--border)] bg-[var(--panel)] px-6 py-5 lg:flex-row lg:items-center"><div className="flex flex-wrap items-center gap-4"><h2 className="text-[17px] font-semibold">Order ID : #34834</h2><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-600">Completed</span><span className="hidden h-6 w-px bg-[var(--border)] sm:block"/><p className="muted">Due date: 25 August 2025</p></div><div className="flex gap-3 lg:ml-auto"><button className="btn btn-primary h-11 px-5" onClick={()=>setMessage("Receipt #1734535 opened.")}>View Receipt</button><button className="btn h-11 px-5" onClick={()=>setMessage("Refund request opened for order #34834.")}>Refund</button></div></section>

    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
      <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)]"><div className="px-6 pb-4 pt-6"><h2 className="text-[18px] font-semibold">Order Details</h2></div><div className="px-6 pb-6"><div className="overflow-x-auto rounded-xl border border-[var(--border)]"><table className="w-full min-w-[680px] text-left"><thead className="bg-[var(--soft)]"><tr>{["S. No.","Products","Quantity","Unit Cost","Discount","Total"].map(heading=><th key={heading} className="px-5 py-4 font-medium">{heading}</th>)}</tr></thead><tbody>{items.map(row=><tr key={row[0]} className="border-t border-[var(--border)]"><td className="muted px-5 py-4">{row[0]}</td><td className="px-5 py-4 font-medium">{row[1]}</td><td className="muted px-5 py-4">{row[2]}</td><td className="muted px-5 py-4">{row[3]}</td><td className="muted px-5 py-4">{row[4]}</td><td className="muted px-5 py-4">{row[5]}</td></tr>)}</tbody></table></div><div className="ml-auto mt-7 w-full max-w-[220px]"><h3 className="mb-5 font-semibold">Order summary</h3><div className="space-y-3"><p className="flex justify-between"><span className="muted">Sub Total</span><b>$3,850</b></p><p className="flex justify-between"><span className="muted">Vat (10%):</span><b>$385</b></p><p className="flex justify-between text-lg"><span>Total</span><b>$4,235</b></p></div></div></div></section>

      <div className="space-y-6">
        <section className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)]"><div className="px-5 py-6"><h2 className="text-[18px] font-semibold">Customer Details</h2><dl className="mt-5 divide-y divide-[var(--border)]">{[["Name","Mushafrof Chowdhury"],["Email","name@example.com"],["Phone","Mountain View, CA, 94040"],["Phone","+123 456 7890"],["Country","United States"],["Address","62 Miles Drive St, Newark, NJ 07103, California."]].map(([label,value],index)=><div key={`${label}-${index}`} className="grid grid-cols-[80px_1fr] gap-3 py-3"><dt className="muted">{label}</dt><dd className="font-medium leading-5">{value}</dd></div>)}</dl></div></section>

        <section className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><h2 className="text-[18px] font-semibold">Order History</h2><div className="mt-6 space-y-0">{[[ShoppingCart,"Checkout Started","via tailadmin.com","12:54","12th Apr 28"],[CreditCard,"Purchased","for US$4,235 via PayPal","12:58","12th Apr 28"],[Mail,"Receipt Email Sent","Receipt #1734535","12:58","12th Apr 28"]].map(([Icon,title,description,time,date],index)=><div key={String(title)} className="relative grid grid-cols-[48px_1fr_52px] gap-3 pb-7 last:pb-3">{index<2&&<span className="absolute left-6 top-11 h-[calc(100%-36px)] border-l border-dashed border-[var(--border)]"/>}<span className="relative z-10 grid h-12 w-12 place-items-center rounded-full border border-[var(--border)] bg-[var(--panel)]"><Icon size={19}/></span><div><h3 className="font-semibold">{String(title)}</h3><p className="muted mt-1 leading-5">{String(description)}</p></div><p className="muted text-xs leading-5">{String(time)}<br/>{String(date)}</p></div>)}</div><div className="flex flex-wrap gap-2"><button className="btn h-9 px-3 text-xs" onClick={()=>setMessage("Receipt email resent.")}><RefreshCcw size={14}/>Resend</button><button className="btn h-9 px-3 text-xs" onClick={()=>setMessage("Receipt forwarding opened.")}><Send size={14}/>Forward</button><button className="btn h-9 px-3 text-xs" onClick={()=>setMessage("Receipt preview opened.")}><Eye size={14}/>Preview</button></div></section>
      </div>
    </div>
  </div>;
}
