"use client";

import { Archive, ChevronDown, ChevronLeft, ChevronRight, EllipsisVertical, Inbox, LockKeyhole, Mail, Pencil, RefreshCw, Search, Send, Star, Trash2 } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

type Email = { id: number; sender: string; preview: string; date: string; box: string; label?: "Important" | "Social" | "Promotional"; starred?: boolean };
const copy = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda dolor dolore esse modi nesciunt, nobis numquam sed sequi sunt totam!";
const seed: Email[] = [
  { id: 1, sender: "Material UI", preview: copy, date: "12:16 pm", box: "Inbox", label: "Important" },{ id: 2, sender: "Wise", preview: copy, date: "12:16 pm", box: "Inbox" },{ id: 3, sender: "Search Console", preview: copy, date: "Apr, 24", box: "Inbox", label: "Social" },{ id: 4, sender: "Paypal", preview: copy, date: "Apr, 30", box: "Inbox" },{ id: 5, sender: "Google Meet", preview: copy, date: "Apr, 16", box: "Inbox" },{ id: 6, sender: "Loom", preview: copy, date: "Apr, 24", box: "Inbox" },{ id: 7, sender: "Airbnb", preview: copy, date: "Mar, 05", box: "Inbox" },{ id: 8, sender: "Facebook", preview: copy, date: "Feb, 25", box: "Inbox" },{ id: 9, sender: "Instagram", preview: copy, date: "Feb, 20", box: "Inbox", label: "Promotional" },{ id: 10, sender: "Google", preview: copy, date: "Feb, 25", box: "Inbox" },{ id: 11, sender: "FormBold", preview: copy, date: "Jan, 22", box: "Inbox" },{ id: 12, sender: "GrayGrids", preview: copy, date: "Feb, 25", box: "Inbox" },{ id: 13, sender: "UIdeck", preview: copy, date: "Feb, 15", box: "Inbox" },
];
const mailboxes = [{ name: "Inbox", icon: Inbox, count: 3 },{ name: "Sent", icon: Send },{ name: "Drafts", icon: Mail },{ name: "Spam", icon: LockKeyhole, count: 2 },{ name: "Trash", icon: Trash2 },{ name: "Archive", icon: Archive }];

export default function InboxPage() {
  const [emails, setEmails] = useState(seed), [box, setBox] = useState("Inbox"), [query, setQuery] = useState(""), [selected, setSelected] = useState<number[]>([]), [compose, setCompose] = useState(false), [page, setPage] = useState(1), [to, setTo] = useState(""), [subject, setSubject] = useState(""), [body, setBody] = useState("");
  const visible = useMemo(() => emails.filter(email => (box === "Starred" ? email.starred : box === "Important" ? email.label === "Important" : email.box === box) && `${email.sender} ${email.preview}`.toLowerCase().includes(query.toLowerCase())), [box, emails, query]);
  const toggleAll = (checked: boolean) => setSelected(checked ? visible.map(email => email.id) : []);
  const deleteSelected = () => { setEmails(items => items.filter(email => !selected.includes(email.id))); setSelected([]); };
  const archiveSelected = () => { setEmails(items => items.map(email => selected.includes(email.id) ? { ...email, box: "Archive" } : email)); setSelected([]); };
  const sendMail = (event: React.FormEvent) => { event.preventDefault(); setEmails(items => [{ id: Date.now(), sender: to, preview: subject || body, date: "Just now", box: "Sent" }, ...items]); setTo(""); setSubject(""); setBody(""); setCompose(false); };
  return <div className="space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">Inbox</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Inbox</span></nav></header>
    <div className="grid h-[550px] gap-5 lg:grid-cols-[214px_minmax(0,1fr)]">
      <aside className="panel overflow-hidden p-4"><button className="btn btn-primary h-11 w-full" onClick={() => setCompose(true)}><Pencil size={17}/>Compose</button><div className="mt-5 h-[455px] overflow-y-auto pr-1"><MailSection title="MAILBOX">{mailboxes.map(item => <MailboxButton item={item} active={box === item.name} onClick={() => { setBox(item.name); setSelected([]); }} key={item.name}/>)}</MailSection><MailSection title="FILTER"><MailboxButton item={{name:"Starred",icon:Star}} active={box === "Starred"} onClick={() => setBox("Starred")}/><MailboxButton item={{name:"Important",icon:LockKeyhole}} active={box === "Important"} onClick={() => setBox("Important")}/></MailSection><MailSection title="LABEL"><LabelButton color="bg-sky-500" label="Personal"/><LabelButton color="bg-orange-500" label="Work"/><LabelButton color="bg-emerald-500" label="Payments"/><LabelButton color="bg-violet-500" label="Invoices"/></MailSection></div></aside>
      <section className="panel min-w-0 overflow-hidden"><header className="flex h-[76px] items-center gap-2 border-b border-[var(--border)] px-4"><div className="flex items-center"><span className="grid h-10 w-10 place-items-center rounded-l-lg border border-[var(--border)]"><input type="checkbox" className="h-4 w-4 accent-[#465fff]" aria-label="Select all emails" checked={visible.length > 0 && visible.every(email => selected.includes(email.id))} onChange={event => toggleAll(event.target.checked)}/></span><button className="grid h-10 w-8 place-items-center rounded-r-lg border-y border-r border-[var(--border)]" aria-label="Selection options"><ChevronDown size={15}/></button></div><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" onClick={() => setEmails([...emails])} aria-label="Refresh inbox"><RefreshCw size={17}/></button><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)] disabled:opacity-40" disabled={!selected.length} onClick={deleteSelected} aria-label="Delete selected"><Trash2 size={17}/></button><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)] disabled:opacity-40" disabled={!selected.length} onClick={archiveSelected} aria-label="Archive selected"><Archive size={17}/></button><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)]" aria-label="More email actions"><EllipsisVertical size={17}/></button><label className="relative ml-auto w-full max-w-[235px]"><Search className="muted absolute left-4 top-1/2 -translate-y-1/2" size={18}/><input className="control !h-11 !pl-11" placeholder="Search..." value={query} onChange={event => setQuery(event.target.value)}/></label></header>
        <div className="h-[418px] overflow-y-auto">{visible.map(email => <article className="flex h-[52px] items-center gap-3 border-b border-[var(--border)] px-4 text-sm hover:bg-[var(--soft)]" key={email.id}><input type="checkbox" className="h-5 w-5 shrink-0 accent-[#465fff]" aria-label={`Select email from ${email.sender}`} checked={selected.includes(email.id)} onChange={event => setSelected(items => event.target.checked ? [...items,email.id] : items.filter(id => id !== email.id))}/><button className={`shrink-0 ${email.starred ? "text-amber-400" : "text-[#98a2b3]"}`} onClick={() => setEmails(items => items.map(item => item.id === email.id ? { ...item, starred: !item.starred } : item))} aria-label={`${email.starred ? "Unstar" : "Star"} ${email.sender}`}><Star size={18} fill={email.starred ? "currentColor" : "none"}/></button><Link href="/inbox-details" className="w-20 shrink-0 truncate font-medium">{email.sender}</Link><Link href="/inbox-details" className="muted min-w-0 flex-1 truncate">{email.preview}</Link>{email.label ? <span className={`rounded-full px-2.5 py-1 text-xs ${email.label === "Important" ? "bg-red-50 text-red-500" : email.label === "Social" ? "bg-emerald-50 text-emerald-600" : "bg-violet-50 text-violet-600"}`}>{email.label}</span> : null}<time className="muted w-16 shrink-0 text-right text-xs">{email.date}</time></article>)}</div>
        <footer className="flex h-[55px] items-center justify-between border-t border-[var(--border)] px-4"><p className="muted text-sm">Showing {page} of 159</p><div className="flex gap-2"><button className="grid h-8 w-8 place-items-center rounded-lg border border-[var(--border)] disabled:opacity-40" disabled={page === 1} onClick={() => setPage(value => value - 1)} aria-label="Previous inbox page"><ChevronLeft size={16}/></button><button className="grid h-8 w-8 place-items-center rounded-lg border border-[var(--border)]" onClick={() => setPage(value => value + 1)} aria-label="Next inbox page"><ChevronRight size={16}/></button></div></footer>
      </section>
    </div>
    {compose ? <div className="fixed inset-0 z-[80] grid place-items-center bg-black/30 p-4" onMouseDown={event => { if (event.target === event.currentTarget) setCompose(false); }}><form className="panel w-full max-w-xl overflow-hidden shadow-2xl" onSubmit={sendMail} role="dialog" aria-modal="true" aria-labelledby="compose-title"><header className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><h2 id="compose-title" className="text-lg font-semibold">New Message</h2><button type="button" className="rounded-lg p-2 hover:bg-[var(--soft)]" onClick={() => setCompose(false)} aria-label="Close compose">×</button></header><div className="space-y-4 p-5"><input className="control" type="email" placeholder="To" required value={to} onChange={event => setTo(event.target.value)}/><input className="control" placeholder="Subject" value={subject} onChange={event => setSubject(event.target.value)}/><textarea className="control min-h-44" placeholder="Write your message..." required value={body} onChange={event => setBody(event.target.value)}/><div className="flex justify-end"><button className="btn btn-primary"><Send size={17}/>Send</button></div></div></form></div> : null}
  </div>;
}

function MailSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-6"><h2 className="muted mb-2 px-1 text-[11px] font-medium">{title}</h2><div className="space-y-1">{children}</div></section>; }
function MailboxButton({ item, active, onClick }: { item: { name: string; icon: typeof Inbox; count?: number }; active: boolean; onClick: () => void }) { const Icon = item.icon; return <button className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${active ? "bg-indigo-50 text-[#465fff]" : "muted hover:bg-[var(--soft)] hover:text-[var(--text)]"}`} onClick={onClick}><Icon size={18}/><span>{item.name}</span>{item.count ? <span className="ml-auto">{item.count}</span> : null}</button>; }
function LabelButton({ color, label }: { color: string; label: string }) { return <button className="muted flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-[var(--soft)]"><i className={`h-2.5 w-2.5 rounded-full ${color}`}/>{label}</button>; }
