"use client";

import { Check, ChevronDown, EllipsisVertical, SlidersHorizontal as Filter, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useCRM } from "@/lib/store";

type Period = "Monthly" | "Quarterly" | "Annually";
type OrderStatus = "Complete" | "Pending" | "Cancel";
type Order = { id:string; initials:string; customer:string; email:string; service:string; value:string; closeDate:string; status:OrderStatus };

const orders:Order[]=[
  {id:"DE124321",initials:"JD",customer:"John Doe",email:"johndoe@gmail.com",service:"Software License",value:"$18,50.34",closeDate:"2024-06-15",status:"Complete"},
  {id:"DE124322",initials:"JS",customer:"Jane Smith",email:"janesmith@gmail.com",service:"Cloud Hosting",value:"$12,99.00",closeDate:"2024-06-18",status:"Pending"},
  {id:"DE124323",initials:"MB",customer:"Michael Brown",email:"michaelbrown@gmail.com",service:"Web Domain",value:"$9,50.00",closeDate:"2024-06-20",status:"Cancel"},
  {id:"DE124324",initials:"AJ",customer:"Alice Johnson",email:"alicejohnson@gmail.com",service:"SSL Certificate",value:"$2,30.45",closeDate:"2024-06-25",status:"Pending"},
  {id:"DE124325",initials:"RL",customer:"Robert Lee",email:"robertlee@gmail.com",service:"Premium Support",value:"$15,20.00",closeDate:"2024-06-30",status:"Complete"},
];
const statisticsData=[
 {month:"Jan",income:180,expenses:40},{month:"Feb",income:190,expenses:30},{month:"Mar",income:170,expenses:48},{month:"Apr",income:160,expenses:38},
 {month:"May",income:175,expenses:52},{month:"Jun",income:165,expenses:40},{month:"Jul",income:172,expenses:70},{month:"Aug",income:205,expenses:100},
 {month:"Sep",income:228,expenses:110},{month:"Oct",income:208,expenses:120},{month:"Nov",income:239,expenses:148},{month:"Dec",income:235,expenses:140},
];
const salesCategories=[
 {name:"Affiliate Program",value:48,products:"2,040 Products",color:"#465fff"},
 {name:"Direct Buy",value:33,products:"1,402 Products",color:"#7592ff"},
 {name:"Adsense",value:19,products:"510 Products",color:"#c7d7fe"},
];

export function Dashboard(){
 const {state}=useCRM();
 const [period,setPeriod]=useState<Period>("Monthly");
 const [status,setStatus]=useState<"All"|OrderStatus>("All");
 const [filterOpen,setFilterOpen]=useState(false);
 const [selected,setSelected]=useState<string[]>([]);
 const active=state.deals.filter(d=>!["Won","Lost"].includes(d.stage));
 const won=state.deals.filter(d=>d.stage==="Won");
 const visibleOrders=useMemo(()=>status==="All"?orders:orders.filter(o=>o.status===status),[status]);
 const allSelected=visibleOrders.length>0&&visibleOrders.every(o=>selected.includes(o.id));
 const toggleAll=()=>setSelected(allSelected?selected.filter(id=>!visibleOrders.some(o=>o.id===id)):[...new Set([...selected,...visibleOrders.map(o=>o.id)])]);
 return <div className="dashboard-page space-y-6">
  <section className="grid gap-6 xl:grid-cols-3">
   <Metric value={`$${active.reduce((sum,d)=>sum+d.value,0).toLocaleString()}`} label="Active Deal" change="+20%" positive/>
   <Metric value={`$${won.reduce((sum,d)=>sum+d.value,0).toLocaleString()}`} label="Revenue Total" change="+9.0%" positive/>
   <Metric value="874" label="Closed Deals" change="-4.5%"/>
  </section>
  <section className="grid gap-6 xl:grid-cols-3">
   <article className="panel p-6 xl:col-span-2"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-[20px] font-semibold">Statistics</h2><p className="muted mt-1 text-sm">Target you’ve set for each month</p></div><div className="soft flex rounded-lg p-0.5">{(["Monthly","Quarterly","Annually"] as Period[]).map(item=><button key={item} className={`rounded-md px-3 py-2 text-[14px] leading-5 ${period===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted"}`} onClick={()=>setPeriod(item)}>{item}</button>)}</div></div><div className="mt-7 flex flex-wrap gap-x-16 gap-y-6"><Profit value={period==="Monthly"?"$212,142.12":period==="Quarterly"?"$624,876.42":"$2,416,928.20"} change="+23.2%" positive/><Profit value={period==="Monthly"?"$30,321.23":period==="Quarterly"?"$91,480.15":"$368,521.09"} change="-12.3%"/></div><div className="mt-5 h-[207px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={statisticsData} margin={{top:8,right:4,left:-24,bottom:0}}><defs><linearGradient id="income-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#465fff" stopOpacity={.24}/><stop offset="100%" stopColor="#465fff" stopOpacity={0}/></linearGradient><linearGradient id="expense-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9ab4ff" stopOpacity={.18}/><stop offset="100%" stopColor="#9ab4ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}} dy={8}/><YAxis domain={[0,250]} ticks={[0,50,100,150,200,250]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{border:"1px solid var(--border)",borderRadius:10,background:"var(--panel)"}}/><Area type="monotone" dataKey="income" stroke="#465fff" strokeWidth={2} fill="url(#income-fill)" dot={false}/><Area type="monotone" dataKey="expenses" stroke="#9ab4ff" strokeWidth={2} fill="url(#expense-fill)" dot={false}/></AreaChart></ResponsiveContainer></div></article>
   <article className="crm-estimated-revenue panel relative p-6"><CardTitle title="Estimated Revenue" subtitle="Target you’ve set for each month"/><button className="absolute right-6 top-6 rounded-lg hover:bg-[var(--soft)]" aria-label="Estimated revenue options"><EllipsisVertical size={24} className="muted"/></button><Gauge value={90}/></article>
  </section>
  <section className="grid items-start gap-6 lg:grid-cols-2">
   <article className="panel relative h-fit px-6 py-7"><CardTitle title="Sales Category"/><button className="absolute right-5 top-6 rounded-lg p-2 hover:bg-[var(--soft)]" aria-label="Sales category options"><EllipsisVertical size={19} className="muted"/></button><div className="mt-7 grid items-center gap-7 sm:grid-cols-[minmax(220px,1fr)_minmax(190px,.9fr)]"><div className="relative mx-auto h-[225px] w-full max-w-[250px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={salesCategories} dataKey="value" cx="50%" cy="50%" innerRadius={62} outerRadius={95} startAngle={90} endAngle={-270} stroke="none">{salesCategories.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip formatter={(value)=>`${value}%`}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="text-[20px] font-semibold">Total 3.5K</p><p className="mt-1 text-sm font-semibold">2450</p></div></div></div><div className="space-y-7">{salesCategories.map(item=><div key={item.name} className="flex items-start gap-3"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full" style={{background:item.color}}/><div className="min-w-0"><h3 className="whitespace-nowrap text-sm font-medium">{item.name}</h3><p className="muted mt-1 whitespace-nowrap text-sm"><span className="font-medium text-[var(--text)]">{item.value}%</span><span className="mx-2">•</span>{item.products}</p></div></div>)}</div></div></article>
   <article className="panel relative h-fit px-6 py-7"><CardTitle title="Upcoming Schedule"/><button className="absolute right-5 top-6 rounded-lg p-2 hover:bg-[var(--soft)]" aria-label="Schedule options"><EllipsisVertical size={19} className="muted"/></button><div className="mt-10 space-y-9">{state.events.slice(0,3).map((event,index)=><label key={event.id} className="grid cursor-pointer grid-cols-[24px_102px_minmax(0,1fr)] items-start gap-4"><input type="checkbox" className="mt-1 h-5 w-5 rounded-md accent-[#465fff]"/><span className="text-sm leading-5"><span className="muted block">{["Wed, 11 Jan","Fri, 15 Feb","Thu, 18 Mar"][index]}</span><span className="mt-1 block font-medium">{["09:20 AM","10:35 AM","1:15 AM"][index]}</span></span><span className="min-w-0 text-sm leading-5"><span className="block truncate font-medium">{["Business Analytics Press","Business Sprint","Customer Review Meeting"][index]}</span><small className="muted mt-2 block truncate text-xs">{["Exploring the Future of Data-Driven +6 more","Techniques from Business Sprint +2 more","Insights from the Customer Review Meeting +8 more"][index]}</small></span></label>)}</div></article>
  </section>
  <section className="panel overflow-visible">
   <header className="flex flex-wrap items-center justify-between gap-4 px-6 py-5"><h2 className="text-[20px] font-semibold">Recent Orders</h2><div className="flex gap-3"><div className="relative"><button className="btn !px-4 !py-2.5 !font-normal" onClick={()=>setFilterOpen(v=>!v)} aria-expanded={filterOpen}><Filter size={17}/>Filter<ChevronDown size={15}/></button>{filterOpen&&<div className="panel absolute right-0 z-30 mt-2 w-44 p-2 shadow-xl" role="menu">{(["All","Complete","Pending","Cancel"] as const).map(option=><button key={option} className={`block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-[var(--soft)] ${status===option?"font-semibold text-[#465fff]":""}`} onClick={()=>{setStatus(option);setFilterOpen(false)}}>{option}</button>)}</div>}</div><button className="btn !px-4 !py-2.5 !font-normal" onClick={()=>setStatus("All")}>See all</button></div></header>
   {selected.length>0&&<div className="border-y border-[var(--border)] bg-indigo-50 px-6 py-2 text-sm font-semibold text-indigo-700" aria-live="polite">{selected.length} order{selected.length===1?"":"s"} selected</div>}
   <div className="table-wrap"><table className="data-table recent-orders"><thead><tr><th><label className="flex items-center gap-3"><input type="checkbox" checked={allSelected} onChange={toggleAll}/><span>Deal ID</span></label></th><th>Customer</th><th>Product/Service</th><th>Deal Value</th><th>Close Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{visibleOrders.map(order=><tr key={order.id}><td><label className="flex items-center gap-3"><input type="checkbox" checked={selected.includes(order.id)} onChange={()=>setSelected(list=>list.includes(order.id)?list.filter(id=>id!==order.id):[...list,order.id])}/><span>{order.id}</span></label></td><td><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-indigo-100 font-semibold text-[#465fff]">{order.initials}</span><span><b className="block">{order.customer}</b><small className="muted">{order.email}</small></span></div></td><td>{order.service}</td><td className="font-normal tabular-nums">{order.value}</td><td className="tabular-nums">{order.closeDate}</td><td><OrderBadge status={order.status}/></td><td><span className="inline-grid h-9 w-9 place-items-center rounded-lg text-[var(--muted)] transition-colors hover:bg-red-50 hover:text-red-500" aria-label={`Delete ${order.id}`}><Trash2 size={18}/></span></td></tr>)}{visibleOrders.length===0&&<tr><td colSpan={7} className="muted !py-12 text-center">No orders match this filter.</td></tr>}</tbody></table></div>
  </section>
 </div>
}

function Metric({value,label,change,positive=false}:{value:string;label:string;change:string;positive?:boolean}){return <article className="crm-metric panel p-6"><p className="text-[30px] font-bold leading-[38px] tracking-[-.02em]">{value}</p><div className="mt-5 flex items-center justify-between gap-4"><p className="text-[14px] leading-5">{label}</p><div className="flex items-center gap-2"><span className={`badge ${positive?"bg-emerald-50 text-emerald-600":"bg-red-50 text-red-500"}`}>{change}</span><span className="muted text-sm">last month</span></div></div></article>}
function Profit({value,change,positive=false}:{value:string;change:string;positive?:boolean}){return <div><div className="flex items-center gap-3"><p className="text-xl font-bold leading-[30px] tracking-[-.02em]">{value}</p><span className={`badge ${positive?"bg-emerald-50 text-emerald-600":"bg-red-50 text-red-500"}`}>{change}</span></div><p className="muted mt-1 text-sm">Avg. Yearly Profit</p></div>}
function CardTitle({title,subtitle}:{title:string;subtitle?:string}){return <div><h2 className="text-[20px] font-semibold">{title}</h2>{subtitle?<p className="muted mt-1 text-sm">{subtitle}</p>:null}</div>}
function Gauge({value}:{value:number}){const arc="M 18.637 112.501 A 103.256 103.256 0 0 1 224.363 112.501";return <div><div className="relative mx-auto aspect-[243/118] w-full max-w-[380px]"><svg viewBox="0 0 243 118" className="absolute inset-0 h-full w-full" role="img" aria-label={`$${value} estimated revenue goal`}><path d={arc} fill="none" stroke="rgba(228,231,236,.85)" strokeWidth="6.854" strokeLinecap="round"/><path className="dashboard-gauge-progress" pathLength="100" d={arc} fill="none" stroke="rgba(70,95,255,.85)" strokeWidth="6.854" strokeLinecap="round" strokeDasharray={`${value} ${100-value}`}/></svg><div className="absolute inset-x-0 top-[48%] text-center"><p className="text-xs leading-4 text-[var(--muted)]">June Goals</p><p className="text-[36px] font-semibold leading-[46px] tracking-[-.02em]">${value}</p></div></div><div className="mt-6 space-y-5 border-t border-[var(--border)] pt-6"><RevenueSource label="Marketing" amount="$30,569.00" percent={85}/><RevenueSource label="Sales" amount="$20,486.00" percent={55}/></div></div>}
function RevenueSource({label,amount,percent}:{label:string;amount:string;percent:number}){return <div><p className="muted mb-2 text-sm">{label}</p><div className="flex items-center justify-between"><p className="font-semibold tabular-nums">{amount}</p><div className="flex w-full max-w-[140px] items-center gap-3"><div className="relative h-2 w-full max-w-[100px] rounded-sm bg-[var(--border)]"><span className="absolute inset-y-0 left-0 rounded-sm bg-[#465fff]" style={{width:`${percent}%`}}/></div><p className="text-sm font-medium tabular-nums">{percent}%</p></div></div></div>}
function OrderBadge({status}:{status:OrderStatus}){return <span className={`badge gap-1.5 ${status==="Complete"?"bg-emerald-50 text-emerald-600":status==="Pending"?"bg-amber-50 text-amber-600":"bg-red-50 text-red-500"}`}>{status==="Complete"?<Check size={13}/>:null}{status}</span>}
