"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Bell, Building2, CalendarDays, ChevronDown, CircleUserRound, Handshake, LayoutDashboard, Menu, Moon, PanelLeftClose, PanelLeftOpen, Search, Sun, Users, X, CheckSquare, RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useCRM } from "@/lib/store";

const links=[
  {href:"/dashboard",label:"Dashboard",icon:LayoutDashboard},
  {href:"/contacts",label:"Contacts",icon:Users},
  {href:"/companies",label:"Companies",icon:Building2},
  {href:"/deals",label:"Deals Pipeline",icon:Handshake},
  {href:"/tasks",label:"Tasks",icon:CheckSquare},
  {href:"/calendar",label:"Calendar",icon:CalendarDays},
  {href:"/profile",label:"Profile",icon:CircleUserRound},
];
export function Shell({children}:{children:React.ReactNode}){
 const path=usePathname(),router=useRouter(),{reset}=useCRM();const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[crmOpen,setCrmOpen]=useState(true),[theme,setTheme]=useState("light"),[notice,setNotice]=useState(false),[profile,setProfile]=useState(false),[query,setQuery]=useState("");const headerRef=useRef<HTMLElement>(null);
 // Theme state mirrors the no-flash script that runs before hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setTheme(document.documentElement.classList.contains("dark")?"dark":"light")},[]);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(!headerRef.current?.contains(e.target as Node)){setNotice(false);setProfile(false)}};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")setMobile(false)};document.addEventListener("keydown",esc);return()=>document.removeEventListener("keydown",esc)},[]);
 const toggleTheme=()=>{const dark=!document.documentElement.classList.contains("dark");document.documentElement.classList.toggle("dark",dark);localStorage.setItem("aarthi-theme",dark?"dark":"light");setTheme(dark?"dark":"light")};
 const search=(e:React.FormEvent)=>{e.preventDefault();if(query.trim())router.push(`/contacts?q=${encodeURIComponent(query.trim())}`)};
 const sidebar=<aside className={`fixed inset-y-0 left-0 z-[60] flex flex-col border-r border-[var(--border)] bg-[var(--panel)] transition-[width,transform] duration-200 ${collapsed?"w-[86px]":"w-[290px]"} ${mobile?"translate-x-0":"max-lg:-translate-x-full"}`} aria-label="Main navigation"><div className="flex h-[72px] items-center justify-between border-b border-[var(--border)] px-5"><Link href="/dashboard" className="flex items-center gap-3" aria-label="Aarthi CRM dashboard"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#465fff] text-lg font-bold text-white">A</span>{!collapsed&&<span><b className="block text-lg">Aarthi CRM</b><small className="muted">Customer workspace</small></span>}</Link><button className="btn !p-2 lg:hidden" onClick={()=>setMobile(false)} aria-label="Close navigation"><X size={18}/></button></div><nav className="flex-1 overflow-y-auto p-4"><p className={`muted mb-3 px-3 text-xs font-semibold uppercase tracking-widest ${collapsed?"text-center":""}`}>{collapsed?"•":"Menu"}</p><button className="mb-1 flex w-full items-center justify-between rounded-xl px-3 py-2.5 font-semibold hover:bg-[var(--soft)]" onClick={()=>setCrmOpen(v=>!v)} aria-expanded={crmOpen}><span className="flex items-center gap-3"><LayoutDashboard size={20}/>{!collapsed&&"CRM workspace"}</span>{!collapsed&&<ChevronDown size={16} className={crmOpen?"rotate-180":""}/>}</button>{crmOpen&&<div className="space-y-1">{links.map(({href,label,icon:Icon})=><Link key={href} href={href} title={collapsed?label:undefined} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${path===href?"bg-[#465fff] text-white":"text-[var(--muted)] hover:bg-[var(--soft)] hover:text-[var(--text)]"}`}><Icon size={19}/>{!collapsed&&label}</Link>)}</div>}</nav><div className="border-t border-[var(--border)] p-4"><button className="btn w-full !justify-start" onClick={()=>{if(confirm("Reset all CRM demo data?"))reset()}} title={collapsed?"Reset demo data":undefined}><RotateCcw size={17}/>{!collapsed&&"Reset demo data"}</button><button className="btn mt-2 hidden w-full !justify-start lg:flex" onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>} {!collapsed&&"Collapse sidebar"}</button></div></aside>;
 return <div>{sidebar}{mobile&&<button className="fixed inset-0 z-50 bg-black/40 lg:hidden" aria-label="Close navigation overlay" onClick={()=>setMobile(false)}/>}<div className={`min-h-screen transition-[padding] ${collapsed?"lg:pl-[86px]":"lg:pl-[290px]"}`}><header ref={headerRef} className="sticky top-0 z-40 flex h-[72px] items-center gap-3 border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--panel)_94%,transparent)] px-4 backdrop-blur md:px-6"><button className="btn !p-2.5 lg:hidden" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu size={20}/></button><form onSubmit={search} className="relative max-w-xl flex-1"><Search className="muted absolute left-3 top-1/2 -translate-y-1/2" size={18}/><input className="field !pl-10" placeholder="Search contacts…" aria-label="Global search" value={query} onChange={e=>setQuery(e.target.value)}/></form><button className="btn !p-2.5" onClick={toggleTheme} aria-label={`Switch to ${theme==="dark"?"light":"dark"} theme`}>{theme==="dark"?<Sun size={19}/>:<Moon size={19}/>}</button><div className="relative"><button className="btn !p-2.5" onClick={()=>{setNotice(v=>!v);setProfile(false)}} aria-label="Notifications"><Bell size={19}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500"/></button>{notice&&<div className="panel absolute right-0 mt-2 w-80 p-4 shadow-xl"><b>Notifications</b><p className="muted mt-2 text-sm">Nova Labs proposal is due tomorrow.</p><p className="muted mt-2 text-sm">Cloudly moved to Negotiation.</p></div>}</div><div className="relative"><button className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-[var(--soft)]" onClick={()=>{setProfile(v=>!v);setNotice(false)}} aria-label="Open profile menu"><span className="grid h-9 w-9 place-items-center rounded-full bg-indigo-100 font-bold text-indigo-700">AR</span><span className="hide-mobile text-left text-sm"><b className="block">Aarthi</b><small className="muted">CRM Specialist</small></span><ChevronDown size={16}/></button>{profile&&<div className="panel absolute right-0 mt-2 w-56 p-2 shadow-xl"><Link className="block rounded-lg px-3 py-2 hover:bg-[var(--soft)]" href="/profile">My profile</Link><button className="w-full rounded-lg px-3 py-2 text-left hover:bg-[var(--soft)]" onClick={()=>alert("Demo account — no sign out required.")}>Sign out</button></div>}</div></header><main className="mx-auto max-w-[1600px] p-4 md:p-7">{children}</main></div></div>
}
