"use client";

import { Bell, Check, Cog, Instagram, Linkedin } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

const Frame=({children}:{children:React.ReactNode})=><main className="auth-grid relative grid min-h-[100dvh] place-items-center overflow-hidden bg-[#f8f9fc] px-5 py-12 text-[#1d2939]"><div className="relative z-10 w-full text-center">{children}</div><footer className="absolute bottom-4 left-0 right-0 text-center text-sm text-slate-500">© 2026 - Aarthi CRM</footer></main>;
const Home=()=> <Link href="/dashboard" className="mt-7 inline-flex h-12 items-center rounded-lg border border-slate-300 bg-white px-5 font-medium shadow-sm hover:bg-slate-50">Back to Home Page</Link>;
const Face=()=> <span className="relative mx-3 inline-block h-[150px] w-[160px] rounded-[36px] border-[22px] border-[#465fff] align-middle before:absolute before:left-8 before:top-5 before:h-6 before:w-6 before:rounded-sm before:bg-[#465fff] after:absolute after:right-8 after:top-5 after:h-6 after:w-6 after:rounded-sm after:bg-[#465fff]"><i className="absolute bottom-7 left-1/2 h-6 w-16 -translate-x-1/2 border-x-[14px] border-b-[14px] border-[#465fff]"/></span>;

export function ErrorPage({code}:{code:"404"|"500"|"503"}){return <Frame><h1 className="text-[68px] font-bold leading-none">ERROR</h1><div className="mt-8 flex items-center justify-center text-[190px] font-black leading-none tracking-[-.08em] text-[#465fff]"><span>{code[0]}</span><Face/><span>{code[2]}</span></div><p className="mt-8 text-lg">We can&apos;t seem to find the page you are looking for!</p><Home/></Frame>}
export function MaintenancePage(){return <Frame><div className="mx-auto flex h-48 w-56 items-end justify-center text-[#465fff]"><Cog className="animate-[spin_12s_linear_infinite]" size={120}/><Cog className="mb-24 -ml-5" size={62}/></div><h1 className="mt-5 text-[64px] font-bold tracking-wide">MAINTENANCE</h1><p className="mx-auto mt-6 max-w-xl text-lg leading-7">Our Site is Currently under maintenance We will be back Shortly<br/>Thank You For Patience</p><Home/></Frame>}
export function SuccessPage(){return <Frame><span className="mx-auto grid h-32 w-32 place-items-center rounded-[38px] bg-[#465fff] text-white [clip-path:polygon(50%_0,61%_12%,78%_9%,86%_25%,100%_33%,94%_50%,100%_67%,84%_76%,77%_93%,59%_90%,50%_100%,38%_89%,21%_94%,14%_77%,0_67%,6%_49%,0_32%,16%_24%,23%_7%,40%_11%)]"><Check size={68} strokeWidth={4}/></span><h1 className="mt-8 text-[68px] font-bold tracking-wide">SUCCESS !</h1><p className="mx-auto mt-5 max-w-xl text-lg leading-7">Awesome! your message has been sent successfully, Our support<br className="hidden sm:block"/> team will get back to you as soon as possible.</p><Home/></Frame>}
export function ComingSoonPage(){const [email,setEmail]=useState(""),[sent,setSent]=useState(false),[time,setTime]=useState(0);useEffect(()=>{const id=setInterval(()=>setTime(value=>value+1),1000);return()=>clearInterval(id)},[]);const two=(n:number)=>String(n).padStart(2,"0");return <Frame><div className="mx-auto flex items-center justify-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#465fff] text-white font-bold">|||</span><b className="text-2xl">Aarthi CRM</b></div><h1 className="mt-9 text-[62px] font-bold">Coming Soon</h1><p className="mx-auto mt-4 max-w-xl text-base leading-6 text-slate-600">Our website is currently under construction, enter your email id to<br className="hidden sm:block"/> get latest updates and notifications about the website.</p><p className="mt-10 text-[48px] font-semibold tracking-wider text-[#465fff]">00 : 00 : {two(Math.floor(time/60)%60)} : {two(time%60)}</p><p className="mt-2 text-slate-600">0 days left</p><p className="mt-10">Don&apos;t want to miss update? Subscribe now</p><form className="mx-auto mt-5 flex max-w-[455px] gap-3" onSubmit={event=>{event.preventDefault();setSent(true)}}><input className="h-12 flex-1 rounded-lg border border-slate-300 bg-white px-4" type="email" placeholder="Email address" required value={email} onChange={event=>setEmail(event.target.value)}/><button className="flex h-12 items-center gap-2 rounded-lg bg-[#1d2939] px-5 text-white"><Bell size={18}/>Notify Me</button></form>{sent&&<p className="mt-3 text-emerald-600">You&apos;ll be notified at launch.</p>}<p className="mt-10 text-lg text-slate-600">Follow Us On</p><div className="mt-5 flex justify-center gap-5 text-slate-600"><b>f</b><b>𝕏</b><Linkedin size={19}/><Instagram size={19}/></div></Frame>}
