"use client";

import { Modal } from "@/components/modal";
import { ChevronDown, ChevronRight, MoreHorizontal, Plus, Settings, X } from "lucide-react";
import { useEffect, useState } from "react";

type Integration = { name: string; description: string; mark: string; color: string; connected: boolean };
const seed: Integration[] = [
  { name: "Mailchimp", mark: "M", color: "bg-amber-300 text-black", connected: true, description: "Connect Mailchimp to streamline your email marketing—automate campaigns." },
  { name: "Google Meet", mark: "▶", color: "bg-emerald-500 text-white", connected: false, description: "Connect your Google Meet account for seamless video conferencing." },
  { name: "Zoom", mark: "▰", color: "bg-blue-500 text-white", connected: false, description: "Integrate Zoom to streamline your virtual meetings and team collaborations" },
  { name: "Loom", mark: "✺", color: "bg-violet-100 text-violet-600", connected: false, description: "Integrate Loom to easily record, share, and manage video messages" },
  { name: "Linear", mark: "◩", color: "bg-indigo-600 text-white", connected: false, description: "Integrate Linear to manage issues, track progress, and streamline your team’s." },
  { name: "Gmail", mark: "M", color: "bg-red-50 text-red-500", connected: false, description: "Integrate Gmail to send, receive, and manage emails directly from your workspace." },
  { name: "Trello", mark: "Ⅱ", color: "bg-sky-500 text-white", connected: false, description: "Capture, organize, and tackle your to-dos from anywhere." },
  { name: "Notion", mark: "N", color: "bg-black text-white", connected: false, description: "Capture, organize, and tackle your to-dos from anywhere." },
  { name: "Jira", mark: "◆", color: "bg-blue-600 text-white", connected: false, description: "Track issues and manage projects with ease and full team visibility." },
];

export default function IntegrationsPage() {
  const [items, setItems] = useState(seed), [addOpen, setAddOpen] = useState(false), [details, setDetails] = useState<Integration | null>(null), [settings, setSettings] = useState<Integration | null>(null), [menu, setMenu] = useState<string | null>(null), [app, setApp] = useState(""), [clientId, setClientId] = useState(""), [clientSecret, setClientSecret] = useState(""), [authUri, setAuthUri] = useState("");
  useEffect(() => { if (!addOpen) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setAddOpen(false); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [addOpen]);
  const toggle = (target: string) => setItems(current => current.map(item => item.name === target ? { ...item, connected: !item.connected } : item));
  const add = (event: React.FormEvent) => { event.preventDefault(); if (!app) return; const existing = seed.find(item => item.name === app); setItems(current => current.some(item => item.name === app) ? current.map(item => item.name === app ? { ...item, connected: true } : item) : [...current, existing ?? { name: app, description: "Connect this integration to your workspace.", mark: app[0], color: "bg-indigo-50 text-[#465fff]", connected: true }]); setApp(""); setClientId(""); setClientSecret(""); setAuthUri(""); setAddOpen(false); };
  return <div className="integrations-page space-y-6">
    <header className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-xl font-semibold leading-6">Integrations</h1><div className="ml-auto flex items-center gap-5"><nav className="muted hidden items-center gap-2 text-sm sm:flex"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Integrations</span></nav><button className="btn btn-primary h-12 !px-5" onClick={() => setAddOpen(true)}><Plus size={18}/>Add New Integration</button></div></header>
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(item => <article className="panel overflow-visible" key={item.name}><div className="relative min-h-[193px] p-5"><div className="flex items-start justify-between"><Logo item={item}/><button className="rounded-lg p-1 hover:bg-[var(--soft)]" onClick={() => setMenu(menu === item.name ? null : item.name)} aria-label={`${item.name} options`}><MoreHorizontal className="muted" size={19}/></button></div>{menu === item.name ? <div className="panel absolute right-4 top-11 z-20 w-28 p-1 shadow-xl"><button className="w-full rounded-md px-3 py-2 text-left text-sm hover:bg-[var(--soft)]" onClick={() => { setDetails(item); setMenu(null); }}>Details</button><button className="w-full rounded-md px-3 py-2 text-left text-sm text-red-500 hover:bg-red-50" onClick={() => setItems(current => current.filter(entry => entry.name !== item.name))}>Remove</button></div> : null}<h2 className="mt-7 text-lg font-semibold">{item.name}</h2><p className="muted mt-3 min-h-[48px] text-sm leading-5">{item.description}</p></div><footer className="flex h-[84px] items-center gap-3 border-t border-[var(--border)] px-5"><button className="grid h-11 w-11 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" onClick={() => setSettings(item)} aria-label={`${item.name} settings`}><Settings size={19}/></button><button className="btn h-11 !px-4" onClick={() => setDetails(item)}>Details</button><button role="switch" aria-checked={item.connected} aria-label={`${item.connected ? "Disconnect" : "Connect"} ${item.name}`} onClick={() => toggle(item.name)} className={`relative ml-auto h-6 w-11 rounded-full transition ${item.connected ? "bg-[#465fff]" : "bg-[#e4e7ec]"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${item.connected ? "left-6" : "left-1"}`}/></button></footer></article>)}</section>
    {addOpen ? <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-900/25 p-4 backdrop-blur-[2px]" onMouseDown={event => { if (event.target === event.currentTarget) setAddOpen(false); }}><section className="max-h-[92vh] w-full max-w-[560px] overflow-y-auto rounded-[24px] bg-[var(--panel)] p-10 shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="new-integration-title"><header className="flex items-start justify-between"><div><h2 id="new-integration-title" className="text-base font-semibold">New integration</h2><p className="muted mt-2 text-sm">Set up an integration and add a brief explanation for the team.</p></div><button className="soft -mr-4 -mt-4 grid h-11 w-11 place-items-center rounded-full" onClick={() => setAddOpen(false)} aria-label="Close dialog"><X className="muted" size={21}/></button></header><form className="mt-8 space-y-5" onSubmit={add}><Field label="Select App"><div className="relative"><select className="control appearance-none" required value={app} onChange={event => setApp(event.target.value)}><option value="">Select Option</option>{["Google Meet","Mailchimp","Zoom","Loom","Gmail"].map(item => <option key={item}>{item}</option>)}</select><ChevronDown className="muted pointer-events-none absolute right-4 top-1/2 -translate-y-1/2" size={18}/></div></Field><Field label="Client ID"><input className="control" placeholder="Enter client ID here" required value={clientId} onChange={event => setClientId(event.target.value)}/></Field><Field label="Client Secret"><input className="control" type="password" placeholder="Enter client secret here" required value={clientSecret} onChange={event => setClientSecret(event.target.value)}/></Field><Field label="Authentication base URI"><input className="control" type="url" placeholder="Paste URL here" required value={authUri} onChange={event => setAuthUri(event.target.value)}/></Field><p className="muted text-sm leading-5">Paste the full URI, and we’ll automatically pull out and show only the subdomain for quick reference.</p><div className="grid grid-cols-2 gap-3 pt-3"><button type="button" className="btn h-12" onClick={() => setAddOpen(false)}>Close</button><button className="btn btn-primary h-12">Add Integration</button></div></form></section></div> : null}
    <Modal open={Boolean(details)} title={details?.name ?? "Integration Details"} onClose={() => setDetails(null)}>{details ? <div><Logo item={details}/><p className="muted mt-5 leading-6">{details.description}</p><p className="mt-5 text-sm font-medium">Status: <span className={details.connected ? "text-emerald-600" : "muted"}>{details.connected ? "Connected" : "Not connected"}</span></p><button className="btn btn-primary mt-6 w-full" onClick={() => { toggle(details.name); setDetails(null); }}>{details.connected ? "Disconnect" : "Connect Integration"}</button></div> : null}</Modal>
    <Modal open={Boolean(settings)} title={`${settings?.name ?? "Integration"} Settings`} onClose={() => setSettings(null)}><div className="space-y-5"><Field label="Workspace"><input className="control" defaultValue="Aarthi CRM"/></Field><Field label="Notification preference"><select className="control"><option>All activity</option><option>Important updates only</option><option>None</option></select></Field><button className="btn btn-primary w-full" onClick={() => setSettings(null)}>Save Settings</button></div></Modal>
  </div>;
}

function Logo({ item }: { item: Integration }) { return <span className={`grid h-9 w-9 place-items-center rounded-lg text-lg font-bold ${item.color}`}>{item.mark}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
