"use client";

import { useMemo, useState } from "react";
import { AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { TimedArea as Area } from "@/components/ui/timed-charts";
import { ArrowDown, ArrowUp, EllipsisVertical, Search } from "lucide-react";

const summary=[{symbol:"AAPL",name:"Apple, Inc",mark:"●",color:"#243447",price:"$1,232.00",change:"11.01%"},{symbol:"PYPL",name:"Paypal, Inc",mark:"P",color:"#2b5bd7",price:"$965.00",change:"9.05%",down:true},{symbol:"TSLA",name:"Tesla, Inc",mark:"T",color:"#e82127",price:"$1,232.00",change:"11.01%"},{symbol:"AMZN",name:"Amazon.com, Inc",mark:"a",color:"#ff9900",price:"$2,567.00",change:"11.01%"}];
const basePerformance=[30.8,30.5,31.2,31.1,31.7,31.4,32.2,31.8,32.4,32.1,32.8,32.6,31.5,33.2,32.8,33.5,32.9,33.7,33.1,33.8,33.4,32.7,32.2,33.1,32.5,32.9,32.1,32.7,32.3,33.0].map((value,index)=>({day:index+1,value}));
const trending=[summary[2],summary[0],{symbol:"SPOT",name:"Spotify, Inc",mark:"S",color:"#1ed760",price:"$192.53",change:"1.01%"},summary[1],summary[3]];
const dividends=[{m:"Jan",v:155},{m:"Feb",v:380},{m:"Mar",v:190},{m:"Apr",v:295},{m:"May",v:180},{m:"Jun",v:190}];
const watch=[{symbol:"AAPL",name:"Apple, Inc",mark:"●",color:"#243447",price:"$4,008.65",change:"11.01%"},{symbol:"SPOT",name:"Spotify.com",mark:"S",color:"#1ed760",price:"$11,689.00",change:"9.48%"},{symbol:"ABNB",name:"Airbnb, Inc",mark:"A",color:"#ff5a60",price:"$32,227.00",change:"0.29%",down:true},{symbol:"ENVT",name:"Envato, Inc",mark:"E",color:"#82db49",price:"$13,895.00",change:"3.79%"},{symbol:"QIWI",name:"qiwi.com, Inc",mark:"Q",color:"#ff9700",price:"$4,008.65",change:"4.52%",down:true}];
const transactions=[{name:"Bought PYPL",symbol:"P",color:"#2b5bd7",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Success"},{name:"Bought AAPL",symbol:"●",color:"#243447",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Pending"},{name:"Sell KKST",symbol:"K",color:"#7c3aed",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Success"},{name:"Bought FB",symbol:"f",color:"#1877f2",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Success"},{name:"Sell AMZN",symbol:"a",color:"#ff9900",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Failed"}];

export default function StocksPage(){const [period,setPeriod]=useState("Monthly");const [trend,setTrend]=useState(0);const [query,setQuery]=useState("");const factor=period==="Quarterly"?1.035:period==="Annually"?1.08:1;const performance=useMemo(()=>basePerformance.map(x=>({...x,value:Number((x.value*factor).toFixed(2))})),[factor]);const rows=transactions.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));return <div className="stocks-page space-y-6">
  <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4" aria-label="Stock summary">{summary.map(stock=><StockSummary key={stock.symbol} stock={stock}/>)}</section>
  <section className="grid gap-6 xl:grid-cols-12">
    <div className="min-w-0 space-y-6 xl:col-span-8">
    <article className="panel p-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div><h2 className="text-xl font-semibold">Portfolio Performance</h2><p className="muted mt-1 text-sm">Here is your performance stats of each month</p></div>
        <div className="soft inline-flex rounded-lg p-0.5">{["Monthly","Quarterly","Annually"].map(item=><button className={`rounded-md px-3 py-1.5 text-[13px] leading-5 ${period===item?"bg-[var(--panel)] font-medium shadow-sm":"muted"}`} aria-pressed={period===item} onClick={()=>setPeriod(item)} key={item}>{item}</button>)}</div>
      </div>
      <div className="mt-6 h-[278px]"><PerformanceChart data={performance}/></div>
    </article>
    <article className="panel min-h-[294px] overflow-hidden p-6">
      <div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">Trending Stocks</h2><div className="flex gap-2"><CircleButton label="Previous stock" disabled={trend===0} onClick={()=>setTrend(v=>Math.max(0,v-1))}><span className="h-0 w-0 border-y-[5px] border-r-[6px] border-y-transparent border-r-[#98a2b3]" aria-hidden="true"/></CircleButton><CircleButton label="Next stock" disabled={trend===trending.length-2} onClick={()=>setTrend(v=>Math.min(trending.length-2,v+1))}><span className="h-0 w-0 border-y-[5px] border-l-[6px] border-y-transparent border-l-[#344054] dark:border-l-[#d0d5dd]" aria-hidden="true"/></CircleButton></div></div>
      <div className="overflow-hidden"><div className={`stocks-slider-track stocks-slide-${trend} flex gap-5`}>{trending.map(stock=><div className="soft w-full shrink-0 basis-full rounded-2xl p-5 sm:basis-[calc((100%-20px)/2)]" key={stock.symbol}><StockRow stock={stock} large/><div className="mt-5 grid grid-cols-2 gap-3"><button className="btn h-11 justify-center !rounded-lg !px-4 !py-2.5 !text-sm !font-medium !transition-none hover:!transform-none bg-[var(--panel)]">Short Stock</button><button className="btn btn-primary h-11 justify-center !rounded-lg !px-4 !py-2.5 !text-sm !font-medium !transition-none hover:!transform-none">Buy Stock</button></div></div>)}</div></div>
    </article>
    </div>
    <div className="min-w-0 space-y-6 xl:col-span-4 xl:flex xl:h-full xl:flex-col xl:gap-6 xl:space-y-0">
    <article className="panel p-6"><CardTitle title="Dividend"/><DividendChart/></article>
    <article className="panel h-fit overflow-hidden p-6 xl:flex xl:min-h-0 xl:flex-1 xl:flex-col"><CardTitle title="My Watchlist"/><div className="stocks-watchlist mt-3 h-[250px] max-h-[250px] shrink-0 divide-y divide-[var(--border)] overflow-y-auto overscroll-contain pr-2" aria-label="Scrollable stock watchlist">{watch.map(stock=><StockRow stock={stock} key={stock.symbol}/>)}</div></article>
    </div>
  </section>
  <article className="panel min-w-0 max-w-full overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 p-6"><h2 className="text-xl font-semibold">Latest Transactions</h2><label className="relative block max-w-full"><Search className="muted absolute left-3 top-1/2 -translate-y-1/2" size={18} aria-hidden="true"/><span className="sr-only">Search transactions</span><input className="field !w-64 max-w-full !pl-10" name="stock-transaction-search" autoComplete="off" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/></label></header><div className="table-wrap max-w-full"><table className="data-table"><thead><tr><th>Name</th><th>Date</th><th>Price</th><th>Category</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.name}><td><div className="flex min-w-36 items-center gap-3"><Logo mark={row.symbol} color={row.color}/><span className="font-normal">{row.name}</span></div></td><td>{row.date}</td><td className="font-normal tabular-nums">{row.price}</td><td>{row.category}</td><td><Status value={row.status}/></td></tr>)}</tbody></table></div></article>
 </div>}

function StockSummary({stock}:{stock:(typeof summary)[number]}){return <article className="panel h-fit p-5"><div className="flex items-center gap-3"><Logo mark={stock.mark} color={stock.color}/><div className="min-w-0"><h2 className="truncate font-semibold">{stock.name}</h2><p className="muted truncate text-xs">{stock.name}</p></div></div><div className="mt-5 flex items-end justify-between gap-3"><p className="text-2xl font-semibold tabular-nums">{stock.price}</p><Change value={stock.change} down={stock.down}/></div></article>}
function DividendChart(){return <figure className="mt-4 grid h-[171px] grid-cols-[30px_minmax(0,1fr)] gap-2"><figcaption className="sr-only">Dividend values from January to June. Focus or hover a bar to see its value.</figcaption><div className="muted flex h-[142px] flex-col justify-between pb-0.5 text-right text-[11px] tabular-nums"><span>400</span><span>300</span><span>200</span><span>100</span><span>0</span></div><div className="relative min-w-0"><div className="pointer-events-none absolute inset-x-0 top-1 h-[138px] bg-[repeating-linear-gradient(to_bottom,transparent_0,transparent_33px,var(--border)_34px,var(--border)_35px)]"/><div className="absolute inset-x-0 top-1 flex h-[138px] items-end justify-around gap-2 px-1">{dividends.map(item=>{const height=Math.max(4,item.v/400*100);return <button type="button" className="group relative flex h-full min-w-0 flex-1 items-end justify-center rounded-sm" aria-label={`${item.m} dividend: ${item.v}`} key={item.m}><span className="w-full max-w-[22px] rounded-t-[4px] bg-[#465fff] transition-[filter,transform] duration-150 group-hover:brightness-110 group-hover:scale-x-110 group-focus-visible:brightness-110 group-focus-visible:scale-x-110" style={{height:`${height}%`}}/><span className="pointer-events-none absolute left-1/2 z-10 -translate-x-1/2 rounded-md bg-[#101828] px-2 py-1 text-[11px] leading-4 text-white opacity-0 shadow-lg transition-opacity duration-150 group-hover:opacity-100 group-focus-visible:opacity-100" style={{bottom:`calc(${height}% + 7px)`}}>{item.v}</span></button>})}</div><div className="muted absolute inset-x-0 bottom-0 flex justify-around px-1 text-[11px]">{dividends.map(item=><span className="min-w-0 flex-1 text-center" key={item.m}>{item.m}</span>)}</div></div></figure>}
function Logo({mark,color}:{mark:string;color:string}){return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-lg font-bold text-white" style={{background:color}} aria-hidden="true">{mark}</span>}
function Change({value,down=false}:{value:string;down?:boolean}){return <span className={`badge ${down?"bg-red-50 text-red-500":"bg-emerald-50 text-emerald-600"}`}>{down?<ArrowDown size={14} strokeWidth={1.8} aria-hidden="true"/>:<ArrowUp size={14} strokeWidth={1.8} aria-hidden="true"/>} {value}</span>}
function CardTitle({title}:{title:string}){return <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical className="muted" size={20} aria-hidden="true"/></button></div>}
function CircleButton({label,onClick,children,disabled=false}:{label:string;onClick:()=>void;children:React.ReactNode;disabled?:boolean}){return <button aria-label={label} disabled={disabled} onClick={onClick} className="grid h-10 w-10 place-items-center rounded-full border border-[var(--border)] hover:bg-[var(--soft)] disabled:cursor-not-allowed disabled:opacity-45">{children}</button>}
function StockRow({stock,large=false}:{stock:{symbol:string;name:string;mark:string;color:string;price:string;change:string;down?:boolean};large?:boolean}){return <div className={`flex items-center gap-3 ${large?"border-b border-[var(--border)] pb-5":"py-2.5"}`}><Logo mark={stock.mark} color={stock.color}/><div><p className="font-semibold">{stock.symbol}</p><p className="muted text-xs">{stock.name}</p></div><div className="ml-auto text-right"><p className="font-semibold tabular-nums">{stock.price}</p>{large?<Change value={stock.change} down={stock.down}/>:<span className={`mt-1 flex items-center justify-end gap-1 text-xs font-semibold ${stock.down?"text-red-500":"text-emerald-600"}`}>{stock.down?<ArrowDown size={13} strokeWidth={1.8} aria-hidden="true"/>:<ArrowUp size={13} strokeWidth={1.8} aria-hidden="true"/>} {stock.change}</span>}</div></div>}
function PerformanceChart({data}:{data:{day:number;value:number}[]}){return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-10,right:8}}><defs><linearGradient id="stock-performance" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#465fff" stopOpacity=".25"/><stop offset="1" stopColor="#465fff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" ticks={[5,15,25]} tickFormatter={v=>v===5?"Jun ’25":v===15?"Jul ’25":"Aug ’25"} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[28,40]} ticks={[28,30,32,34,36,38,40]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Area animationDuration={1800} animationEasing="ease-in-out" type="linear" dataKey="value" stroke="#465fff" strokeWidth={1.6} fill="url(#stock-performance)" dot={false}/></AreaChart></ResponsiveContainer>}
function Status({value}:{value:string}){return <span className={`badge ${value==="Success"?"bg-emerald-50 text-emerald-600":value==="Pending"?"bg-amber-50 text-amber-600":"bg-red-50 text-red-500"}`}>{value}</span>}
