"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ChevronLeft, ChevronRight, EllipsisVertical, Search, TrendingDown, TrendingUp } from "lucide-react";

const summary=[{symbol:"AAPL",name:"Apple, Inc",mark:"●",color:"#243447",price:"$1,232.00",change:"11.01%"},{symbol:"PYPL",name:"Paypal, Inc",mark:"P",color:"#2b5bd7",price:"$965.00",change:"9.05%",down:true},{symbol:"TSLA",name:"Tesla, Inc",mark:"T",color:"#e82127",price:"$1,232.00",change:"11.01%"},{symbol:"AMZN",name:"Amazon.com, Inc",mark:"a",color:"#ff9900",price:"$2,567.00",change:"11.01%"}];
const basePerformance=[30.8,30.5,31.2,31.1,31.7,31.4,32.2,31.8,32.4,32.1,32.8,32.6,31.5,33.2,32.8,33.5,32.9,33.7,33.1,33.8,33.4,32.7,32.2,33.1,32.5,32.9,32.1,32.7,32.3,33.0].map((value,index)=>({day:index+1,value}));
const trending=[summary[2],summary[0],{symbol:"SPOT",name:"Spotify, Inc",mark:"S",color:"#1ed760",price:"$192.53",change:"1.01%"},summary[1],summary[3]];
const dividends=[{m:"Jan",v:155},{m:"Feb",v:380},{m:"Mar",v:190},{m:"Apr",v:295},{m:"May",v:180},{m:"Jun",v:190}];
const watch=[{symbol:"AAPL",name:"Apple, Inc",mark:"●",color:"#243447",price:"$4,008.65",change:"11.01%"},{symbol:"SPOT",name:"Spotify.com",mark:"S",color:"#1ed760",price:"$11,689.00",change:"9.48%"},{symbol:"ABNB",name:"Airbnb, Inc",mark:"A",color:"#ff5a60",price:"$32,227.00",change:"0.29%",down:true},{symbol:"ENVT",name:"Envato, Inc",mark:"E",color:"#82db49",price:"$13,895.00",change:"3.79%"},{symbol:"QIWI",name:"qiwi.com, Inc",mark:"Q",color:"#ff9700",price:"$4,008.65",change:"4.52%",down:true}];
const transactions=[{name:"Bought PYPL",symbol:"P",color:"#2b5bd7",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Success"},{name:"Bought AAPL",symbol:"●",color:"#243447",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Pending"},{name:"Sell KKST",symbol:"K",color:"#7c3aed",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Success"},{name:"Bought FB",symbol:"f",color:"#1877f2",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Success"},{name:"Sell AMZN",symbol:"a",color:"#ff9900",date:"Nov 23, 01:00 PM",price:"$2,567.88",category:"Finance",status:"Failed"}];

export default function StocksPage(){const [period,setPeriod]=useState("Monthly");const [trend,setTrend]=useState(0);const [query,setQuery]=useState("");const factor=period==="Quarterly"?1.035:period==="Annually"?1.08:1;const performance=useMemo(()=>basePerformance.map(x=>({...x,value:Number((x.value*factor).toFixed(2))})),[factor]);const rows=transactions.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));return <div className="stocks-page space-y-6">
  <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4" aria-label="Stock summary">{summary.map(stock=><StockSummary key={stock.symbol} stock={stock}/>)}</section>
  <section className="grid gap-6 xl:grid-cols-12">
    <div className="min-w-0 space-y-6 xl:col-span-8">
    <article className="panel p-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div><h2 className="text-xl font-semibold">Portfolio Performance</h2><p className="muted mt-1 text-sm">Here is your performance stats of each month</p></div>
        <div className="soft inline-flex rounded-lg p-1">{["Monthly","Quarterly","Annually"].map(item=><button className={`rounded-md px-4 py-2 text-sm ${period===item?"bg-[var(--panel)] font-semibold shadow-sm":"muted"}`} aria-pressed={period===item} onClick={()=>setPeriod(item)} key={item}>{item}</button>)}</div>
      </div>
      <div className="mt-6 h-[278px]"><PerformanceChart data={performance}/></div>
    </article>
    <article className="panel min-h-[294px] overflow-hidden p-6">
      <div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">Trending Stocks</h2><div className="flex gap-2"><CircleButton label="Previous stock" onClick={()=>setTrend(v=>(v-1+trending.length)%trending.length)}><ChevronLeft size={16}/></CircleButton><CircleButton label="Next stock" onClick={()=>setTrend(v=>(v+1)%trending.length)}><ChevronRight size={16}/></CircleButton></div></div>
      <div className="grid gap-5 sm:grid-cols-2">{[trending[trend],trending[(trend+1)%trending.length]].map((stock,index)=><div className={`${index===1?"hidden sm:block":""} soft rounded-2xl p-5`} key={`${stock.symbol}-${index}`}><StockRow stock={stock} large/><div className="mt-5 grid grid-cols-2 gap-3"><button className="btn justify-center bg-[var(--panel)]">Short Stock</button><button className="btn btn-primary justify-center">Buy Stock</button></div></div>)}</div>
    </article>
    </div>
    <div className="min-w-0 space-y-6 xl:col-span-4">
    <article className="panel p-6"><CardTitle title="Dividend"/><div className="mt-4 h-[171px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={dividends} margin={{left:-22,right:4}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="v" fill="#465fff" radius={[4,4,0,0]} maxBarSize={14}/></BarChart></ResponsiveContainer></div></article>
    <article className="panel h-[479px] overflow-hidden p-6"><CardTitle title="My Watchlist"/><div className="stocks-watchlist mt-3 divide-y divide-[var(--border)]">{watch.map(stock=><StockRow stock={stock} key={stock.symbol}/>)}</div></article>
    </div>
  </section>
  <article className="panel min-w-0 max-w-full overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-4 p-6"><h2 className="text-xl font-semibold">Latest Transactions</h2><label className="relative block max-w-full"><Search className="muted absolute left-3 top-1/2 -translate-y-1/2" size={17}/><span className="sr-only">Search transactions</span><input className="field !w-64 max-w-full !pl-10" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/></label></header><div className="table-wrap max-w-full"><table className="data-table"><thead><tr><th>Name</th><th>Date</th><th>Price</th><th>Category</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.name}><td><div className="flex min-w-36 items-center gap-3"><Logo mark={row.symbol} color={row.color}/><span className="font-normal">{row.name}</span></div></td><td>{row.date}</td><td className="font-normal tabular-nums">{row.price}</td><td>{row.category}</td><td><Status value={row.status}/></td></tr>)}</tbody></table></div></article>
 </div>}

function StockSummary({stock}:{stock:(typeof summary)[number]}){return <article className="panel min-h-[164px] p-6"><div className="flex items-center gap-3"><Logo mark={stock.mark} color={stock.color}/><div><h2 className="font-semibold">{stock.name}</h2><p className="muted text-xs">{stock.name}</p></div></div><div className="mt-7 flex items-end justify-between gap-3"><p className="text-2xl font-semibold tabular-nums">{stock.price}</p><Change value={stock.change} down={stock.down}/></div></article>}
function Logo({mark,color}:{mark:string;color:string}){return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-lg font-bold text-white" style={{background:color}}>{mark}</span>}
function Change({value,down=false}:{value:string;down?:boolean}){return <span className={`badge ${down?"bg-red-50 text-red-500":"bg-emerald-50 text-emerald-600"}`}>{down?<TrendingDown size={13}/>:<TrendingUp size={13}/>} {value}</span>}
function CardTitle({title}:{title:string}){return <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button className="rounded-lg p-2 hover:bg-[var(--soft)]" aria-label={`${title} options`}><EllipsisVertical size={18}/></button></div>}
function CircleButton({label,onClick,children}:{label:string;onClick:()=>void;children:React.ReactNode}){return <button aria-label={label} onClick={onClick} className="grid h-9 w-9 place-items-center rounded-full border border-[var(--border)] hover:bg-[var(--soft)]">{children}</button>}
function StockRow({stock,large=false}:{stock:{symbol:string;name:string;mark:string;color:string;price:string;change:string;down?:boolean};large?:boolean}){return <div className={`flex items-center gap-3 ${large?"border-b border-[var(--border)] pb-5":"py-2.5"}`}><Logo mark={stock.mark} color={stock.color}/><div><p className="font-semibold">{stock.symbol}</p><p className="muted text-xs">{stock.name}</p></div><div className="ml-auto text-right"><p className="font-semibold tabular-nums">{stock.price}</p>{large?<Change value={stock.change} down={stock.down}/>:<span className={`mt-1 flex items-center justify-end gap-1 text-xs font-semibold ${stock.down?"text-red-500":"text-emerald-600"}`}>{stock.down?<TrendingDown size={12}/>:<TrendingUp size={12}/>} {stock.change}</span>}</div></div>}
function PerformanceChart({data}:{data:{day:number;value:number}[]}){return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-10,right:8}}><defs><linearGradient id="stock-performance" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#465fff" stopOpacity=".25"/><stop offset="1" stopColor="#465fff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" ticks={[5,15,25]} tickFormatter={v=>v===5?"Jun ’25":v===15?"Jul ’25":"Aug ’25"} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[28,40]} ticks={[28,30,32,34,36,38,40]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><Tooltip contentStyle={{background:"var(--panel)",border:"1px solid var(--border)",borderRadius:10}}/><Area type="linear" dataKey="value" stroke="#465fff" strokeWidth={1.6} fill="url(#stock-performance)" dot={false}/></AreaChart></ResponsiveContainer>}
function Status({value}:{value:string}){return <span className={`badge ${value==="Success"?"bg-emerald-50 text-emerald-600":value==="Pending"?"bg-amber-50 text-amber-600":"bg-red-50 text-red-500"}`}>{value}</span>}
