"use client";

import { ArrowRight, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, LockKeyhole, Mail, Send, UserRound } from "lucide-react";
import { useMemo, useState } from "react";

export default function FormLayoutPage() {
  const [remember, setRemember] = useState(false), [membership, setMembership] = useState("Free"), [message, setMessage] = useState("");
  const submit = (label: string) => (event: React.FormEvent) => { event.preventDefault(); setMessage(`${label} submitted successfully.`); };
  return <div className="space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">Form Layout</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Form Layout</span></nav></header>
    {message ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700" role="status">{message}</div> : null}
    <div className="grid items-start gap-6 xl:grid-cols-2">
      <div className="space-y-6">
        <Card title="Basic Form"><form className="space-y-6" onSubmit={submit("Basic form")}><div className="grid gap-6 sm:grid-cols-2"><input className="control" placeholder="Name" aria-label="Name"/><input className="control" type="email" placeholder="Email address" aria-label="Email address"/></div><input className="control" type="password" placeholder="Password" aria-label="Password"/><input className="control" type="password" placeholder="Confirm Password" aria-label="Confirm Password"/><button className="btn btn-primary h-11 w-full">Submit</button></form></Card>
        <Card title="Example Form"><form className="space-y-6" onSubmit={submit("Message")}><div className="grid gap-6 sm:grid-cols-2"><Field label="First Name"><input className="control" name="first-name" autoComplete="given-name" placeholder="Enter first name" required/></Field><Field label="Last Name"><input className="control" name="last-name" autoComplete="family-name" placeholder="Enter last name" required/></Field></div><Field label="Email"><input className="control" name="email" type="email" autoComplete="email" placeholder="Enter email address" required/></Field><Field label="Subject"><Select options={["Option 1","Option 2","Option 3"]}/></Field><Field label="Messages"><textarea className="control h-32 resize-y" name="message" placeholder="Type your message here…" required/></Field><button className="btn btn-primary h-11 w-full">Send Message <Send size={17}/></button></form></Card>
      </div>
      <div className="space-y-6">
        <Card title="Example Form With Icons"><form className="space-y-6" onSubmit={submit("Account")}><IconInput icon={<UserRound size={18}/>} placeholder="Username"/><IconInput icon={<Mail size={18}/>} type="email" placeholder="Email Address"/><IconInput icon={<LockKeyhole size={18}/>} type="password" placeholder="Password"/><IconInput icon={<LockKeyhole size={18}/>} type="password" placeholder="Confirm Password"/><div className="flex items-center justify-between gap-4 pt-1"><label className="flex items-center gap-3 text-sm font-medium"><input className="h-5 w-5 rounded accent-[#465fff]" type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)}/>Remember me</label><button className="btn btn-primary h-11 !px-5">Create Account <ArrowRight size={17}/></button></div></form></Card>
        <Card title="Example Form"><form className="space-y-7" onSubmit={submit("Personal information")}><section><h2 className="mb-5 font-semibold">Personal Info</h2><div className="grid gap-6 sm:grid-cols-2"><Field label="First Name"><input className="control" placeholder="Enter first name"/></Field><Field label="Last Name"><input className="control" placeholder="Enter last name"/></Field><Field label="Gender"><Select options={["Male","Female","Others"]}/></Field><Field label="Date of Birth"><PremiumDatePicker name="date-of-birth"/></Field><Field label="Category"><Select options={["Category 1","Category 2","Category 3"]}/></Field></div></section><section className="border-t border-[var(--border)] pt-7"><h2 className="mb-5 font-semibold">Address</h2><div className="grid gap-6 sm:grid-cols-2"><Field label="Street"><input className="control" placeholder="Street address"/></Field><Field label="City"><input className="control" placeholder="City"/></Field><Field label="State"><input className="control" placeholder="State"/></Field><Field label="Post Code"><input className="control" placeholder="Post code"/></Field><Field label="Category"><Select options={["Bangladesh","United States","Canada"]} placeholder="--Select Country--"/></Field></div></section><div className="flex flex-wrap items-center gap-x-7 gap-y-3"><span className="text-sm font-medium">Membership:</span>{["Free","Premium"].map(item => <label className="flex cursor-pointer items-center gap-2.5 text-sm" key={item}><input className="peer sr-only" type="radio" checked={membership === item} onChange={() => setMembership(item)}/><span className="grid h-5 w-5 place-items-center rounded-full border border-[#d0d5dd] transition peer-checked:border-[#465fff]"><span className="h-2.5 w-2.5 rounded-full bg-transparent peer-checked:bg-[#465fff]"/></span>{item}</label>)}</div><div className="flex justify-end gap-3 border-t border-[var(--border)] pt-6"><button type="submit" className="btn btn-primary">Save Changes</button><button type="reset" className="btn" onClick={() => { setMembership("Free"); setMessage(""); }}>Cancel</button></div></form></Card>
      </div>
    </div>
  </div>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel overflow-hidden"><header className="border-b border-[var(--border)] px-6 py-5"><h2 className="text-base font-semibold">{title}</h2></header><div className="p-6">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
function PremiumDatePicker({ name }: { name: string }) {
  const today = new Date();
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState<Date | null>(null);
  const [month, setMonth] = useState(() => new Date(today.getFullYear(), today.getMonth(), 1));
  const days = useMemo(() => {
    const year = month.getFullYear(), monthIndex = month.getMonth();
    return [...Array(new Date(year, monthIndex, 1).getDay()).fill(null), ...Array.from({ length: new Date(year, monthIndex + 1, 0).getDate() }, (_, index) => new Date(year, monthIndex, index + 1))];
  }, [month]);
  const sameDay = (left: Date | null, right: Date) => Boolean(left && left.getFullYear() === right.getFullYear() && left.getMonth() === right.getMonth() && left.getDate() === right.getDate());
  const value = selected ? `${selected.getFullYear()}-${String(selected.getMonth() + 1).padStart(2, "0")}-${String(selected.getDate()).padStart(2, "0")}` : "";
  return <div className="relative">
    <input type="hidden" name={name} value={value}/>
    <button type="button" className="control !flex h-11 items-center justify-between py-0 text-left" aria-haspopup="dialog" aria-expanded={open} onClick={() => setOpen((value) => !value)}><span className={`truncate ${selected ? "" : "muted"}`}>{selected ? new Intl.DateTimeFormat("en-US", { month: "short", day: "2-digit", year: "numeric" }).format(selected) : "Select a date"}</span><CalendarDays className="muted shrink-0" size={18}/></button>
    {open ? <div className="panel absolute right-0 z-40 mt-2 w-[min(20rem,calc(100vw-3rem))] p-4 shadow-[0_12px_32px_rgb(16_24_40/.16)]" role="dialog" aria-label="Choose date of birth">
      <div className="mb-4 flex items-center justify-between"><button type="button" className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Previous month" onClick={() => setMonth((date) => new Date(date.getFullYear(), date.getMonth() - 1, 1))}><ChevronLeft size={17}/></button><p className="text-sm font-semibold">{new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric" }).format(month)}</p><button type="button" className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Next month" onClick={() => setMonth((date) => new Date(date.getFullYear(), date.getMonth() + 1, 1))}><ChevronRight size={17}/></button></div>
      <div className="grid grid-cols-7 text-center text-xs font-medium text-[var(--muted)]">{["Su","Mo","Tu","We","Th","Fr","Sa"].map((day) => <span className="py-2" key={day}>{day}</span>)}</div>
      <div className="grid grid-cols-7 gap-1">{days.map((date, index) => date ? <button type="button" className={`grid aspect-square place-items-center rounded-lg text-sm hover:bg-indigo-50 hover:text-[#465fff] dark:hover:bg-indigo-500/10 ${sameDay(selected, date) ? "bg-[#465fff] text-white hover:bg-[#465fff] hover:text-white" : sameDay(today, date) ? "border border-[#465fff] text-[#465fff]" : ""}`} key={date.toISOString()} onClick={() => { setSelected(date); setOpen(false); }}>{date.getDate()}</button> : <span key={`empty-${index}`}/>)}</div>
      <div className="mt-3 flex justify-between border-t border-[var(--border)] pt-3"><button type="button" className="text-sm text-[var(--muted)] hover:text-[var(--text)]" onClick={() => setSelected(null)}>Clear</button><button type="button" className="text-sm font-medium text-[#465fff]" onClick={() => { setSelected(today); setMonth(new Date(today.getFullYear(), today.getMonth(), 1)); setOpen(false); }}>Today</button></div>
    </div> : null}
  </div>;
}
function Select({ options, placeholder = "Select an option" }: { options: string[]; placeholder?: string }) { return <div className="relative"><select className="control appearance-none" defaultValue=""><option value="" disabled>{placeholder}</option>{options.map(option => <option key={option}>{option}</option>)}</select><ChevronDown className="muted pointer-events-none absolute right-4 top-1/2 -translate-y-1/2" size={17}/></div>; }
function IconInput({ icon, ...props }: { icon: React.ReactNode } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="control !flex h-11 items-center gap-3 !p-0 focus-within:border-[#465fff] focus-within:shadow-[0_0_0_3px_rgb(70_95_255/.12)]"><span className="muted shrink-0 pl-4" aria-hidden="true">{icon}</span><input className="h-full min-w-0 flex-1 bg-transparent pr-4 outline-none" {...props}/></label>; }
