"use client";

import { ArrowRight, ChevronDown, ChevronRight, LockKeyhole, Mail, Send, UserRound } from "lucide-react";
import { useState } from "react";

export default function FormLayoutPage() {
  const [remember, setRemember] = useState(false), [membership, setMembership] = useState("Free"), [message, setMessage] = useState("");
  const submit = (label: string) => (event: React.FormEvent) => { event.preventDefault(); setMessage(`${label} submitted successfully.`); };
  return <div className="space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">Form Layout</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Form Layout</span></nav></header>
    {message ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700" role="status">{message}</div> : null}
    <div className="grid items-start gap-6 xl:grid-cols-2">
      <div className="space-y-6">
        <Card title="Basic Form"><form className="space-y-6" onSubmit={submit("Basic form")}><div className="grid gap-6 sm:grid-cols-2"><input className="control" placeholder="Name" aria-label="Name"/><input className="control" type="email" placeholder="Email address" aria-label="Email address"/></div><input className="control" type="password" placeholder="Password" aria-label="Password"/><input className="control" type="password" placeholder="Confirm Password" aria-label="Confirm Password"/><button className="btn btn-primary h-11 w-full">Submit</button></form></Card>
        <Card title="Example Form"><form className="space-y-6" onSubmit={submit("Message")}><div className="grid gap-6 sm:grid-cols-2"><Field label="First Name"><input className="control" placeholder="Enter first name" required/></Field><Field label="Last Name"><input className="control" placeholder="Enter last name" required/></Field></div><Field label="Email"><input className="control" type="email" placeholder="Enter email address" required/></Field><Field label="Subject"><Select options={["Option 1","Option 2","Option 3"]}/></Field><Field label="Messages"><textarea className="control min-h-32 resize-y" placeholder="Type your message" required/></Field><button className="btn btn-primary h-11 w-full">Send Message <Send size={17}/></button></form></Card>
      </div>
      <div className="space-y-6">
        <Card title="Example Form With Icons"><form className="space-y-6" onSubmit={submit("Account")}><IconInput icon={<UserRound size={18}/>} placeholder="Username"/><IconInput icon={<Mail size={18}/>} type="email" placeholder="Email Address"/><IconInput icon={<LockKeyhole size={18}/>} type="password" placeholder="Password"/><IconInput icon={<LockKeyhole size={18}/>} type="password" placeholder="Confirm Password"/><div className="flex items-center justify-between gap-4 pt-1"><label className="flex items-center gap-3 text-sm font-medium"><input className="h-5 w-5 rounded accent-[#465fff]" type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)}/>Remember me</label><button className="btn btn-primary h-11 !px-5">Create Account <ArrowRight size={17}/></button></div></form></Card>
        <Card title="Example Form"><form className="space-y-7" onSubmit={submit("Personal information")}><section><h2 className="mb-5 font-semibold">Personal Info</h2><div className="grid gap-6 sm:grid-cols-2"><Field label="First Name"><input className="control" placeholder="Enter first name"/></Field><Field label="Last Name"><input className="control" placeholder="Enter last name"/></Field><Field label="Gender"><Select options={["Male","Female","Others"]}/></Field><Field label="Date of Birth"><input className="control" type="date"/></Field><Field label="Category"><Select options={["Category 1","Category 2","Category 3"]}/></Field></div></section><section className="border-t border-[var(--border)] pt-7"><h2 className="mb-5 font-semibold">Address</h2><div className="grid gap-6 sm:grid-cols-2"><Field label="Street"><input className="control" placeholder="Street address"/></Field><Field label="City"><input className="control" placeholder="City"/></Field><Field label="State"><input className="control" placeholder="State"/></Field><Field label="Post Code"><input className="control" placeholder="Post code"/></Field><Field label="Category"><Select options={["Bangladesh","United States","Canada"]} placeholder="--Select Country--"/></Field></div></section><div className="flex flex-wrap items-center gap-x-7 gap-y-3"><span className="text-sm font-medium">Membership:</span>{["Free","Premium"].map(item => <label className="flex cursor-pointer items-center gap-2.5 text-sm" key={item}><input className="peer sr-only" type="radio" checked={membership === item} onChange={() => setMembership(item)}/><span className="grid h-5 w-5 place-items-center rounded-full border border-[#d0d5dd] transition peer-checked:border-[#465fff]"><span className="h-2.5 w-2.5 rounded-full bg-transparent peer-checked:bg-[#465fff]"/></span>{item}</label>)}</div><div className="flex justify-end gap-3 border-t border-[var(--border)] pt-6"><button type="submit" className="btn btn-primary">Save Changes</button><button type="reset" className="btn" onClick={() => { setMembership("Free"); setMessage(""); }}>Cancel</button></div></form></Card>
      </div>
    </div>
  </div>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel overflow-hidden"><header className="border-b border-[var(--border)] px-6 py-5"><h2 className="text-base font-semibold">{title}</h2></header><div className="p-6">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
function Select({ options, placeholder = "Select an option" }: { options: string[]; placeholder?: string }) { return <div className="relative"><select className="control appearance-none" defaultValue=""><option value="" disabled>{placeholder}</option>{options.map(option => <option key={option}>{option}</option>)}</select><ChevronDown className="muted pointer-events-none absolute right-4 top-1/2 -translate-y-1/2" size={17}/></div>; }
function IconInput({ icon, ...props }: { icon: React.ReactNode } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="control flex h-11 items-center gap-3 !p-0"><span className="muted pl-4">{icon}</span><input className="h-full min-w-0 flex-1 bg-transparent pr-4 outline-none" {...props}/></label>; }
