"use client";

import { Archive, ArrowLeft, ChevronLeft, ChevronRight, Download, FileText, Info, Inbox, LockKeyhole, Mail, Pencil, Reply, ReplyAll, Send, Star, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const mailboxes = [{ name: "Inbox", icon: Inbox, count: 3 },{ name: "Sent", icon: Send },{ name: "Drafts", icon: Mail },{ name: "Spam", icon: LockKeyhole, count: 2 },{ name: "Trash", icon: Trash2 },{ name: "Archive", icon: Archive }];
export default function InboxDetailsPage() {
  const [box, setBox] = useState("Inbox"), [position, setPosition] = useState(4), [compose, setCompose] = useState(false), [mode, setMode] = useState<"Reply" | "Reply all" | "Forward">("Reply"), [replyOpen, setReplyOpen] = useState(false), [reply, setReply] = useState(""), [sent, setSent] = useState(false);
  const openReply = (next: typeof mode) => { setMode(next); setReplyOpen(true); setSent(false); };
  return <div className="space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">Inbox Details</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Inbox Details</span></nav></header>
    <div className="grid h-[550px] gap-5 lg:grid-cols-[214px_minmax(0,1fr)]">
      <aside className="panel overflow-hidden p-4"><button className="btn btn-primary h-11 w-full" onClick={() => setCompose(true)}><Pencil size={17}/>Compose</button><div className="mt-5 h-[455px] overflow-y-auto pr-1"><Section title="MAILBOX">{mailboxes.map(item => { const Icon=item.icon; return <button className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${box === item.name ? "bg-indigo-50 text-[#465fff]" : "muted hover:bg-[var(--soft)]"}`} onClick={() => setBox(item.name)} key={item.name}><Icon size={18}/>{item.name}{item.count ? <span className="ml-auto">{item.count}</span> : null}</button>; })}</Section><Section title="FILTER"><SideItem icon={<Star size={18}/>} label="Starred"/><SideItem icon={<LockKeyhole size={18}/>} label="Important"/></Section><Section title="LABEL"><Label color="bg-sky-500" text="Personal"/><Label color="bg-orange-500" text="Work"/><Label color="bg-emerald-500" text="Payments"/><Label color="bg-violet-500" text="Invoices"/></Section></div></aside>
      <section className="panel min-w-0 overflow-hidden"><header className="flex h-[72px] items-center gap-2 border-b border-[var(--border)] px-4"><Link href="/inbox" className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Back to inbox"><ArrowLeft size={17}/></Link><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Delete email"><Trash2 size={17}/></button><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Email information"><Info size={18}/></button><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Archive email"><Archive size={17}/></button><button className="grid h-10 w-10 place-items-center rounded-lg border border-[var(--border)] hover:bg-[var(--soft)]" aria-label="Mark unread"><Mail size={17}/></button><div className="ml-auto flex items-center gap-2"><span className="muted mr-2 text-sm">{position} of 120</span><button className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] disabled:opacity-40" disabled={position===1} onClick={() => setPosition(value=>Math.max(1,value-1))} aria-label="Previous email"><ChevronLeft size={16}/></button><button className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)]" onClick={() => setPosition(value=>Math.min(120,value+1))} aria-label="Next email"><ChevronRight size={16}/></button></div></header>
        <div className="h-[478px] overflow-y-auto px-6 py-6"><header className="flex items-start gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-br from-orange-100 to-indigo-100 text-sm font-semibold text-indigo-700">CC</span><div><h2 className="font-semibold">Contact For “Website Design”</h2><p className="muted mt-1 text-xs">Codescandy hello@example.com</p></div></header><article className="muted mt-9 space-y-5 text-sm leading-5 text-[var(--text)]"><p>Hello Dear Alexander,</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut rutrum mi. Aenean ac leo non justo suscipit consectetur. Nam vestibulum eleifend magna quis porta. ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut rutrum mi. Aenean ac leo</p><p>Praesent ut rutrum mi. Aenean ac leo non justo suscipit consectetur. Nam vestibulum eleifend magna quis porta.</p><p>Nullam tincidunt sodales diam, quis rhoncus dolor aliquet a. Nulla a rhoncus lectus. In nunc neque, pellentesque non massa ornare, accumsan ornare massa. sodales diam, quis rhoncus dolor aliquet a. Nulla a rhoncus lectus. In nunc neque</p><p>Suspendisse semper vel turpis vitae aliquam. Aenean semper dui in consequat ullamcorper.</p><p>Nullam tincidunt sodales diam, quis rhoncus dolor aliquet a. Nulla a rhoncus lectus. In nunc neque, pellentesque non massa ornare, accumsan ornare massa. sodales diam, quis rhoncus dolor aliquet a. Nulla a rhoncus lectus. In nunc neque</p><p>Praesent ut rutrum mi. Aenean ac leo non justo suscipit consectetur. Nam vestibulum eleifend magna quis porta.</p></article><section className="mt-8"><h3 className="font-semibold">2 Attachments</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Attachment name="Guidelines.pdf" type="PDF"/><Attachment name="Branding Assets" type="Media"/></div></section><div className="mt-8 flex flex-wrap gap-3"><button className="btn" onClick={()=>openReply("Reply")}><Reply size={17}/>Reply</button><button className="btn" onClick={()=>openReply("Reply all")}><ReplyAll size={17}/>Reply all</button><button className="btn" onClick={()=>openReply("Forward")}><Send size={17}/>Forward</button></div>{replyOpen ? <form className="mt-5 rounded-xl border border-[var(--border)] p-4" onSubmit={event=>{event.preventDefault();if(reply.trim()){setSent(true);setReply("");}}}><h3 className="mb-3 text-sm font-semibold">{mode}</h3><textarea className="control min-h-28" placeholder={`Write your ${mode.toLowerCase()}...`} value={reply} onChange={event=>setReply(event.target.value)}/><div className="mt-3 flex items-center justify-end gap-3">{sent ? <span className="mr-auto text-sm text-emerald-600">Message sent</span> : null}<button type="button" className="btn" onClick={()=>setReplyOpen(false)}>Cancel</button><button className="btn btn-primary">Send</button></div></form> : null}</div>
      </section>
    </div>
    {compose ? <div className="fixed inset-0 z-[80] grid place-items-center bg-black/30 p-4" onMouseDown={event=>{if(event.target===event.currentTarget)setCompose(false)}}><section className="panel w-full max-w-xl p-6" role="dialog" aria-modal="true" aria-labelledby="compose-detail-title"><h2 id="compose-detail-title" className="text-lg font-semibold">New Message</h2><div className="mt-5 space-y-4"><input className="control" placeholder="To"/><input className="control" placeholder="Subject"/><textarea className="control min-h-40" placeholder="Write your message..."/><div className="flex justify-end gap-3"><button className="btn" onClick={()=>setCompose(false)}>Close</button><button className="btn btn-primary" onClick={()=>setCompose(false)}>Send</button></div></div></section></div> : null}
  </div>;
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mb-6"><h2 className="muted mb-2 px-1 text-[11px] font-medium">{title}</h2><div className="space-y-1">{children}</div></section>}
function SideItem({icon,label}:{icon:React.ReactNode;label:string}){return <button className="muted flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm hover:bg-[var(--soft)]">{icon}{label}</button>}
function Label({color,text}:{color:string;text:string}){return <button className="muted flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-[var(--soft)]"><i className={`h-2.5 w-2.5 rounded-full ${color}`}/>{text}</button>}
function Attachment({name,type}:{name:string;type:string}){return <article className="flex items-center gap-3 rounded-xl border border-[var(--border)] p-4"><span className="grid h-10 w-10 place-items-center rounded-lg bg-indigo-50 text-[#465fff]"><FileText size={19}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{name}</p><p className="muted mt-1 text-xs">{type}</p></div><button className="muted rounded-lg p-2 hover:bg-[var(--soft)]" onClick={()=>alert(`Downloading ${name}`)} aria-label={`Download ${name}`}><Download size={18}/></button></article>}
