"use client";

import { ChevronLeft, ChevronRight, Link2 } from "lucide-react";
import { useRef, useState } from "react";

type Reply = { id: number; name: string; email: string; time: string; support?: boolean; body: React.ReactNode };
const firstMessage = <><p>Hi TailAdmin Team,<br/>I hope you&apos;re doing well.</p><p className="mt-5">I’m currently working on customizing the TailAdmin dashboard and would like to add a new section labeled “Reports.” Before I proceed, I wanted to check if there’s any official guide or best practice you recommend for adding custom pages within the TailAdmin structure.</p></>;
const startingReplies: Reply[] = [
  { id: 1, name: "John Doe", email: "jhondelin@gmail.com", time: "Mon, 3:20 PM (2 hrs ago)", body: firstMessage },
  { id: 2, name: "Musharof Chowdhury", email: "From - tailadmin support team", time: "Mon, 3:20 PM (2 hrs ago)", support: true, body: <><p>Hi John D,</p><p className="mt-5">Thanks for reaching out—and great to hear you&apos;re customizing TailAdmin to fit your needs! Yes, you can definitely add custom pages like a “Reports” section, and it&apos;s quite straightforward. Here&apos;s a quick guide to help you get started:</p><p className="mt-5">To include your new page in the sidebar:</p><ul className="mt-2 list-disc space-y-1 pl-5"><li>Go to the sidebar configuration file (sidebarData.ts or similar)</li><li>Add a new entry with the label “Reports” and route /reports</li></ul></> },
  { id: 3, name: "John Doe", email: "jhondelin@gmail.com", time: "Mon, 3:20 PM (2 hrs ago)", body: firstMessage },
];

export default function SupportTicketReplyPage() {
  const [replies, setReplies] = useState(startingReplies), [reply, setReply] = useState(""), [attachment, setAttachment] = useState(""), [status, setStatus] = useState("In-Progress"), [position, setPosition] = useState(4);
  const fileRef = useRef<HTMLInputElement>(null);
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!reply.trim() && !attachment) return; setReplies(items => [...items, { id: Date.now(), name: "Aarthi", email: "From - support team", time: "Just now", support: true, body: <><p>{reply.trim()}</p>{attachment ? <p className="mt-3 rounded-lg bg-[var(--soft)] px-3 py-2 text-sm"><Link2 className="mr-2 inline" size={14}/>{attachment}</p> : null}</> }]); setReply(""); setAttachment(""); };
  return <div className="space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">Support Reply</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">Support Reply</span></nav></header>
    <div className="grid items-start gap-5 xl:grid-cols-12">
      <section className="panel overflow-hidden xl:col-span-8"><header className="flex min-h-[79px] items-center border-b border-[var(--border)] px-5"><div><h2 className="text-lg font-semibold">Ticket #346520 - Sidebar not responsive on mobile</h2><p className="muted mt-1 text-sm">Mon, 3:20 PM (2 days ago)</p></div><div className="ml-auto flex items-center gap-2"><span className="muted mr-2 text-sm">{position} of 120</span><button className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)] disabled:opacity-40" disabled={position === 1} onClick={() => setPosition(value => Math.max(1,value - 1))} aria-label="Previous ticket"><ChevronLeft size={17}/></button><button className="grid h-9 w-9 place-items-center rounded-lg border border-[var(--border)]" onClick={() => setPosition(value => Math.min(120,value + 1))} aria-label="Next ticket"><ChevronRight size={17}/></button></div></header>
        <div className="max-h-[680px] overflow-y-auto px-6 py-2">{replies.map(item => <article className="border-b border-[var(--border)] py-6 last:border-b-0" key={item.id}><header className="flex items-start gap-3"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full text-xs font-semibold ${item.support ? "bg-indigo-100 text-[#465fff]" : "bg-orange-100 text-orange-700"}`}>{item.name.split(" ").map(part => part[0]).join("").slice(0,2)}</span><div><h3 className="text-sm font-medium">{item.name}</h3><p className="muted mt-1 text-xs">{item.email}</p></div><time className="muted ml-auto text-xs">{item.time}</time></header><div className="muted ml-14 mt-5 text-sm leading-5 text-[var(--text)]">{item.body}</div></article>)}</div>
        <form className="mx-6 mb-6 rounded-xl border border-[var(--border)]" onSubmit={submit}><textarea className="min-h-[96px] w-full resize-y bg-transparent p-5 outline-none" placeholder="Type your reply here..." value={reply} onChange={event => setReply(event.target.value)}/><div className="flex items-center px-3 pb-3"><button className="muted flex items-center gap-2 rounded-lg px-2 py-2 text-sm hover:bg-[var(--soft)]" type="button" onClick={() => fileRef.current?.click()}><Link2 size={17}/>Attach</button><input ref={fileRef} className="sr-only" type="file" onChange={event => setAttachment(event.target.files?.[0]?.name ?? "")}/>{attachment ? <span className="muted ml-2 max-w-48 truncate text-xs">{attachment}</span> : null}<button className="btn btn-primary ml-auto h-10 !px-5">Reply</button></div></form>
        <fieldset className="flex flex-wrap items-center gap-6 border-t border-[var(--border)] px-6 py-5"><legend className="sr-only">Ticket status</legend><span className="text-sm font-medium">Status:</span>{["In-Progress","Solved","On-Hold"].map(item => <label className="flex cursor-pointer items-center gap-2 text-sm" key={item}><input className="peer sr-only" type="radio" checked={status === item} onChange={() => setStatus(item)}/><span className="grid h-5 w-5 place-items-center rounded-full border border-[#d0d5dd] peer-checked:border-[#465fff]"><i className={`h-2.5 w-2.5 rounded-full ${status === item ? "bg-[#465fff]" : ""}`}/></span>{item}</label>)}</fieldset>
      </section>
      <aside className="panel overflow-hidden xl:col-span-4"><header className="border-b border-[var(--border)] px-6 py-5"><h2 className="text-xl font-semibold">Ticket Details</h2></header><dl className="divide-y divide-[var(--border)] px-6 py-3">{[["Customer","John Doe"],["Email","jhondelin@gmail.com"],["Ticket ID","#346520"],["Category","General Support"],["Created","Dec 20, 2028"]].map(([term,value]) => <div className="grid grid-cols-[112px_minmax(0,1fr)] gap-4 py-4 text-sm" key={term}><dt className="muted">{term}</dt><dd className="break-words">{value}</dd></div>)}<div className="grid grid-cols-[112px_minmax(0,1fr)] gap-4 py-4 text-sm"><dt className="muted">Status</dt><dd><span className="rounded-full bg-sky-50 px-2 py-1 text-xs text-sky-600">{status.replace("-"," ")}</span></dd></div></dl></aside>
    </div>
  </div>;
}
