"use client";

import { CalendarDays, ChevronDown, ChevronRight, Clipboard, Clock3, CloudUpload, Eye, EyeOff, Mail, X } from "lucide-react";
import { useRef, useState } from "react";

export default function FormElementsPage() {
  const [showPassword, setShowPassword] = useState(false), [selected, setSelected] = useState(["Option 1", "Option 3"]), [copied, setCopied] = useState(false), [fileName, setFileName] = useState("No file chosen"), [dropName, setDropName] = useState("");
  const [checked, setChecked] = useState(true), [radio, setRadio] = useState("Selected"), [toggleOne, setToggleOne] = useState(true), [toggleTwo, setToggleTwo] = useState(true);
  const fileRef = useRef<HTMLInputElement>(null);
  const copy = async () => { await navigator.clipboard?.writeText("www.tailadmin.com"); setCopied(true); window.setTimeout(() => setCopied(false), 1200); };
  return <div className="form-elements-page space-y-6">
    <header className="flex items-center justify-between"><h1 className="text-xl font-semibold leading-6">From Elements</h1><nav className="muted flex items-center gap-2 text-sm"><span>Home</span><ChevronRight size={15}/><span className="text-[var(--text)]">From Elements</span></nav></header>
    <div className="grid items-start gap-6 xl:grid-cols-2">
      <div className="space-y-6">
        <FormCard title="Default Inputs"><Field label="Input"><input className="control"/></Field><Field label="Input with Placeholder"><input className="control" placeholder="info@gmail.com"/></Field><Field label="Select Input"><Select/></Field><Field label="Password Input"><div className="relative"><input className="control pr-12" type={showPassword ? "text" : "password"} placeholder="Enter your password"/><button type="button" className="muted absolute right-4 top-1/2 -translate-y-1/2" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <Eye size={19}/> : <EyeOff size={19}/>}</button></div></Field><Field label="Date Picker Input"><IconControl icon={<CalendarDays size={19}/>}><input className="h-full w-full bg-transparent outline-none" type="date" aria-label="Select a date"/></IconControl></Field><Field label="Time Picker Input"><IconControl icon={<Clock3 size={19}/>}><input className="h-full w-full bg-transparent outline-none" type="time" aria-label="Select a time"/></IconControl></Field><Field label="Input with Payment"><div className="control flex items-center !p-0"><span className="border-r border-[var(--border)] px-4 py-3">$</span><input className="min-w-0 flex-1 bg-transparent px-4 outline-none" placeholder="0000"/></div></Field></FormCard>
        <FormCard title="Select Inputs"><Field label="Select Input"><Select placeholder="Select Option"/></Field><Field label="Multiple Select Options"><div className="control flex min-h-12 flex-wrap items-center gap-2">{selected.map(item => <span className="flex items-center gap-1 rounded-md bg-indigo-50 px-2 py-1 text-xs text-[#465fff]" key={item}>{item}<button onClick={() => setSelected(values => values.filter(value => value !== item))} aria-label={`Remove ${item}`}><X size={13}/></button></span>)}<select className="min-w-28 flex-1 bg-transparent text-sm outline-none" aria-label="Add select option" value="" onChange={event => { if (event.target.value && !selected.includes(event.target.value)) setSelected(values => [...values,event.target.value]); }}><option value="">Select option</option>{["Option 1","Option 2","Option 3","Option 4"].map(item => <option key={item}>{item}</option>)}</select></div><p className="muted mt-2 text-sm">Selected Values: {selected.join(", ")}</p></Field></FormCard>
        <FormCard title="Textarea input field"><Field label="Description"><textarea className="control min-h-28 resize-y" placeholder="Description"/></Field><Field label="Description"><textarea className="control min-h-28 border-red-400" defaultValue="Description"/><p className="mt-2 text-sm text-red-500">Please enter a valid message.</p></Field></FormCard>
        <FormCard title="Input States" subtitle="Validation styles for error, success and disabled states on form controls."><Field label="Email"><input className="control border-emerald-400" defaultValue="info@gmail.com"/><p className="mt-2 text-sm text-emerald-600">This is an success message.</p></Field><Field label="Email"><input className="control cursor-not-allowed bg-[var(--soft)]" value="info@gmail.com" disabled readOnly/></Field></FormCard>
      </div>
      <div className="space-y-6">
        <FormCard title="Input Group"><Field label="Email"><IconControl icon={<Mail size={18}/>}><input className="h-full w-full bg-transparent outline-none" placeholder="info@gmail.com"/></IconControl></Field><Field label="Phone"><div className="control flex !p-0"><select className="border-r border-[var(--border)] bg-transparent px-3 outline-none" aria-label="Phone country"><option>US</option><option>GB</option><option>CA</option><option>AU</option></select><input className="min-w-0 flex-1 bg-transparent px-4 outline-none" defaultValue="+1" aria-label="Phone number"/></div></Field><Field label="Website"><div className="control flex !p-0"><input className="min-w-0 flex-1 bg-transparent px-4 outline-none" defaultValue="+1"/><select className="border-l border-[var(--border)] bg-transparent px-3 outline-none" aria-label="Website country"><option>US</option><option>GB</option><option>CA</option><option>AU</option></select></div></Field><Field label="URL"><div className="control flex !p-0"><span className="border-r border-[var(--border)] px-4 py-3">http://</span><input className="min-w-0 flex-1 bg-transparent px-4 outline-none" placeholder="www.tailadmin.com"/></div></Field><Field label="Website"><div className="control flex !p-0"><input className="min-w-0 flex-1 bg-transparent px-4 outline-none" value="www.tailadmin.com" readOnly/><button className="flex items-center gap-2 border-l border-[var(--border)] px-4 font-medium" onClick={copy}><Clipboard size={17}/>{copied ? "Copied" : "Copy"}</button></div></Field></FormCard>
        <FormCard title="File Input"><Field label="Upload file"><button className="control flex items-center !p-0 text-left" onClick={() => fileRef.current?.click()}><span className="border-r border-[var(--border)] px-4 py-3 font-medium">Choose File</span><span className="muted truncate px-4">{fileName}</span></button><input ref={fileRef} className="sr-only" type="file" onChange={event => setFileName(event.target.files?.[0]?.name ?? "No file chosen")}/></Field></FormCard>
        <FormCard title="Checkbox"><div className="grid gap-5"><CheckControl label="Default" checked={false}/><CheckControl label="Checked" checked={checked} onChange={setChecked}/><CheckControl label="Disabled" checked={false} disabled/></div></FormCard>
        <FormCard title="Radio Buttons"><div className="grid gap-5">{["Default","Selected","Disabled"].map(item => <label className={`flex items-center gap-3 text-sm ${item === "Disabled" ? "muted" : ""}`} key={item}><input className="h-5 w-5 accent-[#465fff]" type="radio" disabled={item === "Disabled"} checked={radio === item} onChange={() => setRadio(item)}/>{item}</label>)}</div></FormCard>
        <FormCard title="Toggle switch input"><div className="grid grid-cols-2 gap-x-10 gap-y-5"><Toggle label="Default" checked={false}/><Toggle label="Default" checked={false} square/><Toggle label="Checked" checked={toggleOne} onChange={setToggleOne}/><Toggle label="Checked" checked={toggleTwo} onChange={setToggleTwo} square/><Toggle label="Disabled" checked={false} disabled/><Toggle label="Disabled" checked={false} disabled square/></div></FormCard>
        <FormCard title="Dropzone"><div className={`grid min-h-64 place-items-center rounded-xl border border-dashed p-8 text-center ${dropName ? "border-[#465fff] bg-indigo-50/40" : "border-[var(--border)] bg-[var(--soft)]"}`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); setDropName(event.dataTransfer.files[0]?.name ?? ""); }}><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[var(--panel)] text-[#465fff]"><CloudUpload size={26}/></span><h3 className="mt-4 font-semibold">Drag &amp; Drop Files Here</h3><p className="muted mt-2 text-sm">{dropName || "Drag and drop your PNG, JPG, WebP, SVG images here or browse"}</p><label className="mt-4 inline-block cursor-pointer text-sm font-semibold text-[#465fff] underline">Browse File<input className="sr-only" type="file" onChange={event => setDropName(event.target.files?.[0]?.name ?? "")}/></label></div></div></FormCard>
      </div>
    </div>
  </div>;
}

function FormCard({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section className="panel overflow-hidden"><header className="border-b border-[var(--border)] px-6 py-5"><h2 className="text-base font-semibold">{title}</h2>{subtitle ? <p className="muted mt-1 text-sm">{subtitle}</p> : null}</header><div className="space-y-6 p-6">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>; }
function Select({ placeholder = "Select an option" }: { placeholder?: string }) { return <div className="relative"><select className="control appearance-none" defaultValue=""><option value="" disabled>{placeholder}</option><option>Marketing</option><option>Template</option><option>Development</option></select><ChevronDown className="muted pointer-events-none absolute right-4 top-1/2 -translate-y-1/2" size={18}/></div>; }
function IconControl({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) { return <div className="control flex h-11 items-center gap-3">{icon}<span className="h-5 border-l border-[var(--border)]"/>{children}</div>; }
function CheckControl({ label, checked, disabled, onChange }: { label: string; checked: boolean; disabled?: boolean; onChange?: (value: boolean) => void }) { return <label className={`flex items-center gap-3 text-sm ${disabled ? "muted" : ""}`}><input className="h-5 w-5 rounded accent-[#465fff]" type="checkbox" checked={checked} disabled={disabled} onChange={event => onChange?.(event.target.checked)}/>{label}</label>; }
function Toggle({ label, checked, disabled, square, onChange }: { label: string; checked: boolean; disabled?: boolean; square?: boolean; onChange?: (value: boolean) => void }) { return <label className={`flex items-center gap-3 text-sm ${disabled ? "muted" : ""}`}><button type="button" disabled={disabled} role="switch" aria-checked={checked} onClick={() => onChange?.(!checked)} className={`relative h-6 w-11 ${square ? "rounded-md" : "rounded-full"} ${checked ? "bg-[#465fff]" : "bg-[#d0d5dd]"}`}><span className={`absolute left-1 top-1 h-4 w-4 bg-white transition-transform ${square ? "rounded-[3px]" : "rounded-full"} ${checked ? "translate-x-5" : "translate-x-0"}`}/></button>{label}</label>; }
